Repository prefeiturasp/SME-Terceirizadas-Frontend, pull requests merged in 2021-07, with the labels that each got.

#849 Bugfix/40754 erro validacao
  src/components/screens/DietaEspecial/Escola/index.jsx
  src/helpers/fieldValidators.js
Labels: bug

#854 Development
  package-lock.json
  package.json
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/ClassificacaoDaDieta/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/DataOpcional/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/DataTermino/componentes/DataOpcional/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/DataTermino/componentes/DataOpcional/style.scss
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/DataTermino/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/DataTermino/style.scss
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/Diagnosticos/Field.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/Diagnosticos/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/Diagnosticos/style.scss
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/IdentificacaoNutricionista/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/InformacoesAdicionais/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/ModalAdicionaProtocolo/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/ModalSolicitacaoCadastroProduto/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/ModalSolicitacaoCadastroProduto/styles.scss
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/Orientacoes/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/Protocolos/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/SubstituicoesField/MultiSelect/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/SubstituicoesField/Substituicao.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/SubstituicoesField/SubstituicaoFinalForm.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/SubstituicoesField/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/SubstituicoesField/style.scss
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/helper.js
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/style.scss
  src/components/screens/DietaEspecial/Relatorio/componentes/ModalNegaDietaEspecial/index.jsx
  src/components/screens/DietaEspecial/Relatorio/index.jsx
  src/helpers/fieldValidators.js
  src/services/dietaEspecial.service.js
Labels: dependencies, enhancement, feature

#855 Fix: campos substituições em todas as telas que utilizam o componente.
  src/components/screens/DietaEspecial/CadastroProtocoloPadraoDietaEsp/index.jsx
  src/components/screens/DietaEspecial/ConsultaProtocoloPadraoDieta/componentes/DetalhesProtocolo/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/Protocolos/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/helper.js
Labels: bug

#856 Hom - atualizado até 06/07 - 12:45
  src/components/screens/DietaEspecial/CadastroProtocoloPadraoDietaEsp/index.jsx
  src/components/screens/DietaEspecial/ConsultaProtocoloPadraoDieta/componentes/DetalhesProtocolo/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/Protocolos/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/helper.js
Labels: bug

#861 Feature: alterar nome do card da gestão de produtos.
  src/helpers/gestaoDeProdutos.js
Labels: feature

#862 Hom - atualizado até 08/07 - 15:20 #861
  src/helpers/gestaoDeProdutos.js
Labels: feature

#863 Feature: adicionar informações do produto no modal de responder quest…
  src/components/screens/Produto/ResponderReclamacao/ModalResponderReclamacao/index.jsx
  src/components/screens/Produto/ResponderReclamacao/Reclamacao/index.jsx
  src/components/screens/Produto/ResponderReclamacao/index.js
Labels: feature

#864 Hom - atualizado até 12/07 - 13:20 #863
  src/components/screens/Produto/ResponderReclamacao/ModalResponderReclamacao/index.jsx
  src/components/screens/Produto/ResponderReclamacao/Reclamacao/index.jsx
  src/components/screens/Produto/ResponderReclamacao/index.js
Labels: feature

#877 Feature/38866 processo resposta reclamacao
  src/components/Shareable/ModalJustificativa/index.jsx
  src/components/screens/Produto/AvaliarReclamacaoProduto/components/TabelaProdutos/index.jsx
  src/components/screens/Produto/AvaliarReclamacaoProduto/index.jsx
  src/components/screens/Produto/ResponderReclamacao/ModalResponderReclamacao/index.jsx
  src/helpers/gestaoDeProdutos.js
Labels: feature

#878 Hom - atualizado até 12/07 - 18:00 #877
  src/components/Shareable/ModalJustificativa/index.jsx
  src/components/screens/Produto/AvaliarReclamacaoProduto/components/TabelaProdutos/index.jsx
  src/components/screens/Produto/AvaliarReclamacaoProduto/index.jsx
  src/components/screens/Produto/ResponderReclamacao/ModalResponderReclamacao/index.jsx
  src/helpers/gestaoDeProdutos.js
Labels: feature

#889 Fix: set protocolo salvo na solicitacao quando o campo de seleção não…
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/index.jsx
Labels: bug

#891 HOM - Atualizado até 22/07 18:00
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/index.jsx
Labels: bug

#895 Feature: adicionar spin ao autorizar alteração UE
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/ModalAutorizaAlteracaoUE/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/index.jsx
Labels: feature

#896 HOM - Atualizado até 26/07 10:00
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/ModalAutorizaAlteracaoUE/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/index.jsx
Labels: feature
