Repository prefeiturasp/SME-Terceirizadas-Frontend, pull requests merged in 2021-12, with the labels that each got.

#1123 Fix: correção na exibição do botão para solicitações de kit lanche unificado cancelada
  src/components/SolicitacaoUnificada/Relatorio/index.jsx
  src/helpers/utilities.js
Labels: bug

#1124 Hom - Atualizado até 01/12 as 08:50
  src/components/SolicitacaoUnificada/Relatorio/index.jsx
  src/helpers/utilities.js
Labels: bug

#1127 PROD - hotfix para correção 02/12 as 13:50
  src/components/screens/Produto/AtualizacaoProdutoForm/components/WizardFormTerceiraPagina.jsx
Labels: bug

#1130 Feature/53219-DE-dieta-especial-conferida-cor-verde-somente-para-terceirizada
  src/components/Shareable/CardListarSolicitacoes/index.jsx
  src/components/Shareable/CardStatusDeSolicitacao/CardStatusDeSolicitacao.jsx
  src/helpers/terceirizadas.js
Labels: feature

#1131 Hom - Atualizado até 02/12 as 16:40
  src/components/Shareable/CardListarSolicitacoes/index.jsx
  src/components/Shareable/CardStatusDeSolicitacao/CardStatusDeSolicitacao.jsx
  src/helpers/terceirizadas.js
Labels: feature

#1133 Feature/47960-GA-incluir-campo-de-informaçõess-codae-ao-autorizar-inversão-de-cardápio
  src/components/InversaoDeDiaDeCardapio/Relatorio/index.jsx
  src/components/Shareable/ModalCODAEAutoriza/index.jsx
  src/services/inversaoDeDiaDeCardapio.service.js
Labels: feature

#1134 Feature/54008-GA-visualização-campo-de-informações-na-solicitação-de-inversão-de-cardápio
  src/components/InversaoDeDiaDeCardapio/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/Shareable/RelatorioHistoricoQuestionamento/index.jsx
Labels: feature

#1132 Feature: status do kit lanche agora é um select
  src/components/screens/Cadastros/CadastroKitLanche/index.jsx
  src/pages/Cadastros/CadastroKitLanchePage.jsx
  src/services/codae.service.js
Labels: feature

#1135 Feature/47631 campo observacao
  src/components/InclusaoDeAlimentacao/helper.js
  src/components/InclusaoDeAlimentacao/index.jsx
  src/reducers/foodInclusionReducer.js
Labels: feature

#1136 Hom - Atualizado até 08/12 as 16:00
  src/components/InclusaoDeAlimentacao/helper.js
  src/components/InclusaoDeAlimentacao/index.jsx
  src/components/InversaoDeDiaDeCardapio/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/InversaoDeDiaDeCardapio/Relatorio/index.jsx
  src/components/Shareable/ModalCODAEAutoriza/index.jsx
  src/components/Shareable/RelatorioHistoricoQuestionamento/index.jsx
  src/components/screens/Cadastros/CadastroKitLanche/index.jsx
  src/pages/Cadastros/CadastroKitLanchePage.jsx
  src/reducers/foodInclusionReducer.js
  src/services/codae.service.js
  src/services/inversaoDeDiaDeCardapio.service.js
Labels: feature

#1141 Fix/47960-GA-ajustar-validação-campo-de-informações-codae-ao-autorizar-inversão-de-cardápio
  src/components/InversaoDeDiaDeCardapio/Relatorio/index.jsx
  src/components/Shareable/ModalCODAEAutoriza/index.jsx
  src/pages/InversaoDeDiaDeCardapio/RelatorioPage.jsx
  src/services/inversaoDeDiaDeCardapio.service.js
Labels: bug

#1150 Hom - Atualizado até 13/12 as 17:00
  src/components/InversaoDeDiaDeCardapio/Relatorio/index.jsx
  src/components/Shareable/ModalCODAEAutoriza/index.jsx
  src/pages/InversaoDeDiaDeCardapio/RelatorioPage.jsx
  src/services/inversaoDeDiaDeCardapio.service.js
Labels: bug

#1157 Feature/53752 card aguardando vigenciar para terceirizada
  src/components/screens/DashBoardDietaEspecial/index.jsx
  src/pages/DietaEspecial/DashboardDietaEspecialPage.jsx
  src/services/dashBoardDietaEspecial.service.js
Labels: feature

#1156 Feature/53758 gp para perfil dre
  src/components/Shareable/Sidebar/SidebarContent.jsx
  src/components/screens/PainelInicial/index.jsx
  src/configs/RoutesConfig.js
Labels: feature

#1159 Hom - Atualizado até 14/12 as 15:30
  src/components/Shareable/NotificacoesNavbar/index.jsx
  src/components/Shareable/Sidebar/SidebarContent.jsx
  src/components/screens/Cadastros/CadastroKitLanche/index.jsx
  src/components/screens/DashBoardDietaEspecial/index.jsx
  src/components/screens/Notificacoes/components/CardNotificacao/style.scss
  src/components/screens/Notificacoes/components/Filtros/index.jsx
  src/components/screens/Notificacoes/components/Filtros/style.scss
  src/components/screens/Notificacoes/index.jsx
  src/components/screens/PainelInicial/index.jsx
  src/configs/RoutesConfig.js
  src/pages/DietaEspecial/DashboardDietaEspecialPage.jsx
  src/services/dashBoardDietaEspecial.service.js
  src/services/notificacoes.service.js
Labels: feature

#1161 Bugfix/54033 campo data solicitacao alteracao ue
  src/components/screens/DietaEspecial/AlteracaoUE/components/FormCadastro/index.jsx
Labels: bug

#1164 Bugfix/54033 campo data solicitacao alteracao ue
  src/components/screens/DietaEspecial/AlteracaoUE/components/FormCadastro/index.jsx
Labels: bug

#1168 Bugfix/54067 redirecionamento errado
  src/components/screens/DashboardGestaoProduto/helper.js
Labels: bug

#1170 Fix: posicionamento do campo observação
  src/components/InclusaoDeAlimentacao/index.jsx
Labels: bug

#1171 Fix: não deve permitir adicionar a escola de destino igual a de origem
  src/components/screens/DietaEspecial/AlteracaoUE/components/FormCadastro/index.jsx
Labels: bug

#1172 Feature/52554 ajuste texto fluxo e laudo
  src/components/Shareable/FluxoDeStatus/index.jsx
  src/components/screens/DietaEspecial/CancelamentoDieta/components/ModalCancelamento/index.jsx
  src/components/screens/DietaEspecial/Escola/componentes/Laudo/index.jsx
Labels: feature

#1173 Hom - Atualizado até 15/12 as 14:00
  src/components/InclusaoDeAlimentacao/index.jsx
  src/components/Shareable/FluxoDeStatus/index.jsx
  src/components/screens/DietaEspecial/AlteracaoUE/components/FormCadastro/index.jsx
  src/components/screens/DietaEspecial/CancelamentoDieta/components/ModalCancelamento/index.jsx
  src/components/screens/DietaEspecial/Escola/componentes/Laudo/index.jsx
Labels: bug, feature

#1174 Fix: remover duplicação de componente
  src/components/InclusaoDeAlimentacao/index.jsx
Labels: bug

#1175 HOM - atualizado ate 15/12 15:10
  src/components/InclusaoDeAlimentacao/index.jsx
Labels: bug

#1178 Feature/53752 ver mais aguardando vigencia
  src/components/screens/DashBoardDietaEspecial/StatusSolicitacoes.jsx
  src/components/screens/DashBoardDietaEspecial/index.jsx
  src/configs/RoutesConfig.js
  src/configs/constants.js
  src/pages/DietaEspecial/StatusSolicitacoesPage.jsx
Labels: feature

#1177 HOM - Atualizado até 17/12 06:20
  src/components/screens/DashBoardDietaEspecial/StatusSolicitacoes.jsx
  src/components/screens/DashBoardDietaEspecial/index.jsx
  src/components/screens/Notificacoes/components/CardNotificacao/index.jsx
  src/components/screens/Notificacoes/components/CardNotificacao/style.scss
  src/components/screens/Notificacoes/components/Filtros/index.jsx
  src/configs/RoutesConfig.js
  src/configs/constants.js
  src/pages/DietaEspecial/StatusSolicitacoesPage.jsx
Labels: feature

#1183 Fix/54140-GA-quantidade-de-dietas-cadastradas-diferente-ao-cadastrar-kit-lanche
  src/components/SolicitacaoDeKitLanche/Container/base.jsx
  src/components/screens/DietaEspecial/AtivasInativasPorAluno/index.jsx
Labels: bug

#1184 Hom - Atualizado até 21/12 as 15:00
  src/components/SolicitacaoDeKitLanche/Container/base.jsx
  src/components/screens/DietaEspecial/AtivasInativasPorAluno/index.jsx
Labels: bug

#1185 Feature/55117-GA-retirar-acesso-ao-modulo-GA-das-escolas-tipo-gestao-mista-e-parceira
  src/components/Shareable/Sidebar/SidebarContent.jsx
  src/components/Shareable/Sidebar/menus/MenuGestaoDeAlimentacao.jsx
  src/components/screens/PainelInicial/index.jsx
  src/configs/RoutesConfig.js
  src/constants/shared.js
  src/helpers/utilities.js
  src/services/auth.js
Labels: feature

#1186 Hom - Atualizado até 23/12 as 12:50
  src/components/Shareable/Sidebar/SidebarContent.jsx
  src/components/Shareable/Sidebar/menus/MenuGestaoDeAlimentacao.jsx
  src/components/screens/PainelInicial/index.jsx
  src/configs/RoutesConfig.js
  src/constants/shared.js
  src/helpers/utilities.js
  src/services/auth.js
Labels: feature

#1193 Fix: adicionar opção de solicitação contínua nos cases de alteração d…
  src/services/alteracaoDeCardapio/helper.js
Labels: bug

#1196 Fix: adicionar validação de perfil para consultar lotes vinculados
  src/components/screens/DashboardTerceirizada/StatusSolicitacoes.jsx
Labels: bug

#1197 Hotfix/56177 ver mais pe d gpcodae
  src/components/screens/DashboardTerceirizada/StatusSolicitacoes.jsx
Labels: bug

#1198 Hotfix/56177 ver mais pe d gpcodae
  src/components/screens/DashboardTerceirizada/StatusSolicitacoes.jsx
Labels: bug

#1199 Feature/55805-PD-melhoria-na-visualizacao-da-ficha-de-produto
  src/components/Shareable/DetalheDoProduto/index.jsx
  src/components/Shareable/TabelaEspecificacoesProduto/index.jsx
  src/components/Shareable/TabelaEspecificacoesProduto/style.scss
  src/components/screens/Produto/Homologacao/index.jsx
  src/components/screens/Produto/RelatorioAnaliseSensorial/index.jsx
Labels: feature

#1201 Bugfix/55804 correcao validacoes
  src/components/Shareable/Select/index.jsx
  src/components/screens/Produto/AtualizacaoProdutoForm/components/WizardFormPrimeiraPagina.jsx
  src/components/screens/Produto/AtualizacaoProdutoForm/components/WizardFormTerceiraPagina.jsx
  src/components/screens/Produto/AtualizacaoProdutoForm/components/components/Especificacoes/index.jsx
Labels: bug

#1202 HOM - atualizado ate 29/12 09:50
  src/components/Shareable/Select/index.jsx
  src/components/screens/Produto/AtualizacaoProdutoForm/components/WizardFormPrimeiraPagina.jsx
  src/components/screens/Produto/AtualizacaoProdutoForm/components/WizardFormTerceiraPagina.jsx
  src/components/screens/Produto/AtualizacaoProdutoForm/components/components/Especificacoes/index.jsx
Labels: bug
