Repository prefeiturasp/SME-Terceirizadas-Frontend, pull requests merged in 2022-07, with the labels that each got.

#1521 Feature/64864 alteracao fluxo homologacao produto
  src/components/Shareable/TabelaEspecificacoesProduto/index.jsx
  src/components/screens/Produto/AtualizacaoProdutoForm/components/WizardFormTerceiraPagina.jsx
  src/components/screens/Produto/AtualizacaoProdutoForm/index.jsx
  src/components/screens/Produto/AvaliarReclamacaoProduto/components/TabelaProdutos/index.jsx
  src/components/screens/Produto/AvaliarReclamacaoProduto/helpers.js
  src/components/screens/Produto/BuscaProdutoSuspensos/index.jsx
  src/components/screens/Produto/Homologacao/index.jsx
  src/constants/shared.js
Labels: feature, refactoring

#1534 HOM - Atualizada 01/07 às 16:20
  src/components/Shareable/TabelaEspecificacoesProduto/index.jsx
  src/components/screens/Produto/AtualizacaoProdutoForm/components/WizardFormTerceiraPagina.jsx
  src/components/screens/Produto/AtualizacaoProdutoForm/index.jsx
  src/components/screens/Produto/AvaliarReclamacaoProduto/components/TabelaProdutos/index.jsx
  src/components/screens/Produto/AvaliarReclamacaoProduto/helpers.js
  src/components/screens/Produto/BuscaProdutoSuspensos/index.jsx
  src/components/screens/Produto/Homologacao/index.jsx
  src/constants/shared.js
Labels: feature, refactoring

#1540 Feature/66588-DE-incluir-classificação-dieta-ativa-tela-consulta-de-dieta-do-aluno
  src/components/screens/DietaEspecial/AtivasInativasPorAluno/components/TabelaResultados/index.jsx
Labels: feature

#1535 Feature/65706-DE-melhorias-na-tela-xlsx-pdf-relatório-de-dietas-especiais-terceirizada
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/components/Filtros/index.jsx
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/components/ListagemDietas/index.jsx
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/components/ListagemDietas/styles.scss
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/index.jsx
Labels: feature

#1542 Hom - Atualizado até 05/07/22 as 11:00
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/components/Filtros/index.jsx
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/components/ListagemDietas/index.jsx
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/components/ListagemDietas/styles.scss
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/index.jsx
Labels: feature

#1538 Feature/67462-GA-melhoria-ao-cadastrar-tipos-de-alimentacao
  src/components/screens/Cadastros/CadastroTipoAlimentacao/index.jsx
Labels: feature

#1543 Hom - Atualizado até 05/07/22 as 11:15
  src/components/screens/Cadastros/CadastroTipoAlimentacao/index.jsx
Labels: feature

#1546 Feature/67753-GA-alterar-termo-merenda-seca-para-lanche-emergencial
  src/components/AlteracaoDeCardapio/Relatorio/index.jsx
  src/components/AlteracaoDeCardapio/index.jsx
Labels: feature

#1547 Hom - Atualizado até 06/07/22 as 10:20
  src/components/AlteracaoDeCardapio/Relatorio/index.jsx
  src/components/AlteracaoDeCardapio/index.jsx
Labels: feature

#1576 Feature/67789 remover quantidade alunos para ceu gestao
  src/components/AlteracaoDeCardapio/Relatorio/index.jsx
  src/components/AlteracaoDeCardapio/index.jsx
  src/components/AlteracaoDeCardapio/validacao.js
  src/components/InclusaoDeAlimentacao/Escola/Formulario/componentes/InclusaoContinua/index.jsx
  src/components/InclusaoDeAlimentacao/Escola/Formulario/componentes/InclusaoNormal/index.jsx
  src/components/InclusaoDeAlimentacao/Escola/Formulario/index.jsx
  src/components/InclusaoDeAlimentacao/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/InclusaoDeAlimentacao/Relatorio/index.jsx
  src/components/InclusaoDeAlimentacao/helper.js
  src/components/InclusaoDeAlimentacao/validacao.js
  src/components/Shareable/CardMatriculados/index.jsx
  src/components/SolicitacaoDeKitLanche/Container/base.jsx
  src/components/SolicitacaoDeKitLanche/Relatorio/index.jsx
  src/components/SuspensaoDeAlimentacao/index.jsx
  src/components/SuspensaoDeAlimentacao/validacao.js
Labels: feature

#1577 Feature: ao clicar no link do card redirecionar para reclamação expan…
  src/components/screens/DashboardGestaoProduto/helper.js
  src/components/screens/Produto/Reclamacao/index.jsx
  src/helpers/gestaoDeProdutos.js
Labels: feature

#1578 Hom atualizado 15/07 as 12:20
  src/components/AlteracaoDeCardapio/Relatorio/index.jsx
  src/components/AlteracaoDeCardapio/index.jsx
  src/components/AlteracaoDeCardapio/validacao.js
  src/components/InclusaoDeAlimentacao/Escola/Formulario/componentes/InclusaoContinua/index.jsx
  src/components/InclusaoDeAlimentacao/Escola/Formulario/componentes/InclusaoNormal/index.jsx
  src/components/InclusaoDeAlimentacao/Escola/Formulario/index.jsx
  src/components/InclusaoDeAlimentacao/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/InclusaoDeAlimentacao/Relatorio/index.jsx
  src/components/InclusaoDeAlimentacao/helper.js
  src/components/InclusaoDeAlimentacao/validacao.js
  src/components/Shareable/CardMatriculados/index.jsx
  src/components/SolicitacaoDeKitLanche/Container/base.jsx
  src/components/SolicitacaoDeKitLanche/Relatorio/index.jsx
  src/components/SuspensaoDeAlimentacao/index.jsx
  src/components/SuspensaoDeAlimentacao/validacao.js
  src/components/screens/DashboardGestaoProduto/helper.js
  src/components/screens/Produto/Reclamacao/index.jsx
  src/helpers/gestaoDeProdutos.js
Labels: feature

#1583 Fix: links dos cards
  src/components/screens/DashboardGestaoProduto/helper.js
Labels: bug

#1585 fix: link
  src/components/screens/DashboardGestaoProduto/helper.js
Labels: bug

#1586 HOM - Atualizado até 19/07 às 17:50
  src/components/screens/DashboardGestaoProduto/helper.js
Labels: bug

#1597 Bugfix/69355 reposicao ocorrencia atraso entrega
  src/components/screens/Logistica/ReposicaoDeGuia/index.jsx
Labels: bug

#1611 Feature/69541 vincular produtos editais
  src/components/Shareable/Sidebar/SidebarContent.jsx
  src/components/Shareable/Sidebar/menus/MenuGestaoDeProduto.jsx
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/Filtros/index.jsx
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/ModalAtivarInativar/index.jsx
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/Tabela/helpers.js
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/Tabela/index.jsx
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/Tabela/style.scss
  src/components/screens/Cadastros/VincularProdutosEditais/index.jsx
  src/configs/RoutesConfig.js
  src/helpers/gestaoDeProdutos.js
  src/pages/Cadastros/VincularProdutosEditaisPage.jsx
  src/services/produto.service.js
Labels: feature

#1599 Feature/68883-PeD-técnica-otimização-telas-produtos
  src/components/Shareable/InputSearchPendencias/index.jsx
  src/components/Shareable/InputSearchPendencias/style.scss
  src/components/Shareable/Paginacao/style.scss
  src/components/screens/DashboardTerceirizada/StatusSolicitacoes.jsx
  src/services/produto.service.js
Labels: enhancement, feature

#1617 Hom - Atualizado até 28/07/22 as 13:50
  src/components/Shareable/InputSearchPendencias/index.jsx
  src/components/Shareable/InputSearchPendencias/style.scss
  src/components/Shareable/Paginacao/style.scss
  src/components/screens/DashboardTerceirizada/StatusSolicitacoes.jsx
  src/services/produto.service.js
Labels: enhancement, feature

#1622 Feature/68883-PeD-técnica-otimização-telas-produtos
  src/components/screens/DashboardTerceirizada/StatusSolicitacoes.jsx
Labels: enhancement, feature

#1623 Hom - Atualizado até 28/07/22 as 18:15
  src/components/screens/DashboardTerceirizada/StatusSolicitacoes.jsx
Labels: enhancement, feature

#1624 Fix: remover helper, filtrar opcoes do autocomplete, exibição da tabela
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/Filtros/index.jsx
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/Tabela/helpers.js
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/Tabela/index.jsx
  src/components/screens/Cadastros/VincularProdutosEditais/index.jsx
  src/pages/Cadastros/VincularProdutosEditaisPage.jsx
Labels: bug
