Repository prefeiturasp/SME-Terceirizadas-Frontend, pull requests merged in 2022-10, with the labels that each got.

#1833 Feature/74095-PeD-ajustar-botão-cancelar-à-direita
  src/components/screens/Produto/Homologacao/components/BotoesTerceirizada.jsx
Labels: enhancement, feature

#1834 Hom - Atualizado até 03/10/22 as 14:10
  src/components/screens/Produto/Homologacao/components/BotoesTerceirizada.jsx
Labels: feature

#1828 Feature/75028-PeD-melhoria-produtos-homologados-e-em-correção-para-dieta
  src/components/screens/Produto/AtualizacaoProdutoForm/components/WizardFormPrimeiraPagina.jsx
  src/configs/constants.js
Labels: enhancement, feature

#1839 Hom - Atualizado até 03/10/22 as 17:30
  src/components/screens/Produto/AtualizacaoProdutoForm/components/WizardFormPrimeiraPagina.jsx
  src/configs/constants.js
Labels: enhancement, feature

#1867 Feature/75586-GA-relatorio-escola-kit-lanche-passeio-CEMEI
  src/components/SolicitacaoDeKitLanche/components/SeletorAlunosDietaEspecial/style.scss
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/components/CorpoRelatorio/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/components/ModalKitLancheCEMEI/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/style.scss
  src/components/SolicitacaoKitLancheCEMEI/componentes/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/helpers.js
  src/components/SolicitacaoKitLancheCEMEI/index.jsx
  src/components/screens/helper.js
  src/configs/RoutesConfig.js
  src/configs/constants.js
  src/configs/helper.js
  src/constants/shared.js
  src/context/SolicitacaoAlimentacao/index.js
  src/index.jsx
  src/pages/SolicitacaoDeKitLancheCEMEI/RelatorioPage.jsx
  src/services/kitLanche/escola.service.js
Labels: enhancement, feature

#1869 Hom - Atualizado até 10/10/22 as 18:00
  src/components/SolicitacaoDeKitLanche/components/SeletorAlunosDietaEspecial/style.scss
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/components/CorpoRelatorio/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/components/ModalKitLancheCEMEI/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/style.scss
  src/components/SolicitacaoKitLancheCEMEI/componentes/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/helpers.js
  src/components/SolicitacaoKitLancheCEMEI/index.jsx
  src/components/screens/helper.js
  src/configs/RoutesConfig.js
  src/configs/constants.js
  src/configs/helper.js
  src/constants/shared.js
  src/context/SolicitacaoAlimentacao/index.js
  src/index.jsx
  src/pages/SolicitacaoDeKitLancheCEMEI/RelatorioPage.jsx
  src/services/kitLanche/escola.service.js
Labels: enhancement, feature

#1870 Feature/75586-GA-relatorio-escola-kit-lanche-passeio-CEMEI
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/components/CorpoRelatorio/index.jsx
  src/pages/SolicitacaoDeKitLancheCEMEI/RelatorioPage.jsx
Labels: enhancement, feature

#1882 Feature/75795-GA-relatorio-DRE-kit-lanche-passeio-CEMEI
  src/components/Shareable/ModalNaoValidarSolicitacao/index.jsx
  src/components/SolicitacaoDeKitLanche/DRE/PainelPedidos/index.jsx
  src/components/SolicitacaoDeKitLanche/components/CardPendenteAcao/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/components/CorpoRelatorio/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/components/ModalCancelarKitLancheCEMEI/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/components/ModalNaoValidarKitLancheCEMEI/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/index.jsx
  src/configs/helper.js
  src/helpers/corrigeDadosDoDashboard.js
  src/helpers/utilities.js
  src/pages/SolicitacaoDeKitLancheCEMEI/RelatorioPage.jsx
  src/services/constants.js
  src/services/kitLanche/escola.service.js
  src/services/kitLanche/helper.js
Labels: enhancement, feature

#1883 Hom - Atualizado até 13/10/22 as 15:55
  src/components/Shareable/ModalNaoValidarSolicitacao/index.jsx
  src/components/Shareable/ModalTercRespondeQuestFinalForm/index.jsx
  src/components/SolicitacaoDeKitLanche/DRE/PainelPedidos/index.jsx
  src/components/SolicitacaoDeKitLanche/components/CardPendenteAcao/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/components/CorpoRelatorio/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/components/ModalCancelarKitLancheCEMEI/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/components/ModalNaoValidarKitLancheCEMEI/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/helpers.js
  src/configs/helper.js
  src/helpers/corrigeDadosDoDashboard.js
  src/helpers/utilities.js
  src/pages/SolicitacaoDeKitLancheCEMEI/RelatorioPage.jsx
  src/services/constants.js
  src/services/kitLanche/escola.service.js
  src/services/kitLanche/helper.js
Labels: enhancement, feature

#1884 Feature/75561-GA-painel-solicitações--solicitação-inclusão-ETEC
  src/components/InclusaoDeAlimentacao/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/Shareable/ModalCancelarInclusaoAlimentacao/index.jsx
  src/components/screens/helper.js
Labels: enhancement, feature

#1887 Hom - Atualizado até 14/10/22 as 11:20
  src/components/InclusaoDeAlimentacao/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/Shareable/ModalCancelarInclusaoAlimentacao/index.jsx
  src/components/screens/helper.js
Labels: enhancement, feature

#1891 Feature/75801-kit-lanche-cemei-codae
  src/components/Shareable/ModalCODAEQuestiona/index.jsx
  src/components/Shareable/ModalNegarSolicitacao.jsx
  src/components/Shareable/ModalTercRespondeQuestFinalForm/index.jsx
  src/components/SolicitacaoDeKitLanche/CODAE/PainelPedidos/index.jsx
  src/components/SolicitacaoDeKitLanche/DRE/PainelPedidos/index.jsx
  src/components/SolicitacaoDeKitLanche/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/SolicitacaoDeKitLanche/Relatorio/componentes/style.scss
  src/components/SolicitacaoDeKitLanche/Relatorio/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/components/CorpoRelatorio/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/components/ModalCODAEQuestionaKitLancheCEMEI/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/components/ModalNegarKitLancheCEMEI/index.jsx
  src/configs/helper.js
  src/pages/SolicitacaoDeKitLanche/RelatorioPage.jsx
  src/pages/SolicitacaoDeKitLancheCEMEI/RelatorioPage.jsx
  src/services/kitLanche/codae.service.js
Labels: enhancement, feature

#1892 Hom - Atualizado até 14/10/22 as 20:20
  src/components/Shareable/ModalCODAEQuestiona/index.jsx
  src/components/Shareable/ModalNegarSolicitacao.jsx
  src/components/Shareable/ModalTercRespondeQuestFinalForm/index.jsx
  src/components/SolicitacaoDeKitLanche/CODAE/PainelPedidos/index.jsx
  src/components/SolicitacaoDeKitLanche/DRE/PainelPedidos/index.jsx
  src/components/SolicitacaoDeKitLanche/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/SolicitacaoDeKitLanche/Relatorio/componentes/style.scss
  src/components/SolicitacaoDeKitLanche/Relatorio/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/components/CorpoRelatorio/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/components/ModalCODAEQuestionaKitLancheCEMEI/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/components/ModalNegarKitLancheCEMEI/index.jsx
  src/configs/helper.js
  src/pages/SolicitacaoDeKitLanche/RelatorioPage.jsx
  src/pages/SolicitacaoDeKitLancheCEMEI/RelatorioPage.jsx
  src/services/kitLanche/codae.service.js
Labels: enhancement, feature

#1893 Feature/75039 relatorio produtos suspensos
  src/components/Shareable/Sidebar/menus/MenuRelatorios.jsx
  src/components/screens/Produto/BuscaProdutoSuspensos/components/ContadorResultado/index.jsx
  src/components/screens/Produto/BuscaProdutoSuspensos/components/ContadorResultado/styles.scss
  src/components/screens/Produto/BuscaProdutoSuspensos/components/FormBuscaProduto/index.js
  src/components/screens/Produto/BuscaProdutoSuspensos/components/ModalRelatorioProdutoSuspenso/helpers.js
  src/components/screens/Produto/BuscaProdutoSuspensos/components/ModalRelatorioProdutoSuspenso/index.jsx
  src/components/screens/Produto/BuscaProdutoSuspensos/components/TabelaResultado/index.jsx
  src/components/screens/Produto/BuscaProdutoSuspensos/index.jsx
  src/components/screens/Produto/BuscaProdutoSuspensos/styles.scss
  src/configs/RoutesConfig.js
Labels: feature

#1896 Fix: margem quando não houver resultados
  src/components/screens/Produto/BuscaProdutoSuspensos/index.jsx
Labels: bug

#1897 Hom atualizado 17/10 as 12h27
  src/components/screens/Produto/BuscaProdutoSuspensos/index.jsx
Labels: bug

#1898 Fix: usar POST ao invés de GET
  src/components/screens/Produto/BuscaProdutoSuspensos/components/TabelaResultado/index.jsx
  src/components/screens/Produto/BuscaProdutoSuspensos/index.jsx
  src/services/produto.service.js
Labels: bug

#1900 Hom atualizado 17/10 as 17h50
  src/components/screens/Produto/BuscaProdutoSuspensos/components/TabelaResultado/index.jsx
  src/components/screens/Produto/BuscaProdutoSuspensos/index.jsx
  src/services/produto.service.js
Labels: bug

#1901 Fix: corrigir problemas com anexos e paginação da tela
  src/components/screens/Produto/BuscaProdutoSuspensos/components/TabelaResultado/index.jsx
  src/components/screens/Produto/BuscaProdutoSuspensos/index.jsx
  src/services/produto.service.js
Labels: bug

#1902 Hom atualizado 18/10 as 13h45
  src/components/screens/Produto/BuscaProdutoSuspensos/components/TabelaResultado/index.jsx
  src/components/screens/Produto/BuscaProdutoSuspensos/index.jsx
  src/services/produto.service.js
Labels: bug

#1903 Fix: opções dos editais para filtros
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/Filtros/index.jsx
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/ModalVincularProdutosEditais/index.jsx
Labels: bug

#1908 Hom - Atualizado até 19/10/22 as 12:20
  src/components/AlteracaoDeCardapio/CODAE/PainelPedidos/index.jsx
  src/components/AlteracaoDeCardapio/DRE/PainelPedidos/index.jsx
  src/components/InclusaoDeAlimentacao/CODAE/PainelPedidos/index.jsx
  src/components/InclusaoDeAlimentacao/DRE/PainelPedidos/index.jsx
  src/components/InversaoDeDiaDeCardapio/CODAE/PainelPedidos/index.jsx
  src/components/InversaoDeDiaDeCardapio/DRE/PainelPedidos/index.jsx
  src/components/SolicitacaoDeKitLanche/CODAE/PainelPedidos/index.jsx
  src/components/SolicitacaoDeKitLanche/DRE/PainelPedidos/index.jsx
  src/components/SolicitacaoUnificada/CODAE/PainelPedidos/index.jsx
  src/helpers/painelPedidos.js
Labels: enhancement, feature

#1894 Feature: liberar modulo GA para nutrissupervisão e nutrimanifestação
  src/helpers/utilities.js
Labels: feature

#1912 Hom atualizado 20/10 as 10h40
  src/helpers/utilities.js
Labels: feature

#1915 Feature/76370-problema-componente-de-texto-draft-js
  package-lock.json
  package.json
  src/components/AlteracaoDeCardapio/CEI/AlteracaoCardapio.jsx
  src/components/AlteracaoDeCardapio/index.jsx
  src/components/AlteracaoDeCardapioCEMEI/index.jsx
  src/components/InclusaoDeAlimentacao/Escola/Formulario/componentes/InclusaoContinua/index.jsx
  src/components/InclusaoDeAlimentacao/Escola/Formulario/componentes/InclusaoNormal/index.jsx
  src/components/InversaoDeDiaDeCardapio/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/InversaoDeDiaDeCardapio/Relatorio/index.jsx
  src/components/InversaoDeDiaDeCardapio/index.jsx
  src/components/Shareable/CKEditorField/index.jsx
  src/components/Shareable/Input/InputErroMensagemCKEditor/index.jsx
  src/components/Shareable/Input/InputErroMensagemCKEditor/style.scss
  src/components/Shareable/ModalCODAEAutoriza/index.jsx
  src/components/Shareable/ModalCODAEQuestiona/index.jsx
  src/components/Shareable/ModalCodaeCancelaAnaliseSensorial/index.jsx
  src/components/Shareable/ModalHistorico/index.jsx
  src/components/Shareable/ModalNegarSolicitacao.jsx
  src/components/Shareable/ModalPadrao/index.jsx
  src/components/Shareable/TextArea/TextAreaWYSIWYG/OpcoesCustomizadas.jsx
  src/components/Shareable/TextArea/TextAreaWYSIWYG/__tests__/teste_TextAreaWYSIWYG.js
  src/components/Shareable/TextArea/TextAreaWYSIWYG/index.jsx
  src/components/Shareable/TextArea/TextAreaWYSIWYG/style.scss
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/components/ModalCODAEQuestionaKitLancheCEMEI/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/components/ModalNegarKitLancheCEMEI/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/index.jsx
  src/components/SolicitacaoUnificada/helper.js
  src/components/SolicitacaoUnificada/index.jsx
  src/components/SuspensaoDeAlimentacao/index.jsx
  src/components/screens/Cadastros/FaixasEtarias/ModalJustificativa.jsx
  src/components/screens/Configuracoes/Mensagem.jsx
  src/components/screens/DietaEspecial/AlteracaoUE/components/FormCadastro/index.jsx
  src/components/screens/DietaEspecial/CancelamentoDieta/components/ModalCancelamento/index.jsx
  src/components/screens/DietaEspecial/Escola/componentes/Laudo/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/ModalCancelaDietaEspecial/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/ModalNegaDietaEspecial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalObservacaoDiaria/index.jsx
  src/components/screens/Produto/AtivacaoSuspensao/ModalAtivacaoSuspensaoProduto/index.jsx
  src/components/screens/Produto/AvaliarReclamacaoProduto/components/Modal/index.jsx
  src/components/screens/Produto/AvaliarSolicitacaoCadastroProduto/components/FormPrevisaoCadastro/index.jsx
  src/components/screens/Produto/Homologacao/components/ModalCancelarHomologacaoProduto/index.jsx
  src/components/screens/Produto/Reclamacao/components/ModalReclamacaoProduto/index.jsx
  src/components/screens/Produto/ResponderReclamacao/ModalResponderReclamacao/index.jsx
  src/helpers/fieldValidators.js
Labels: enhancement, feature

#1920 Hom - Atualizado até 21/10/22 as 12:55
  package-lock.json
  package.json
  src/components/AlteracaoDeCardapio/CEI/AlteracaoCardapio.jsx
  src/components/AlteracaoDeCardapio/index.jsx
  src/components/AlteracaoDeCardapioCEMEI/index.jsx
  src/components/InclusaoDeAlimentacao/Escola/Formulario/componentes/InclusaoContinua/index.jsx
  src/components/InclusaoDeAlimentacao/Escola/Formulario/componentes/InclusaoNormal/index.jsx
  src/components/InversaoDeDiaDeCardapio/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/InversaoDeDiaDeCardapio/Relatorio/index.jsx
  src/components/InversaoDeDiaDeCardapio/index.jsx
  src/components/Shareable/CKEditorField/index.jsx
  src/components/Shareable/Input/InputErroMensagemCKEditor/index.jsx
  src/components/Shareable/Input/InputErroMensagemCKEditor/style.scss
  src/components/Shareable/ModalCODAEAutoriza/index.jsx
  src/components/Shareable/ModalCODAEQuestiona/index.jsx
  src/components/Shareable/ModalCodaeCancelaAnaliseSensorial/index.jsx
  src/components/Shareable/ModalHistorico/index.jsx
  src/components/Shareable/ModalNegarSolicitacao.jsx
  src/components/Shareable/ModalPadrao/index.jsx
  src/components/Shareable/TextArea/TextAreaWYSIWYG/OpcoesCustomizadas.jsx
  src/components/Shareable/TextArea/TextAreaWYSIWYG/__tests__/teste_TextAreaWYSIWYG.js
  src/components/Shareable/TextArea/TextAreaWYSIWYG/index.jsx
  src/components/Shareable/TextArea/TextAreaWYSIWYG/style.scss
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/components/ModalCODAEQuestionaKitLancheCEMEI/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/components/ModalNegarKitLancheCEMEI/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/index.jsx
  src/components/SolicitacaoUnificada/helper.js
  src/components/SolicitacaoUnificada/index.jsx
  src/components/SuspensaoDeAlimentacao/index.jsx
  src/components/screens/Cadastros/FaixasEtarias/ModalJustificativa.jsx
  src/components/screens/Configuracoes/Mensagem.jsx
  src/components/screens/DietaEspecial/AlteracaoUE/components/FormCadastro/index.jsx
  src/components/screens/DietaEspecial/CancelamentoDieta/components/ModalCancelamento/index.jsx
  src/components/screens/DietaEspecial/Escola/componentes/Laudo/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/ModalCancelaDietaEspecial/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/ModalNegaDietaEspecial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalObservacaoDiaria/index.jsx
  src/components/screens/Produto/AtivacaoSuspensao/ModalAtivacaoSuspensaoProduto/index.jsx
  src/components/screens/Produto/AvaliarReclamacaoProduto/components/Modal/index.jsx
  src/components/screens/Produto/AvaliarSolicitacaoCadastroProduto/components/FormPrevisaoCadastro/index.jsx
  src/components/screens/Produto/Homologacao/components/ModalCancelarHomologacaoProduto/index.jsx
  src/components/screens/Produto/Reclamacao/components/ModalReclamacaoProduto/index.jsx
  src/components/screens/Produto/ResponderReclamacao/ModalResponderReclamacao/index.jsx
  src/helpers/fieldValidators.js
Labels: enhancement, feature

#1917 Feature: 1 alteração de alimentação RPL para o mesmo mes e período
  src/components/AlteracaoDeCardapio/CEI/AlteracaoCardapio.jsx
  src/components/AlteracaoDeCardapio/index.jsx
  src/components/AlteracaoDeCardapioCEMEI/componentes/TabelaFaixasCEMEI.jsx
  src/components/AlteracaoDeCardapioCEMEI/index.jsx
  src/components/AlteracaoDeCardapioCEMEI/style.scss
  src/services/alteracaoDeCardapio/escola.service.js
Labels: feature

#1925 Hom atualizado 24/10 as 10h50
  src/components/AlteracaoDeCardapio/CEI/AlteracaoCardapio.jsx
  src/components/AlteracaoDeCardapio/index.jsx
  src/components/AlteracaoDeCardapioCEMEI/componentes/TabelaFaixasCEMEI.jsx
  src/components/AlteracaoDeCardapioCEMEI/index.jsx
  src/components/AlteracaoDeCardapioCEMEI/style.scss
  src/services/alteracaoDeCardapio/escola.service.js
Labels: feature

#1926 Feature/76462-PeD-tela-vincular-produtos-editais-incluir-campo-tipo-produto-edital-origem
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/ModalAtivarInativar/index.jsx
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/ModalVincularProdutosEditais/helper.js
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/ModalVincularProdutosEditais/index.jsx
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/Tabela/index.jsx
Labels: enhancement, feature

#1928 Hom - Atualizado até 25/10/22 as 11:50
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/ModalAtivarInativar/index.jsx
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/ModalVincularProdutosEditais/helper.js
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/ModalVincularProdutosEditais/index.jsx
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/Tabela/index.jsx
Labels: enhancement, feature

#1931 Feature/76462-PeD-tela-vincular-produtos-editais-incluir-campo-tipo-produto-edital-origem
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/ModalVincularProdutosEditais/index.jsx
Labels: enhancement, feature

#1962 Feature/76797--tela-gerenciamento-de-email-busca-edicão-exclusão
  src/components/screens/Configuracoes/GerenciamentoEmails/FiltrosEmails/index.jsx
  src/components/screens/Configuracoes/GerenciamentoEmails/GerenciamentoEmails.jsx
  src/components/screens/Configuracoes/GerenciamentoEmails/ListagemSolicitacoes/index.js
  src/components/screens/Configuracoes/GerenciamentoEmails/ListagemSolicitacoes/styles.scss
  src/components/screens/Configuracoes/GerenciamentoEmails/ModalEditarEmail/index.jsx
  src/components/screens/Configuracoes/GerenciamentoEmails/ModalExcluirEmail/index.jsx
  src/services/terceirizada.service.js
Labels: enhancement, feature

#1966 Hom - Atualizado até 28/10/22 as 12:45
  src/components/screens/Configuracoes/GerenciamentoEmails/FiltrosEmails/index.jsx
  src/components/screens/Configuracoes/GerenciamentoEmails/GerenciamentoEmails.jsx
  src/components/screens/Configuracoes/GerenciamentoEmails/ListagemSolicitacoes/index.js
  src/components/screens/Configuracoes/GerenciamentoEmails/ListagemSolicitacoes/styles.scss
  src/components/screens/Configuracoes/GerenciamentoEmails/ModalEditarEmail/index.jsx
  src/components/screens/Configuracoes/GerenciamentoEmails/ModalExcluirEmail/index.jsx
  src/services/terceirizada.service.js
Labels: enhancement, feature

#1968 Feature/76797--tela-gerenciamento-de-email-busca-edicão-exclusão
  src/components/screens/Configuracoes/GerenciamentoEmails/FiltrosEmails/index.jsx
  src/components/screens/Configuracoes/GerenciamentoEmails/ListagemSolicitacoes/styles.scss
  src/components/screens/Configuracoes/GerenciamentoEmails/ModalEditarEmail/index.jsx
Labels: enhancement, feature

#1969 Hom - Atualizado até 28/10/22 as 16:05
  src/components/screens/Configuracoes/GerenciamentoEmails/FiltrosEmails/index.jsx
  src/components/screens/Configuracoes/GerenciamentoEmails/ListagemSolicitacoes/styles.scss
  src/components/screens/Configuracoes/GerenciamentoEmails/ModalEditarEmail/index.jsx
Labels: enhancement, feature

#1970 Feature/77978-DE-alterar-descrição-do-texto-de-laudo-na-solicitação-de-dieta-especial
  src/components/screens/DietaEspecial/Escola/componentes/Laudo/index.jsx
Labels: enhancement, feature
