Repository prefeiturasp/SME-Terceirizadas-Frontend, pull requests merged in 2022-02, with the labels that each got.

#1248 Feature/56262 copia protocolo padrao
  src/components/screens/DietaEspecial/CadastroProtocoloPadraoDietaEsp/componentes/ModalCancelaCopia/index.jsx
  src/components/screens/DietaEspecial/CadastroProtocoloPadraoDietaEsp/index.jsx
  src/components/screens/DietaEspecial/ConsultaProtocoloPadraoDieta/componentes/DetalhesProtocolo/index.jsx
  src/configs/RoutesConfig.js
  src/pages/DietaEspecial/CriarCopiaProtocoloPadraoDieta.jsx
Labels: feature

#1249 Bugfix/55955 pe d anexos e reload
  src/components/Shareable/Input/InputFile/AnexosProdutoField.jsx
  src/components/Shareable/Input/InputFile/style.scss
  src/components/screens/Produto/Cadastro/Step3/index.jsx
  src/components/screens/Produto/Cadastro/index.jsx
Labels: bug

#1250 Hom - Atualizado até 01/02/22 as 03:30
  src/components/Shareable/Input/InputFile/AnexosProdutoField.jsx
  src/components/Shareable/Input/InputFile/style.scss
  src/components/screens/DietaEspecial/CadastroProtocoloPadraoDietaEsp/componentes/ModalCancelaCopia/index.jsx
  src/components/screens/DietaEspecial/CadastroProtocoloPadraoDietaEsp/index.jsx
  src/components/screens/DietaEspecial/ConsultaProtocoloPadraoDieta/componentes/DetalhesProtocolo/index.jsx
  src/components/screens/Produto/Cadastro/Step3/index.jsx
  src/components/screens/Produto/Cadastro/index.jsx
  src/configs/RoutesConfig.js
  src/pages/DietaEspecial/CriarCopiaProtocoloPadraoDieta.jsx
Labels: bug, feature

#1251 Feature/53994-PD-criar-cards-de-responder-questionamentos-da-codae
  src/components/Shareable/CardStatusDeSolicitacao/CardStatusDeSolicitacao.jsx
  src/components/Shareable/Sidebar/menus/MenuGestaoDeProduto.jsx
  src/components/screens/DashboardGestaoProduto/helper.js
  src/components/screens/DashboardGestaoProduto/index.jsx
  src/components/screens/DashboardTerceirizada/StatusSolicitacoes.jsx
  src/components/screens/Produto/ResponderQuestionamentoNutrisupervisor/components/Filtros/index.jsx
  src/components/screens/Produto/ResponderQuestionamentoNutrisupervisor/components/TabelaProdutos/index.jsx
  src/components/screens/Produto/ResponderQuestionamentoNutrisupervisor/index.jsx
  src/components/screens/Produto/ResponderQuestionamentoUE/components/Filtros/index.jsx
  src/components/screens/Produto/ResponderQuestionamentoUE/components/TabelaProdutos/index.jsx
  src/components/screens/Produto/ResponderQuestionamentoUE/index.jsx
  src/configs/RoutesConfig.js
  src/configs/constants.js
  src/helpers/gestaoDeProdutos.js
  src/pages/Produto/StatusSolicitacoesGestaoProduto.jsx
Labels: feature

#1252 Hom - Atualizado até 01/02/22 as 08:30
  src/components/Shareable/CardStatusDeSolicitacao/CardStatusDeSolicitacao.jsx
  src/components/Shareable/Sidebar/menus/MenuGestaoDeProduto.jsx
  src/components/screens/DashboardGestaoProduto/helper.js
  src/components/screens/DashboardGestaoProduto/index.jsx
  src/components/screens/DashboardTerceirizada/StatusSolicitacoes.jsx
  src/components/screens/Produto/ResponderQuestionamentoNutrisupervisor/components/Filtros/index.jsx
  src/components/screens/Produto/ResponderQuestionamentoNutrisupervisor/components/TabelaProdutos/index.jsx
  src/components/screens/Produto/ResponderQuestionamentoNutrisupervisor/index.jsx
  src/components/screens/Produto/ResponderQuestionamentoUE/components/Filtros/index.jsx
  src/components/screens/Produto/ResponderQuestionamentoUE/components/TabelaProdutos/index.jsx
  src/components/screens/Produto/ResponderQuestionamentoUE/index.jsx
  src/configs/RoutesConfig.js
  src/configs/constants.js
  src/helpers/gestaoDeProdutos.js
  src/pages/Produto/StatusSolicitacoesGestaoProduto.jsx
Labels: feature

#1253 Feature/53994-PD-ajustar-títulos-das-telas-e-modais-responder-questionamento-da-codae
  src/components/screens/Produto/AvaliarReclamacaoProduto/components/TabelaProdutos/index.jsx
  src/components/screens/Produto/ResponderQuestionamentoNutrisupervisor/components/TabelaProdutos/index.jsx
  src/components/screens/Produto/ResponderQuestionamentoUE/components/TabelaProdutos/index.jsx
  src/components/screens/Produto/ResponderReclamacao/ModalResponderReclamacao/index.jsx
  src/pages/Produto/index.js
Labels: feature

#1254 Hom - Atualizado até 02/02/22 as 11:20
  src/components/screens/Produto/AvaliarReclamacaoProduto/components/TabelaProdutos/index.jsx
  src/components/screens/Produto/ResponderQuestionamentoNutrisupervisor/components/TabelaProdutos/index.jsx
  src/components/screens/Produto/ResponderQuestionamentoUE/components/TabelaProdutos/index.jsx
  src/components/screens/Produto/ResponderReclamacao/ModalResponderReclamacao/index.jsx
  src/pages/Produto/index.js
Labels: feature

#1255 Feature/53994-PD-ajustar-título-do-modal-de-avaliar-reclamação-de-produto
  src/components/screens/Produto/AvaliarReclamacaoProduto/components/TabelaProdutos/index.jsx
Labels: feature

#1256 Hom - Atualizado até 02/02/22 as 12:20
  src/components/screens/Produto/AvaliarReclamacaoProduto/components/TabelaProdutos/index.jsx
Labels: feature

#1257 Prod - Atualizado até 03/02/2022 as 03:40
  src/components/Shareable/CardStatusDeSolicitacao/CardStatusDeSolicitacao.jsx
  src/components/Shareable/Input/InputFile/AnexosProdutoField.jsx
  src/components/Shareable/Input/InputFile/style.scss
  src/components/Shareable/Sidebar/menus/MenuGestaoDeProduto.jsx
  src/components/screens/DashboardGestaoProduto/helper.js
  src/components/screens/DashboardGestaoProduto/index.jsx
  src/components/screens/DashboardTerceirizada/StatusSolicitacoes.jsx
  src/components/screens/DietaEspecial/CadastroProtocoloPadraoDietaEsp/componentes/ModalCancelaCopia/index.jsx
  src/components/screens/DietaEspecial/CadastroProtocoloPadraoDietaEsp/index.jsx
  src/components/screens/DietaEspecial/ConsultaProtocoloPadraoDieta/componentes/DetalhesProtocolo/index.jsx
  src/components/screens/Logistica/GestaoRequisicaoEntrega/components/Filtros/index.jsx
  src/components/screens/Logistica/GestaoRequisicaoEntrega/components/ListagemGuias/index.jsx
  src/components/screens/Logistica/GestaoRequisicaoEntrega/components/ListagemGuias/styles.scss
  src/components/screens/Logistica/GestaoRequisicaoEntrega/components/ListagemSolicitacoes/index.js
  src/components/screens/Logistica/GestaoRequisicaoEntrega/components/ListagemSolicitacoes/styles.scss
  src/components/screens/Logistica/GestaoRequisicaoEntrega/index.js
  src/components/screens/Produto/Cadastro/Step3/index.jsx
  src/components/screens/Produto/Cadastro/index.jsx
  src/components/screens/Produto/ResponderQuestionamentoNutrisupervisor/components/Filtros/index.jsx
  src/components/screens/Produto/ResponderQuestionamentoNutrisupervisor/components/TabelaProdutos/index.jsx
  src/components/screens/Produto/ResponderQuestionamentoNutrisupervisor/index.jsx
  src/components/screens/Produto/ResponderQuestionamentoUE/components/Filtros/index.jsx
  src/components/screens/Produto/ResponderQuestionamentoUE/components/TabelaProdutos/index.jsx
  src/components/screens/Produto/ResponderQuestionamentoUE/index.jsx
  src/components/screens/Produto/ResponderReclamacao/ModalResponderReclamacao/index.jsx
  src/configs/RoutesConfig.js
  src/configs/constants.js
  src/helpers/gestaoDeProdutos.js
  src/pages/DietaEspecial/CriarCopiaProtocoloPadraoDieta.jsx
  src/pages/Produto/StatusSolicitacoesGestaoProduto.jsx
  src/pages/Produto/index.js
  src/services/logistica.service.js
Labels: bug, feature

#1258 Fix: props para corrigir problema de invalid data
  src/components/screens/DietaEspecial/Escola/index.jsx
Labels: bug

#1259 Hom - Atualizado até 03/02/22 as 04:10
  src/components/screens/DietaEspecial/Escola/index.jsx
Labels: bug

#1260 Fix: correção ao definir nome da escola para aluno não matriculado
  src/components/screens/DietaEspecial/Escola/index.jsx
Labels: bug

#1261 Hom - Atualizado até 03/02/22 as 11:55
  src/components/screens/DietaEspecial/Escola/index.jsx
Labels: bug

#1262 Feature/56234-PD-alteração-na-tela-de-cadastro-do-produto-retirar-campo-de-protocolo
  src/components/screens/Produto/AtualizacaoProdutoForm/components/WizardFormPrimeiraPagina.jsx
  src/components/screens/Produto/AtualizacaoProdutoForm/index.jsx
  src/components/screens/Produto/BuscaProdutoAnaliseSensorial/components/DetalheProduto.jsx
  src/components/screens/Produto/Cadastro/Step1/index.jsx
  src/components/screens/Produto/Cadastro/helpers.js
  src/components/screens/Produto/Cadastro/index.jsx
  src/components/screens/Produto/Homologacao/index.jsx
  src/components/screens/Produto/RelatorioAnaliseSensorial/index.jsx
  src/reducers/produto.reducer.js
Labels: feature

#1263 Hom - Atualizado até 03/02/22 as 18:10
  src/components/screens/Produto/AtualizacaoProdutoForm/components/WizardFormPrimeiraPagina.jsx
  src/components/screens/Produto/AtualizacaoProdutoForm/index.jsx
  src/components/screens/Produto/BuscaProdutoAnaliseSensorial/components/DetalheProduto.jsx
  src/components/screens/Produto/Cadastro/Step1/index.jsx
  src/components/screens/Produto/Cadastro/helpers.js
  src/components/screens/Produto/Cadastro/index.jsx
  src/components/screens/Produto/Homologacao/index.jsx
  src/components/screens/Produto/RelatorioAnaliseSensorial/index.jsx
  src/reducers/produto.reducer.js
Labels: feature

#1266 Feature: desabilitar edição dos campos 'nome' e 'produto é para dieta especial'
  src/components/screens/Produto/AtualizacaoProdutoForm/components/WizardFormPrimeiraPagina.jsx
Labels: feature

#1272 Feature/56243-PeD-melhorias-dashboard-ver-mais
  src/components/Shareable/CardListarSolicitacoes/index.jsx
  src/components/Shareable/CardListarSolicitacoes/style.scss
  src/components/screens/DashboardTerceirizada/StatusSolicitacoes.jsx
  src/services/produto.service.js
Labels: feature

#1273 Hom - Atualizado até 09/02/22 as 18:30
  src/components/Shareable/CardListarSolicitacoes/index.jsx
  src/components/Shareable/CardListarSolicitacoes/style.scss
  src/components/screens/DashboardTerceirizada/StatusSolicitacoes.jsx
  src/services/produto.service.js
Labels: feature

#1275 Feature/56243-PeD-melhorias-dashboard-ver-mais
  src/components/screens/DashboardTerceirizada/StatusSolicitacoes.jsx
Labels: feature

#1276 Hom - Atualizado até 10/02/22 as 19:15
  src/components/screens/DashboardTerceirizada/StatusSolicitacoes.jsx
Labels: feature

#1280 Feature/57884-DE-criar-permissionamento-nutricionista-manifestação
  src/components/Shareable/Sidebar/SidebarContent.jsx
  src/components/Shareable/Sidebar/menus/MenuDietaEspecial.jsx
  src/components/screens/PainelInicial/index.jsx
  src/configs/RoutesConfig.js
  src/configs/helper.js
  src/constants/shared.js
  src/helpers/utilities.js
Labels: feature

#1281 Hom - Atualizado até 15/02/22 as 19:45
  src/components/Shareable/Sidebar/SidebarContent.jsx
  src/components/Shareable/Sidebar/menus/MenuDietaEspecial.jsx
  src/components/screens/PainelInicial/index.jsx
  src/configs/RoutesConfig.js
  src/configs/helper.js
  src/constants/shared.js
  src/helpers/utilities.js
Labels: feature

#1282 Feature/57884-DE-criar-permissionamento-nutricionista-manifestação
  src/components/screens/DietaEspecial/Relatorio/index.jsx
  src/configs/helper.js
Labels: feature

#1283 Hom - Atualizado até 16/02/22 as 19:25
  src/components/screens/DietaEspecial/Relatorio/index.jsx
  src/configs/helper.js
Labels: feature

#1287 Prod - Atualizado até 21/02/2022 as 19:40
  src/components/Shareable/CardListarSolicitacoes/index.jsx
  src/components/Shareable/CardListarSolicitacoes/style.scss
  src/components/Shareable/ModalNaoValidarSolicitacao/index.jsx
  src/components/Shareable/Sidebar/SidebarContent.jsx
  src/components/Shareable/Sidebar/menus/MenuDietaEspecial.jsx
  src/components/SolicitacaoDeKitLanche/Container/base.jsx
  src/components/screens/DashboardEscola/style.scss
  src/components/screens/DashboardNutricionista/style.scss
  src/components/screens/DashboardTerceirizada/StatusSolicitacoes.jsx
  src/components/screens/DietaEspecial/Relatorio/index.jsx
  src/components/screens/PainelInicial/index.jsx
  src/components/screens/Produto/AtualizacaoProdutoForm/components/WizardFormPrimeiraPagina.jsx
  src/configs/RoutesConfig.js
  src/configs/helper.js
  src/constants/shared.js
  src/helpers/utilities.js
  src/services/produto.service.js
Labels: feature

#1288 Feature/57885-GA-criar-permissionamento-nutricionista-manifestação
  src/components/Shareable/Sidebar/SidebarContent.jsx
  src/components/Shareable/Sidebar/menus/MenuGestaoDeAlimentacao.jsx
  src/components/screens/DashboardNutricionista/DashboardNutriManifestacao.jsx
  src/components/screens/DashboardNutricionista/DashboardNutriManifestacaoContainer.jsx
  src/components/screens/DashboardNutricionista/StatusSolicitacoesNutriManifestacao.jsx
  src/components/screens/PainelInicial/index.jsx
  src/configs/RoutesConfig.js
  src/configs/constants.js
  src/configs/helper.js
  src/pages/Nutricionista/DashboardNutriManifestacaoPage.jsx
  src/pages/Nutricionista/Solicitacoes/StatusSolicitacoesAutorizadasNutriManifestacaoPage.jsx
  src/pages/Nutricionista/Solicitacoes/StatusSolicitacoesCanceladasNutriManifestacaoPage.jsx
  src/pages/Nutricionista/Solicitacoes/StatusSolicitacoesRecusadasNutriManifestacaoPage.jsx
  src/services/painelNutricionista.service.js
Labels: feature

#1289 Hom - Atualizado até 22/02/22 as 13:30
  src/components/Shareable/Sidebar/SidebarContent.jsx
  src/components/Shareable/Sidebar/menus/MenuGestaoDeAlimentacao.jsx
  src/components/screens/DashboardNutricionista/DashboardNutriManifestacao.jsx
  src/components/screens/DashboardNutricionista/DashboardNutriManifestacaoContainer.jsx
  src/components/screens/DashboardNutricionista/StatusSolicitacoesNutriManifestacao.jsx
  src/components/screens/PainelInicial/index.jsx
  src/configs/RoutesConfig.js
  src/configs/constants.js
  src/configs/helper.js
  src/pages/Nutricionista/DashboardNutriManifestacaoPage.jsx
  src/pages/Nutricionista/Solicitacoes/StatusSolicitacoesAutorizadasNutriManifestacaoPage.jsx
  src/pages/Nutricionista/Solicitacoes/StatusSolicitacoesCanceladasNutriManifestacaoPage.jsx
  src/pages/Nutricionista/Solicitacoes/StatusSolicitacoesRecusadasNutriManifestacaoPage.jsx
  src/services/painelNutricionista.service.js
Labels: feature

#1290 Feature/57883-PD-criar-permissionamento-nutricionista-manifestação
  src/components/Shareable/Sidebar/SidebarContent.jsx
  src/components/screens/PainelInicial/index.jsx
  src/configs/RoutesConfig.js
Labels: feature

#1291 Hom - Atualizado até 22/02/22 as 16:10
  src/components/Shareable/Sidebar/SidebarContent.jsx
  src/components/screens/PainelInicial/index.jsx
  src/configs/RoutesConfig.js
Labels: feature

#1292 Prod - Atualizado até 22/02/2022 as 17:50
  src/components/Shareable/Sidebar/SidebarContent.jsx
  src/components/Shareable/Sidebar/menus/MenuGestaoDeAlimentacao.jsx
  src/components/screens/DashboardNutricionista/DashboardNutriManifestacao.jsx
  src/components/screens/DashboardNutricionista/DashboardNutriManifestacaoContainer.jsx
  src/components/screens/DashboardNutricionista/StatusSolicitacoesNutriManifestacao.jsx
  src/components/screens/PainelInicial/index.jsx
  src/configs/RoutesConfig.js
  src/configs/constants.js
  src/configs/helper.js
  src/pages/Nutricionista/DashboardNutriManifestacaoPage.jsx
  src/pages/Nutricionista/Solicitacoes/StatusSolicitacoesAutorizadasNutriManifestacaoPage.jsx
  src/pages/Nutricionista/Solicitacoes/StatusSolicitacoesCanceladasNutriManifestacaoPage.jsx
  src/pages/Nutricionista/Solicitacoes/StatusSolicitacoesRecusadasNutriManifestacaoPage.jsx
  src/services/painelNutricionista.service.js
Labels: feature
