Repository prefeiturasp/SME-Terceirizadas-Frontend, pull requests merged in 2022-09, with the labels that each got.

#1709 Feature/70695-MI-tela-de-lancamento-de-alimentacao-pt1
  src/components/Shareable/TextArea/TextAreaWYSIWYG/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalObservacaoDiaria/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalObservacaoDiaria/styles.scss
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalSalvarLancamento/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/styles.scss
  src/configs/RoutesConfig.js
  src/configs/constants.js
  src/pages/LancamentoMedicaoInicial/LancamentoMedicaoInicialPage.jsx
  src/pages/LancamentoMedicaoInicial/PeriodoLancamentoMedicaoInicialPage.jsx
  src/services/medicaoInicial/periodoLancamentoMedicao.service.js
Labels: enhancement, feature

#1710 Hom - Atualizado até 31/08/22 as 22:50
  src/components/Shareable/TextArea/TextAreaWYSIWYG/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalObservacaoDiaria/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalObservacaoDiaria/styles.scss
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalSalvarLancamento/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/styles.scss
  src/configs/RoutesConfig.js
  src/configs/constants.js
  src/pages/LancamentoMedicaoInicial/LancamentoMedicaoInicialPage.jsx
  src/pages/LancamentoMedicaoInicial/PeriodoLancamentoMedicaoInicialPage.jsx
  src/services/medicaoInicial/periodoLancamentoMedicao.service.js
Labels: enhancement, feature

#1712 Hom - Atualizado até 01/09/22 as 12:20
  src/components/SuspensaoAlimentacaoDeCEI/Relatorio/components/CorpoRelatorio/index.jsx
  src/components/SuspensaoAlimentacaoDeCEI/Relatorio/components/ModalCancelaSuspensao/index.jsx
  src/components/SuspensaoAlimentacaoDeCEI/Relatorio/index.jsx
  src/components/SuspensaoAlimentacaoDeCEI/Relatorio/style.scss
  src/components/screens/helper.js
  src/configs/RoutesConfig.js
  src/configs/constants.js
  src/pages/SuspensaoAlimentacaoCEI/RelatorioPage.jsx
  src/services/suspensaoAlimentacaoCei.service.js
Labels: feature

#1713 Feature/70695-MI-tela-de-lancamento-de-alimentacao-pt1
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalObservacaoDiaria/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: enhancement, feature

#1714 Hom - Atualizado até 01/09/22 as 13:10
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalObservacaoDiaria/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: enhancement, feature

#1715 Feature/70695-MI-tela-de-lancamento-de-alimentacao-pt1
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalObservacaoDiaria/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: enhancement, feature

#1716 Hom - Atualizado até 01/09/22 as 17:45
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalObservacaoDiaria/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: enhancement, feature

#1717 Feature/70695-MI-tela-de-lancamento-de-alimentacao-pt1
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalObservacaoDiaria/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
Labels: enhancement, feature

#1718 Hom - Atualizado até 01/09/22 as 19:45
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalObservacaoDiaria/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
Labels: enhancement, feature

#1720 Fix/72543-PeD-melhoria-campo-rf-ao-responder-análise-sensorial
  src/components/screens/Produto/BuscaProdutoAnaliseSensorial/components/ModalResponderAnaliseSensorial/index.jsx
Labels: bug

#1722 Fix/72543-PeD-melhoria-campo-rf-ao-responder-análise-sensorial
  src/components/screens/Produto/BuscaProdutoAnaliseSensorial/components/ModalResponderAnaliseSensorial/index.jsx
Labels: bug

#1723 Hom - Atualizado até 05/09/22 as 11:45
  src/components/Shareable/Sidebar/menus/MenuLogistica.jsx
  src/components/screens/Logistica/ConferenciaInconsistencias/Filtros/index.jsx
  src/components/screens/Logistica/ConferenciaInconsistencias/ListagemInconsistencias/index.jsx
  src/components/screens/Produto/BuscaProdutoAnaliseSensorial/components/ModalResponderAnaliseSensorial/index.jsx
  src/pages/Logistica/ConferenciaInconsistenciasPage.jsx
Labels: bug

#1727 Feature/72834 melhoria realtorio produto
  src/components/screens/Produto/Homologacao/helper.js
  src/components/screens/Produto/Homologacao/index.jsx
Labels: feature

#1728 Feature: protocolos com base nos editais vinculados a escola da solicitação
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/index.jsx
  src/services/dietaEspecial.service.js
Labels: feature

#1729 Hom - Atualizado até 06/09/22 as 15:45
  src/components/Logistica/TabelaAlimentoConsolidado/index.jsx
  src/components/screens/CentralDownloads/components/ListagemDownloads/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/index.jsx
  src/components/screens/Logistica/ConferenciaDeGuia/index.jsx
  src/components/screens/Logistica/ConferenciaDeGuia/styles.scss
  src/components/screens/Logistica/ConferenciaDeGuiaComOcorrencia/index.jsx
  src/components/screens/Logistica/ConferenciaDeGuiaComOcorrencia/styles.scss
  src/components/screens/Logistica/ConferirEntrega/components/Filtros/index.jsx
  src/components/screens/Logistica/RegistrarInsucessoEntrega/index.jsx
  src/components/screens/Logistica/RegistrarInsucessoEntrega/styles.scss
  src/components/screens/Logistica/ReposicaoDeGuia/index.jsx
  src/components/screens/Logistica/ReposicaoDeGuia/styles.scss
  src/components/screens/Produto/Homologacao/helper.js
  src/components/screens/Produto/Homologacao/index.jsx
  src/services/dietaEspecial.service.js
Labels: feature

#1731 Feature/71891-MI-tela-lançamento-número-de-matriculados
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/services/medicaoInicial/periodoLancamentoMedicao.service.js
Labels: enhancement, feature

#1734 Feature/71890-MI-tela-lançamento-identificação-dias-não-letivos
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/services/medicaoInicial/periodoLancamentoMedicao.service.js
Labels: feature

#1735 Hom - Atualizado até 08/09/22 as 12:00
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/services/medicaoInicial/periodoLancamentoMedicao.service.js
Labels: feature

#1736 Feature/71891-MI-tela-lançamento-número-de-matriculados
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: feature

#1737 Hom - Atualizado até 09/09/22 as 18:30
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: feature

#1739 Feature/73038 inversao cardapio cemei
  src/components/InversaoDeDiaDeCardapio/index.jsx
  src/components/Shareable/CardMatriculados/index.jsx
  src/components/Shareable/CardMatriculados/style.scss
  src/components/screens/Produto/Homologacao/index.jsx
  src/pages/InversaoDeDiaDeCardapio/RelatorioPage.jsx
  src/reducers/inversaoDeDiaDeCardapio.reducer.js
Labels: feature

#1748 Feature/71892-MI-tela-lancamento-validações-frequência
  src/components/Shareable/Input/InputValueMedicao/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/styles.scss
  src/components/screens/helper.js
  src/helpers/fieldValidators.js
Labels: enhancement, feature

#1749 Hom - Atualizado até 14/09/22 as 17:30
  src/components/Shareable/Input/InputValueMedicao/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/styles.scss
  src/components/screens/helper.js
  src/helpers/fieldValidators.js
Labels: enhancement, feature

#1753 Feature/73034-GA-solicitação-suspensão-CEMEI
  src/components/Shareable/CardMatriculados/index.jsx
  src/components/Shareable/TextArea/TextAreaWYSIWYG/index.jsx
  src/components/SuspensaoDeAlimentacao/index.jsx
  src/components/SuspensaoDeAlimentacao/validacao.js
  src/reducers/suspensaoDeAlimentacaoReducer.js
  src/services/aluno.service.js
Labels: enhancement, feature

#1754 Hom - Atualizado até 17/09/22 as 13:30
  src/components/Shareable/CardMatriculados/index.jsx
  src/components/Shareable/TextArea/TextAreaWYSIWYG/index.jsx
  src/components/SuspensaoDeAlimentacao/index.jsx
  src/components/SuspensaoDeAlimentacao/validacao.js
  src/reducers/suspensaoDeAlimentacaoReducer.js
  src/services/aluno.service.js
Labels: enhancement, feature

#1757 Feature/73034-73035-GA
  src/pages/Escola/SuspensaoDeAlimentacaoPage.jsx
  src/pages/SolicitacaoDeKitLanche/ContainerPage.jsx
Labels: enhancement, feature

#1758 Hom - Atualizado até 19/09/22 as 11:20
  src/pages/Escola/SuspensaoDeAlimentacaoPage.jsx
  src/pages/SolicitacaoDeKitLanche/ContainerPage.jsx
Labels: enhancement, feature

#1764 Feature/73034-GA-ajustes-campo-observação
  src/components/Shareable/TextArea/TextAreaWYSIWYG/index.jsx
  src/components/SuspensaoDeAlimentacao/index.jsx
Labels: enhancement, feature

#1766 Hom - Atualizado até 19/09/22 as 19:45
  src/components/Shareable/TextArea/TextAreaWYSIWYG/index.jsx
  src/components/SuspensaoDeAlimentacao/index.jsx
Labels: enhancement, feature

#1773 Feature: Criar pagina para alteração de cardápio CEMEI
  src/components/AlteracaoDeCardapioCEMEI/componentes/Container.jsx
  src/components/AlteracaoDeCardapioCEMEI/componentes/Rascunhos.jsx
  src/components/AlteracaoDeCardapioCEMEI/componentes/TabelaFaixasCEMEI.jsx
  src/components/AlteracaoDeCardapioCEMEI/helpers.js
  src/components/AlteracaoDeCardapioCEMEI/index.jsx
  src/components/AlteracaoDeCardapioCEMEI/style.scss
  src/configs/helper.js
  src/pages/Escola/AlteracaoDeCardapioCEMEIPage.jsx
  src/services/alteracaoDeCardapio/escola.service.js
Labels: feature

#1776 Fix: campo justificativa
  src/components/AlteracaoDeCardapioCEMEI/helpers.js
  src/components/AlteracaoDeCardapioCEMEI/index.jsx
Labels: bug

#1778 Hom atualizado 22/09 as 11h
  src/components/AlteracaoDeCardapioCEMEI/helpers.js
  src/components/AlteracaoDeCardapioCEMEI/index.jsx
Labels: bug

#1782 Fix: regras do seletor de motivo
  src/components/AlteracaoDeCardapioCEMEI/index.jsx
Labels: bug

#1784 Hom atualizado 23/09 as 10h30
  src/components/AlteracaoDeCardapioCEMEI/index.jsx
Labels: bug

#1787 Feature/74098-PeD-impressão-pdf-ficha-identificação-produto
  src/components/screens/Produto/Homologacao/index.jsx
  src/components/screens/Produto/Homologacao/style.scss
  src/services/produto.service.js
Labels: feature

#1788 Hom - Atualizado até 23/09/22 as 13:45
  src/components/screens/Produto/Homologacao/index.jsx
  src/components/screens/Produto/Homologacao/style.scss
  src/services/produto.service.js
Labels: feature

#1797 Feature/72545-PeD-alterar-msg-após-enviar-alteração-de-ficha-de-produto-já-homologado
  src/components/screens/Produto/AtualizacaoProdutoForm/components/WizardFormTerceiraPagina.jsx
Labels: feature

#1799 Hom - Atualizado até 28/09/22 as 09:45
  src/components/screens/Produto/AtualizacaoProdutoForm/components/WizardFormTerceiraPagina.jsx
Labels: feature

#1806 Feature/74095 melhoria relatorio produto
  src/components/Shareable/ModalPadrao/index.jsx
  src/components/screens/Produto/AvaliarReclamacaoProduto/components/TabelaProdutos/index.jsx
  src/components/screens/Produto/Homologacao/components/AnaliseSensorial.jsx
  src/components/screens/Produto/Homologacao/components/BotoesCabecalho.jsx
  src/components/screens/Produto/Homologacao/components/BotoesGPCODAE.jsx
  src/components/screens/Produto/Homologacao/components/BotoesTerceirizada.jsx
  src/components/screens/Produto/Homologacao/components/Container.jsx
  src/components/screens/Produto/Homologacao/components/DadosDaEmpresa.jsx
  src/components/screens/Produto/Homologacao/components/DocumentosProduto.jsx
  src/components/screens/Produto/Homologacao/components/EditaisVinculados.jsx
  src/components/screens/Produto/Homologacao/components/FotosProduto.jsx
  src/components/screens/Produto/Homologacao/components/IdentificacaoProduto.jsx
  src/components/screens/Produto/Homologacao/components/InformacoesNutricionais.jsx
  src/components/screens/Produto/Homologacao/components/InformacoesProduto.jsx
  src/components/screens/Produto/Homologacao/components/ModalCancelarHomologacaoProduto/index.jsx
  src/components/screens/Produto/Homologacao/components/ModelVincularEditais/index.jsx
  src/components/screens/Produto/Homologacao/components/Respostas/JustificativaAnalise.jsx
  src/components/screens/Produto/Homologacao/components/Respostas/MotivoCancelamento.jsx
  src/components/screens/Produto/Homologacao/components/Respostas/MotivoCorrecaoHomologacao.jsx
  src/components/screens/Produto/Homologacao/components/Respostas/MotivoHomologacaoRecusada.jsx
  src/components/screens/Produto/Homologacao/components/Respostas/MotivoSuspensao.jsx
  src/components/screens/Produto/Homologacao/components/Respostas/index.jsx
  src/components/screens/Produto/Homologacao/helper.js
  src/components/screens/Produto/Homologacao/index.jsx
  src/components/screens/Produto/Homologacao/style.scss
  src/pages/Produto/HomologacaoProdutoPage.jsx
Labels: feature

#1807 Feature/72225 mi upload arquivos de ocorrencias
  src/components/Shareable/HelpText/index.jsx
  src/components/Shareable/Input/InputFile/index.jsx
  src/components/Shareable/Input/InputFile/style.scss
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/InformacoesEscola/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/InformacoesMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/ModalFinalizarMedicao/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/styles.scss
  src/components/screens/Perfil/components/ModalAlterarSenha/index.jsx
  src/components/screens/Perfil/style.scss
Labels: feature

#1816 Hom atualizada 30/09 as 10h10
  src/components/Shareable/HelpText/index.jsx
  src/components/Shareable/Input/InputFile/index.jsx
  src/components/Shareable/Input/InputFile/style.scss
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/InformacoesEscola/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/InformacoesMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/ModalFinalizarMedicao/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/styles.scss
  src/components/screens/Perfil/components/ModalAlterarSenha/index.jsx
  src/components/screens/Perfil/style.scss
Labels: feature

#1819 Bugfix/74095 corrigir regra de exibicao dos componentes
  src/components/Shareable/FluxoDeStatus/helper.js
  src/components/Shareable/Input/InputFile/index.jsx
  src/components/screens/Produto/BuscaProdutoAnaliseSensorial/components/ModalResponderAnaliseSensorial/index.jsx
  src/components/screens/Produto/Homologacao/components/AnaliseSensorial.jsx
  src/components/screens/Produto/Homologacao/components/Respostas/index.jsx
  src/components/screens/Produto/Homologacao/index.jsx
Labels: bug

#1820 Hom atualizado 30/09 as 14h30
  src/components/Shareable/FluxoDeStatus/helper.js
  src/components/Shareable/Input/InputFile/index.jsx
  src/components/screens/Produto/BuscaProdutoAnaliseSensorial/components/ModalResponderAnaliseSensorial/index.jsx
  src/components/screens/Produto/Homologacao/components/AnaliseSensorial.jsx
  src/components/screens/Produto/Homologacao/components/Respostas/index.jsx
  src/components/screens/Produto/Homologacao/index.jsx
Labels: bug

#1822 Hom atualizado 30/09 as 15h30
  src/components/screens/Produto/Homologacao/components/BotoesGPCODAE.jsx
  src/components/screens/Produto/Homologacao/components/BotoesRodape.jsx
  src/components/screens/Produto/Homologacao/components/BotoesTerceirizada.jsx
  src/components/screens/Produto/Homologacao/index.jsx
Labels: bug

#1825 Fix: icon no botão voltar
  src/components/screens/Produto/Homologacao/components/BotoesRodape.jsx
Labels: bug

#1826 Hom atualizado 30/09 as 17h15
  src/components/screens/Produto/Homologacao/components/BotoesRodape.jsx
Labels: bug
