Repository prefeiturasp/SME-Terceirizadas-Frontend, pull requests merged in 2022-05, with the labels that each got.

#1372 Feature/62896 cadastro tipos alimentacao
  src/components/screens/Cadastros/CadastroTipoAlimentacao/Container.jsx
  src/components/screens/Cadastros/CadastroTipoAlimentacao/index.jsx
  src/components/screens/Cadastros/CadastroTipoAlimentacao/style.scss
  src/services/cadastroTipoAlimentacao.service.js
Labels: feature

#1382 Fix: verificar tipo perfil no submit
  src/components/screens/Produto/Reclamacao/components/ModalReclamacaoProduto/index.jsx
Labels: bug

#1383 HOM - Atualizada 04/05 às 14:10
  src/components/screens/Produto/Reclamacao/components/ModalReclamacaoProduto/index.jsx
Labels: bug

#1384 Atualizacao da alteracao de cardapio CEI com nova modelagem + pequeno…
  src/components/AlteracaoDeCardapio/CEI/AlteracaoCardapio.jsx
  src/components/AlteracaoDeCardapio/CEI/helper.js
  src/components/Shareable/DatePicker/index.jsx
  src/components/Shareable/TabelaQuantidadePorFaixaEtaria/index.jsx
  src/components/Shareable/TextArea/TextAreaWYSIWYG/index.jsx
  src/reducers/alteracaoCardapioReducer.js
  src/services/alteracaoDeCardapio/escola.service.js
Labels: refactoring

#1385 Feature/62415-PeD-melhoria-desempenho-painel-gestão-produtos
  src/components/Shareable/CardBody.jsx
  src/components/Shareable/style.scss
  src/components/screens/DashboardGestaoProduto/index.jsx
  src/services/produto.service.js
Labels: feature, refactoring

#1386 Hom - Atualizado até 06/05/22 as 18:25
  src/components/AlteracaoDeCardapio/CEI/AlteracaoCardapio.jsx
  src/components/AlteracaoDeCardapio/CEI/helper.js
  src/components/Shareable/CardBody.jsx
  src/components/Shareable/DatePicker/index.jsx
  src/components/Shareable/TabelaQuantidadePorFaixaEtaria/index.jsx
  src/components/Shareable/TextArea/TextAreaWYSIWYG/index.jsx
  src/components/Shareable/style.scss
  src/components/screens/DashboardGestaoProduto/index.jsx
  src/reducers/alteracaoCardapioReducer.js
  src/services/alteracaoDeCardapio/escola.service.js
  src/services/produto.service.js
Labels: feature, refactoring

#1390 Feature/57415 horarios de alimentacao
  src/components/screens/Cadastros/CadastroHorarioComboAlimentacao/Container.jsx
  src/components/screens/Cadastros/CadastroHorarioComboAlimentacao/components/ModalAlterarQuantidadeAlunos.jsx
  src/components/screens/Cadastros/CadastroHorarioComboAlimentacao/helper.js
  src/components/screens/Cadastros/CadastroHorarioComboAlimentacao/index.jsx
  src/components/screens/Cadastros/CadastroHorarioComboAlimentacao/style.scss
Labels: feature

#1392 Fix: exibição do horário sem os segundos
  src/components/screens/Cadastros/CadastroHorarioComboAlimentacao/index.jsx
Labels: bug

#1393 HOM - Atualizada 16/05 às 10:50
  src/components/screens/Cadastros/CadastroHorarioComboAlimentacao/Container.jsx
  src/components/screens/Cadastros/CadastroHorarioComboAlimentacao/components/ModalAlterarQuantidadeAlunos.jsx
  src/components/screens/Cadastros/CadastroHorarioComboAlimentacao/helper.js
  src/components/screens/Cadastros/CadastroHorarioComboAlimentacao/index.jsx
  src/components/screens/Cadastros/CadastroHorarioComboAlimentacao/style.scss
Labels: feature

#1394 Feature/63524-DE-filtros-relatórios-dieta-especial-terceirizadas
  src/components/Shareable/Botao/constants.js
  src/components/Shareable/Sidebar/menus/MenuDietaEspecial.jsx
  src/components/Shareable/Sidebar/menus/MenuRelatorios.jsx
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/components/Filtros/index.jsx
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/components/Filtros/styles.scss
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/index.jsx
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/styles.scss
  src/components/screens/DietaEspecial/RelatorioGestaoDietaEspecial/components/FormFiltros/helpers.js
  src/components/screens/DietaEspecial/RelatorioGestaoDietaEspecial/components/FormFiltros/index.jsx
  src/components/screens/DietaEspecial/RelatorioGestaoDietaEspecial/components/FormFiltros/styles.scss
  src/components/screens/DietaEspecial/RelatorioGestaoDietaEspecial/components/ModalRelatorioDietaEspecial/helpers.jsx
  src/components/screens/DietaEspecial/RelatorioGestaoDietaEspecial/components/ModalRelatorioDietaEspecial/index.jsx
  src/components/screens/DietaEspecial/RelatorioGestaoDietaEspecial/components/ModalRelatorioDietaEspecial/styles.scss
  src/components/screens/DietaEspecial/RelatorioGestaoDietaEspecial/index.jsx
  src/configs/RoutesConfig.js
  src/configs/constants.js
  src/constants/shared.js
  src/helpers/terceirizadas.js
  src/pages/DietaEspecial/RelatorioDietaEspecial.jsx
  src/pages/DietaEspecial/RelatorioGestaoDietaEspecial.jsx
  src/services/dietaEspecial.service.js
Labels: feature

#1396 Feature/63529-DE-resultado-da-busca-relatórios-dieta-especial-terceirizadas
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/components/Filtros/index.jsx
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/components/Filtros/styles.scss
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/components/ListagemDietas/index.jsx
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/components/ListagemDietas/styles.scss
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/index.jsx
Labels: feature

#1397 Hom - Atualizado até 16/05/22 as 14:15
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/components/Filtros/index.jsx
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/components/Filtros/styles.scss
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/components/ListagemDietas/index.jsx
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/components/ListagemDietas/styles.scss
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/index.jsx
Labels: feature

#1398 Feature/63529-DE-resultado-da-busca-relatórios-dieta-especial-terceirizadas
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/components/Filtros/index.jsx
Labels: feature

#1399 Hom - Atualizado até 16/05/22 as 15:10
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/components/Filtros/index.jsx
Labels: feature

#1402 Feature/63529-DE-resultado-da-busca-relatórios-dieta-especial-terceirizadas
  src/components/Shareable/Paginacao/style.scss
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/components/ListagemDietas/index.jsx
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/components/ListagemDietas/styles.scss
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/index.jsx
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/styles.scss
Labels: feature

#1404 Feature: botão e service para exportar pdf
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/index.jsx
  src/services/dietaEspecial.service.js
Labels: feature

#1405 HOM - Atualizada 18/05 às 09:35
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/index.jsx
  src/services/dietaEspecial.service.js
Labels: feature

#1406 Feature/63524-DE-ajuste-sidebar-relatórios-dieta-especial-terceirizadas
  src/components/Shareable/Sidebar/SidebarContent.jsx
  src/components/Shareable/Sidebar/menus/MenuDietaEspecial.jsx
  src/components/Shareable/Sidebar/menus/MenuRelatorios.jsx
Labels: feature

#1407 Hom - Atualizado até 18/05/22 as 16:20
  src/components/Shareable/Sidebar/SidebarContent.jsx
  src/components/Shareable/Sidebar/menus/MenuDietaEspecial.jsx
  src/components/Shareable/Sidebar/menus/MenuRelatorios.jsx
Labels: feature

#1409 Feature: melhoria na mensagem informativa de dietas vigentes
  src/components/screens/DietaEspecial/Escola/componentes/SolicitacaoVigente/index.jsx
Labels: feature

#1410 Fix/63540-acerto-cadastro-ues-no-cadastro-de-lotes
  src/components/screens/Cadastros/CadastroLote/components/LotesCadastrados/index.jsx
  src/components/screens/Cadastros/CadastroLote/index.jsx
Labels: bug

#1412 HOM - Atualizada 20/05 às 11:35
  src/components/screens/Cadastros/CadastroLote/components/LotesCadastrados/index.jsx
  src/components/screens/Cadastros/CadastroLote/index.jsx
  src/components/screens/DietaEspecial/Escola/componentes/SolicitacaoVigente/index.jsx
Labels: feature

#1411 Feature/64363-perfil-meus-dados-incluir-campo-de-cargo
  src/components/screens/Perfil/index.jsx
Labels: feature

#1413 Hom - Atualizado até 20/05/22 as 12:20
  src/components/screens/Perfil/index.jsx
Labels: feature

#1414 Feature/64365-DE-melhoria-direcionamento-solicitações-inclusão-e-alteracão-scroll-top
  src/components/screens/DietaEspecial/AlteracaoUE/index.jsx
  src/components/screens/DietaEspecial/Escola/index.jsx
Labels: feature

#1415 Hom - Atualizado até 20/05/22 as 14:00
  src/components/screens/DietaEspecial/AlteracaoUE/index.jsx
  src/components/screens/DietaEspecial/Escola/index.jsx
Labels: feature

#1416 Feature/64854-PeD-melhoria-cadastro-de-marca-e-fabricante
  src/components/Shareable/ModalCadastrarItem/index.jsx
  src/helpers/fieldValidators.js
Labels: feature

#1419 Hom - Atualizado até 24/05/22 as 14:35
  src/components/Shareable/CardAtalho/index.jsx
  src/components/Shareable/ModalCadastrarItem/index.jsx
  src/components/screens/DashboardEscola/DashboardEscola.jsx
  src/components/screens/DashboardGestaoProduto/index.jsx
  src/helpers/fieldValidators.js
Labels: feature

#1420 Hotfix/65441-DE-não-está-mostrando-anexos-tela-de-autorizar-cancelamento-dieta
  src/components/screens/DietaEspecial/Relatorio/componentes/CorpoRelatorio/index.jsx
Labels: bug

#1422 Fix/57563-invalid-date-datepicker-component
  src/components/Shareable/DatePicker/index.jsx
Labels: bug

#1426 Prod - Atualizado até 25/05/2022 as 16:10 (hotfix)
  src/components/screens/DietaEspecial/Relatorio/componentes/CorpoRelatorio/index.jsx
Labels: bug

#1428 Dev - Atualizado até 25/05/2022 as 16:25 (hotfix -- homolog > development)
  src/components/screens/DietaEspecial/Relatorio/componentes/CorpoRelatorio/index.jsx
Labels: bug

#1429 Fix/31506-GA-erro-ao-abrir-rascunho-alteração-cardápio-e-kit-lanche
  src/components/AlteracaoDeCardapio/index.jsx
  src/components/SolicitacaoDeKitLanche/Container/base.jsx
  src/reducers/alteracaoCardapioReducer.js
Labels: bug

#1431 Fix/52089-GA-alteração-tipo-alimentação-erro-troca-período
  src/components/AlteracaoDeCardapio/index.jsx
  src/reducers/alteracaoCardapioReducer.js
Labels: bug

#1430 Hom - Atualizado até 30/05/22 as 17:45
  src/components/AlteracaoDeCardapio/index.jsx
  src/components/SolicitacaoDeKitLanche/Container/base.jsx
  src/reducers/alteracaoCardapioReducer.js
Labels: bug

#1432 Fix/31506-GA-erro-ao-abrir-rascunho-alteração-cardápio-e-kit-lanche
  src/components/AlteracaoDeCardapio/index.jsx
  src/components/AlteracaoDeCardapio/validacao.js
Labels: bug

#1433 Hom - Atualizado até 31/05/22 as 12:30
  src/components/AlteracaoDeCardapio/index.jsx
  src/components/AlteracaoDeCardapio/validacao.js
Labels: bug

#1434 Fix/31506-GA-rascunho-alteracao-cardapio-ajuste-includes
  src/components/AlteracaoDeCardapio/index.jsx
Labels: bug

#1435 Hom - Atualizado até 31/05/22 as 16:30
  src/components/AlteracaoDeCardapio/index.jsx
Labels: bug

#1436 Fix/31506-GA-rascunho-alteracao-cardapio-ajuste-unmount-component
  src/components/AlteracaoDeCardapio/index.jsx
Labels: bug

#1437 Hom - Atualizado até 31/05/22 as 17:50
  src/components/AlteracaoDeCardapio/index.jsx
Labels: bug
