Repository prefeiturasp/SME-Terceirizadas-Frontend, pull requests merged in 2022-04, with the labels that each got.

#1327 Bugfix/60090-PD-relatório-com-data-de-homologação-errada
  src/components/screens/RelatorioProdutosHomologados/index.js
  src/components/screens/helper.js
Labels: bug

#1328 Hom - Atualizado até 01/04/22 as 10:45
  src/components/screens/RelatorioProdutosHomologados/index.js
  src/components/screens/helper.js
Labels: bug

#1329 Hom - Atualizado até 01/04/22 as 11:10 (homolog > homolog-r2)
  src/components/Shareable/DownloadsNavbar/index.jsx
  src/components/Shareable/DownloadsNavbar/style.scss
  src/components/Shareable/Header/index.jsx
  src/components/Shareable/ModalHistoricoProtocoloPadrao/index.jsx
  src/components/Shareable/ModalSolicitacaoDownload/index.jsx
  src/components/screens/CentralDownloads/components/Filtros/index.jsx
  src/components/screens/CentralDownloads/components/Filtros/styles.scss
  src/components/screens/CentralDownloads/components/ListagemDownloads/index.jsx
  src/components/screens/CentralDownloads/components/ListagemDownloads/styles.scss
  src/components/screens/CentralDownloads/index.jsx
  src/components/screens/CentralDownloads/styles.scss
  src/components/screens/DietaEspecial/CadastroProtocoloPadraoDietaEsp/componentes/SubstituicoesField/index.jsx
  src/components/screens/DietaEspecial/ConsultaProtocoloPadraoDieta/componentes/DetalhesProtocolo/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/SubstituicoesField/SubstituicoesTable.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/SubstituicoesField/index.jsx
  src/components/screens/Logistica/ConsultaEntregas/components/ListagemSolicitacoes/index.jsx
  src/components/screens/Logistica/ConsultaRequisicaoEntregaDilog/components/Filtros/index.jsx
  src/components/screens/Logistica/ConsultaRequisicaoEntregaDilog/components/ListagemSolicitacoes/index.js
  src/components/screens/Logistica/ConsultaRequisicaoEntregaDilog/index.jsx
  src/components/screens/Logistica/GestaoRequisicaoEntrega/components/ListagemSolicitacoes/index.js
  src/components/screens/Logistica/GestaoRequisicaoEntrega/index.js
  src/components/screens/RelatorioProdutosHomologados/index.js
  src/components/screens/helper.js
  src/configs/RoutesConfig.js
  src/configs/constants.js
  src/constants/shared.js
  src/context/CentralDeDownloads/index.js
  src/helpers/utilities.js
  src/index.jsx
  src/pages/CentralDownloads/CentralDownloadsPage.jsx
  src/services/downloads.service.js
  src/services/logistica.service.js
  src/styles/_overrides.scss
Labels: bug

#1330 Prod - Atualizado até 04/04/2022 as 17:00
  src/components/Shareable/DownloadsNavbar/index.jsx
  src/components/Shareable/DownloadsNavbar/style.scss
  src/components/Shareable/Header/index.jsx
  src/components/Shareable/ModalHistoricoProtocoloPadrao/index.jsx
  src/components/Shareable/ModalSolicitacaoDownload/index.jsx
  src/components/screens/CentralDownloads/components/Filtros/index.jsx
  src/components/screens/CentralDownloads/components/Filtros/styles.scss
  src/components/screens/CentralDownloads/components/ListagemDownloads/index.jsx
  src/components/screens/CentralDownloads/components/ListagemDownloads/styles.scss
  src/components/screens/CentralDownloads/index.jsx
  src/components/screens/CentralDownloads/styles.scss
  src/components/screens/DietaEspecial/CadastroProtocoloPadraoDietaEsp/componentes/SubstituicoesField/index.jsx
  src/components/screens/DietaEspecial/ConsultaProtocoloPadraoDieta/componentes/DetalhesProtocolo/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/SubstituicoesField/SubstituicoesTable.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/SubstituicoesField/index.jsx
  src/components/screens/Logistica/ConsultaEntregas/components/ListagemSolicitacoes/index.jsx
  src/components/screens/Logistica/ConsultaRequisicaoEntregaDilog/components/Filtros/index.jsx
  src/components/screens/Logistica/ConsultaRequisicaoEntregaDilog/components/ListagemSolicitacoes/index.js
  src/components/screens/Logistica/ConsultaRequisicaoEntregaDilog/index.jsx
  src/components/screens/Logistica/GestaoRequisicaoEntrega/components/ListagemSolicitacoes/index.js
  src/components/screens/Logistica/GestaoRequisicaoEntrega/index.js
  src/components/screens/RelatorioProdutosHomologados/index.js
  src/components/screens/helper.js
  src/configs/RoutesConfig.js
  src/configs/constants.js
  src/constants/shared.js
  src/context/CentralDeDownloads/index.js
  src/helpers/utilities.js
  src/index.jsx
  src/pages/CentralDownloads/CentralDownloadsPage.jsx
  src/services/downloads.service.js
  src/services/logistica.service.js
  src/styles/_overrides.scss
Labels: feature

#1331 Feature/61720-liberar-relatórios-para-usuário-nutrimanifestação
  src/components/Shareable/Sidebar/menus/MenuRelatorios.jsx
  src/configs/RoutesConfig.js
Labels: feature

#1332 Feature/61720 liberar relatorios para usuario nutrimanifestacao
  src/components/Shareable/Sidebar/menus/MenuRelatorios.jsx
  src/configs/RoutesConfig.js
Labels: feature

#1334 Feature: alteração título do label
  src/components/AlteracaoDeCardapio/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/InclusaoDeAlimentacao/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/InversaoDeDiaDeCardapio/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/SolicitacaoDeKitLanche/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/SolicitacaoUnificada/Relatorio/componentes/CorpoRelatorio.jsx
Labels: feature

#1335 Fix/61844-DE-problema-campo-de-busca-protocolo-padrão
  src/components/screens/DietaEspecial/ConsultaProtocoloPadraoDieta/componentes/Filtros/index.jsx
Labels: bug

#1336 Hom - Atualizado até 06/04/22 as 17:30
  src/components/AlteracaoDeCardapio/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/InclusaoDeAlimentacao/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/InversaoDeDiaDeCardapio/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/SolicitacaoDeKitLanche/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/SolicitacaoUnificada/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/screens/DietaEspecial/ConsultaProtocoloPadraoDieta/componentes/Filtros/index.jsx
Labels: bug, feature

#1337 Feature/61312-GA-PeD-retirar-acesso-aos-módulos-escola-tipo-gestão-direta
  src/components/Shareable/Sidebar/SidebarContent.jsx
  src/components/Shareable/Sidebar/menus/MenuGestaoDeAlimentacao.jsx
  src/components/Shareable/Sidebar/menus/MenuLancamentoInicial.jsx
  src/components/Shareable/Sidebar/menus/MenuRelatorios.jsx
  src/components/screens/PainelInicial/index.jsx
  src/configs/RoutesConfig.js
  src/helpers/permissions.js
  src/helpers/utilities.js
Labels: feature

#1338 Feature: usar tipos_alimentacao ao invés de combos
  src/components/SuspensaoDeAlimentacao/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/SuspensaoDeAlimentacao/index.jsx
Labels: feature

#1342 Feature/57922 usar tipos alimentacao em solicitacoes de inclusao
  src/components/InclusaoDeAlimentacao/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/InclusaoDeAlimentacao/helper.js
  src/components/InclusaoDeAlimentacaoDaCei/helper.js
  src/constants/shared.js
Labels: feature, refactoring

#1345 Feature: usar tipos de alimentação em alteração de cardápio
  src/components/AlteracaoDeCardapio/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/AlteracaoDeCardapio/helper.js
  src/components/AlteracaoDeCardapio/index.jsx
  src/components/AlteracaoDeCardapio/validacao.js
Labels: feature, refactoring

#1341 Feature/57922 alteracao modelagem gestao alimentacao
  src/components/AlteracaoDeCardapio/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/AlteracaoDeCardapio/helper.js
  src/components/AlteracaoDeCardapio/index.jsx
  src/components/AlteracaoDeCardapio/validacao.js
  src/components/InclusaoDeAlimentacao/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/InclusaoDeAlimentacao/helper.js
  src/components/InclusaoDeAlimentacaoDaCei/helper.js
  src/components/SuspensaoDeAlimentacao/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/SuspensaoDeAlimentacao/index.jsx
  src/constants/shared.js
Labels: feature, refactoring

#1348 Prod - Atualizado até 19/04/2022 as 17:20
  .github/workflows/CI-CD.yml
  .github/workflows/Dev-CI-CD.yml
  src/components/AlteracaoDeCardapio/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/AlteracaoDeCardapio/helper.js
  src/components/AlteracaoDeCardapio/index.jsx
  src/components/AlteracaoDeCardapio/validacao.js
  src/components/InclusaoDeAlimentacao/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/InclusaoDeAlimentacao/helper.js
  src/components/InclusaoDeAlimentacaoDaCei/helper.js
  src/components/InversaoDeDiaDeCardapio/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/Shareable/Botao/constants.js
  src/components/Shareable/Sidebar/SidebarContent.jsx
  src/components/Shareable/Sidebar/menus/MenuGestaoDeAlimentacao.jsx
  src/components/Shareable/Sidebar/menus/MenuLancamentoInicial.jsx
  src/components/Shareable/Sidebar/menus/MenuRelatorios.jsx
  src/components/SolicitacaoDeKitLanche/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/SolicitacaoUnificada/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/SuspensaoDeAlimentacao/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/SuspensaoDeAlimentacao/index.jsx
  src/components/screens/DietaEspecial/ConsultaProtocoloPadraoDieta/componentes/Filtros/index.jsx
  src/components/screens/Logistica/ConferenciaDeGuia/components/ReceberSemOcorrencia/index.jsx
  src/components/screens/Logistica/ConferenciaDeGuia/index.jsx
  src/components/screens/Logistica/ConferenciaDeGuia/styles.scss
  src/components/screens/PainelInicial/index.jsx
  src/configs/RoutesConfig.js
  src/constants/shared.js
  src/helpers/permissions.js
  src/helpers/utilities.js
Labels: feature

#1353 Fix/61206-DE-problema-linha-do-tempo-cancelamento-automático
  src/components/Shareable/FluxoDeStatus/helper.js
Labels: bug

#1362 Hom - Atualizado até 21/04/22 as 19:15
  src/components/Shareable/CardBody.jsx
  src/components/screens/DashboardGestaoProduto/index.jsx
Labels: feature

#1365 Feature/59416 reclamacao produto nutrisupervisao
  src/components/screens/Produto/Reclamacao/components/ModalReclamacaoProduto/index.jsx
  src/helpers/fieldValidators.js
  src/services/escola.service.js
Labels: feature

#1370 Hom - Atualizado até 27/04/22 as 13:20
  src/components/screens/Produto/Reclamacao/components/ModalReclamacaoProduto/index.jsx
  src/helpers/fieldValidators.js
  src/services/escola.service.js
Labels: feature
