Repository prefeiturasp/SME-Terceirizadas-Frontend, pull requests merged in 2022-11, with the labels that each got.

#1985 Feature: refatoração tela InclusãoAlimentacaoDaCei
  src/components/InclusaoDeAlimentacaoDaCei/Container.jsx
  src/components/InclusaoDeAlimentacaoDaCei/Rascunhos.jsx
  src/components/InclusaoDeAlimentacaoDaCei/TabelaFaixasCEI.jsx
  src/components/InclusaoDeAlimentacaoDaCei/helper.js
  src/components/InclusaoDeAlimentacaoDaCei/index.jsx
  src/components/InclusaoDeAlimentacaoDaCei/style.scss
Labels: feature

#1986 Hom atualizado 03/11 as 18h10
  src/components/InclusaoDeAlimentacaoDaCei/Container.jsx
  src/components/InclusaoDeAlimentacaoDaCei/Rascunhos.jsx
  src/components/InclusaoDeAlimentacaoDaCei/TabelaFaixasCEI.jsx
  src/components/InclusaoDeAlimentacaoDaCei/helper.js
  src/components/InclusaoDeAlimentacaoDaCei/index.jsx
  src/components/InclusaoDeAlimentacaoDaCei/style.scss
Labels: feature

#1988 Feature: exibir layout diferente quando a solicitacao usar nova modelagem
  src/components/InclusaoDeAlimentacao/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/InclusaoDeAlimentacao/Relatorio/componentes/InclusoesCEI.jsx
Labels: feature

#1992 Feature/77600 relatorio inclusao cemei dre
  src/components/InclusaoDeAlimentacao/DRE/PainelPedidos/index.jsx
  src/components/InclusaoDeAlimentacao/Escola/Formulario/componentes/InclusaoContinua/index.jsx
  src/components/InclusaoDeAlimentacao/components/CardPendenteAcao/index.jsx
  src/components/InclusaoDeAlimentacaoCEMEI/Relatorio/index.jsx
  src/components/Shareable/ModalNaoValidarFinalForm/index.jsx
  src/components/Shareable/ModalNaoValidarSolicitacaoReduxForm/index.jsx
  src/configs/helper.js
  src/helpers/corrigeDadosDoDashboard.js
  src/helpers/painelPedidos.js
  src/pages/AlteracaoDeCardapio/RelatorioPage.jsx
  src/pages/InclusaoDeAlimentacao/RelatorioPage.jsx
  src/pages/InclusaoDeAlimentacaoCEMEIRelatorios/index.jsx
  src/pages/InversaoDeDiaDeCardapio/RelatorioPage.jsx
  src/pages/SolicitacaoDeKitLanche/RelatorioPage.jsx
  src/pages/SolicitacaoDeKitLancheCEMEI/RelatorioPage.jsx
Labels: feature

#1993 Feature/77591-PeD-alterar-ordem-do-campo-de-DE-telas-de-cadastro-e-edição-de-produtos
  src/components/screens/Produto/AtualizacaoProdutoForm/components/WizardFormPrimeiraPagina.jsx
  src/components/screens/Produto/AtualizacaoProdutoForm/components/styles.scss
  src/components/screens/Produto/Cadastro/Step1/index.jsx
Labels: enhancement

#1995 Hom - Atualizado até 04/11/22 as 17:25
  src/components/screens/Logistica/ConsultaRequisicaoEntregaDilog/index.jsx
  src/components/screens/Logistica/GestaoRequisicaoEntrega/index.js
  src/components/screens/Produto/AtualizacaoProdutoForm/components/WizardFormPrimeiraPagina.jsx
  src/components/screens/Produto/AtualizacaoProdutoForm/components/styles.scss
  src/components/screens/Produto/Cadastro/Step1/index.jsx
  src/services/disponibilizacaoDeSolicitacoes.service.js
Labels: enhancement, feature

#1997 Hom - Atualizado até 07/11/22 as 12:55
  src/components/screens/Produto/Homologacao/components/IdentificacaoProduto.jsx
  src/components/screens/Produto/Homologacao/index.jsx
Labels: enhancement

#2000 Feature/76235-GA-pdf-solicita;cão-de-suspensão-cei
  src/components/SuspensaoAlimentacaoDeCEI/Index.jsx
  src/components/SuspensaoAlimentacaoDeCEI/Relatorio/components/CorpoRelatorio/index.jsx
  src/components/SuspensaoAlimentacaoDeCEI/Relatorio/components/ModalCancelaSuspensao/index.jsx
  src/components/SuspensaoAlimentacaoDeCEI/Relatorio/index.jsx
  src/components/SuspensaoDeAlimentacao/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/SuspensaoDeAlimentacao/Relatorio/index.jsx
  src/components/SuspensaoDeAlimentacao/components/ModalCancelaSuspensao/index.jsx
  src/pages/SuspensaoAlimentacaoCEI/RelatorioPage.jsx
  src/pages/Terceirizada/SuspensaoAlimentacao/RelatorioPage.jsx
  src/services/relatorios.js
Labels: enhancement, feature

#2004 Hom - Atualizado até 08/11/22 as 16:25
  src/components/SuspensaoAlimentacaoDeCEI/Index.jsx
  src/components/SuspensaoAlimentacaoDeCEI/Relatorio/components/CorpoRelatorio/index.jsx
  src/components/SuspensaoAlimentacaoDeCEI/Relatorio/components/ModalCancelaSuspensao/index.jsx
  src/components/SuspensaoAlimentacaoDeCEI/Relatorio/index.jsx
  src/components/SuspensaoDeAlimentacao/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/SuspensaoDeAlimentacao/Relatorio/index.jsx
  src/components/SuspensaoDeAlimentacao/components/ModalCancelaSuspensao/index.jsx
  src/pages/SuspensaoAlimentacaoCEI/RelatorioPage.jsx
  src/pages/Terceirizada/SuspensaoAlimentacao/RelatorioPage.jsx
  src/services/relatorios.js
Labels: enhancement, feature

#2021 Fix: step número inteiro
  src/components/InclusaoDeAlimentacaoDaCei/TabelaFaixasCEI.jsx
Labels: bug

#2023 HOM - Atualizada até 11/11 às 10:30
  src/components/InclusaoDeAlimentacaoCEMEI/Relatorio/index.jsx
  src/components/InclusaoDeAlimentacaoDaCei/TabelaFaixasCEI.jsx
Labels: bug

#2026 HOM - Atualizada até 11/11 às 14:40
  src/components/AlteracaoDeCardapioCEMEI/Relatorio/componentes/ModalEscolaCancela.jsx
  src/components/AlteracaoDeCardapioCEMEI/Relatorio/index.jsx
  src/components/AlteracaoDeCardapioCEMEI/Relatorio/style.scss
  src/components/AlteracaoDeCardapioCEMEI/helpers.js
  src/components/AlteracaoDeCardapioCEMEI/style.scss
  src/components/screens/PreRecebimento/CadastroCronograma/index.jsx
  src/components/screens/PreRecebimento/CronogramaEntrega/styles.scss
  src/components/screens/helper.js
  src/configs/RoutesConfig.js
  src/configs/constants.js
  src/configs/helper.js
  src/pages/AlteracaoDeCardapioCEMEIRelatorios/index.jsx
  src/services/alteracaoDeCardapio/escola.service.js
Labels: feature

#2029 Fix: minimo e maximo para input number, breadcrumb inclusao cemei
  src/components/InclusaoDeAlimentacaoDaCei/TabelaFaixasCEI.jsx
  src/pages/AlteracaoDeCardapioCEMEIRelatorios/index.jsx
Labels: bug

#2030 HOM - Atualizado até 14/11 às 11:00
  src/components/InclusaoDeAlimentacaoDaCei/TabelaFaixasCEI.jsx
  src/pages/AlteracaoDeCardapioCEMEIRelatorios/index.jsx
Labels: bug

#2031 Fix: page helper para todos perfis, componentes para diferenciar tipo de usuário
  src/configs/helper.js
  src/pages/AlteracaoDeCardapioCEMEIRelatorios/index.jsx
Labels: bug

#2033 HOM - Atualizado até 16/11 às 12:15
  src/configs/helper.js
  src/pages/AlteracaoDeCardapioCEMEIRelatorios/index.jsx
Labels: bug

#2052 Fix: criar método helper, corrigir cor do componente
  src/components/InclusaoDeAlimentacao/Relatorio/componentes/InclusoesCEI.jsx
  src/components/InclusaoDeAlimentacao/Relatorio/componentes/helper.js
  src/components/InclusaoDeAlimentacaoDaCei/Container.jsx
  src/pages/Escola/InclusaoDeAlimentacaoCEIPage.jsx
Labels: bug

#2054 Hom atualizado 18/11 as 09:00h
  src/components/InclusaoDeAlimentacao/Relatorio/componentes/InclusoesCEI.jsx
  src/components/InclusaoDeAlimentacao/Relatorio/componentes/helper.js
  src/components/InclusaoDeAlimentacaoDaCei/Container.jsx
  src/pages/Escola/InclusaoDeAlimentacaoCEIPage.jsx
Labels: bug

#2055 Fix: nome da props no modal de cancelamento
  src/components/AlteracaoDeCardapioCEMEI/Relatorio/componentes/ModalEscolaCancela.jsx
Labels: bug

#2085 Feature/79479 ga dt popular matriculados no dia
  src/components/AlteracaoDeCardapio/CEI/helper.js
  src/components/AlteracaoDeCardapioCEMEI/componentes/TabelaFaixasCEMEI.jsx
  src/components/AlteracaoDeCardapioCEMEI/helpers.js
  src/components/InclusaoDeAlimentacaoDaCei/TabelaFaixasCEI.jsx
  src/components/InclusaoDeAlimentacaoDaCei/helper.js
  src/components/Shareable/TabelaQuantidadePorFaixaEtaria/index.jsx
  src/components/SolicitacaoDeKitLanche/Container/base.jsx
  src/components/SolicitacaoDeKitLanche/Container/helper.js
  src/components/SolicitacaoKitLancheCEMEI/componentes/index.jsx
Labels: feature
