Repository prefeiturasp/SME-Terceirizadas-Frontend, pull requests merged in 2022-06, with the labels that each got.

#1438 Fix/60507-GA-alterar-entidade-que-realizou-cancelamento-da-solicitação
  src/components/AlteracaoDeCardapio/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/InclusaoDeAlimentacao/Escola/Relatorio/index.jsx
  src/components/InclusaoDeAlimentacao/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/InversaoDeDiaDeCardapio/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/Shareable/FluxoDeStatus/index.jsx
  src/components/Shareable/ModalCancelarSolicitacao_/index.jsx
  src/components/SolicitacaoDeKitLanche/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/SolicitacaoUnificada/Relatorio/componentes/CorpoRelatorio.jsx
Labels: bug

#1439 Hom - Atualizado até 01/06/22 as 09:15
  src/components/AlteracaoDeCardapio/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/InclusaoDeAlimentacao/Escola/Relatorio/index.jsx
  src/components/InclusaoDeAlimentacao/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/InversaoDeDiaDeCardapio/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/Shareable/FluxoDeStatus/index.jsx
  src/components/Shareable/ModalCancelarSolicitacao_/index.jsx
  src/components/SolicitacaoDeKitLanche/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/SolicitacaoUnificada/Relatorio/componentes/CorpoRelatorio.jsx
Labels: bug

#1443 Feature/65442-GA-inclusão-alimentação-retirar-campo-obs-para-sol-não-contínua
  src/components/InclusaoDeAlimentacao/Relatorio/componentes/CorpoRelatorio.jsx
Labels: feature

#1444 Hom - Atualizado até 01/06/22 as 17:10
  src/components/InclusaoDeAlimentacao/Relatorio/componentes/CorpoRelatorio.jsx
Labels: feature

#1453 Feature/58665-GA-alteração-solic-inv-cardápio-não-encontra-cardápio
  src/components/InversaoDeDiaDeCardapio/Rascunhos.jsx
  src/components/InversaoDeDiaDeCardapio/Relatorio/componentes/CorpoRelatorio.jsx
  src/reducers/inversaoDeDiaDeCardapio.reducer.js
Labels: feature

#1454 Hom - Atualizado até 06/06/22 as 19:15
  src/components/InversaoDeDiaDeCardapio/Rascunhos.jsx
  src/components/InversaoDeDiaDeCardapio/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/screens/Logistica/ConferirEntrega/components/ListagemGuias/index.js
  src/reducers/inversaoDeDiaDeCardapio.reducer.js
Labels: bug, feature

#1456 Feature/62430 ga solicitacao kit lanche unificado
  src/components/Shareable/Botao/constants.js
  src/components/Shareable/Botao/index.jsx
  src/components/Shareable/DatePicker/index.jsx
  src/components/SolicitacaoUnificada/Container.jsx
  src/components/SolicitacaoUnificada/Rascunhos.jsx
  src/components/SolicitacaoUnificada/helper.js
  src/components/SolicitacaoUnificada/index.jsx
  src/components/SolicitacaoUnificada/style.scss
Labels: feature, refactoring

#1469 Feature/65382-GA-limitar-período-merenda-seca-em-5-dias-úteis
  src/components/AlteracaoDeCardapio/index.jsx
  src/reducers/alteracaoCardapioReducer.js
  src/services/diasUteis.service.js
Labels: bug, feature

#1470 Hom - Atualizado até 10/06/22 as 11:35
  src/components/AlteracaoDeCardapio/index.jsx
  src/reducers/alteracaoCardapioReducer.js
  src/services/diasUteis.service.js
Labels: bug, feature

#1471 Fix/65384-PeD-visualização-errada-da-tela-para-reenvio-de-homologação
  src/components/screens/DashboardGestaoProduto/helper.js
Labels: bug

#1472 Hom - Atualizado até 10/06/22 as 13:55
  src/components/screens/DashboardGestaoProduto/helper.js
Labels: bug

#1481 Hom - Atualizado até 13/06/22 as 15:50
  src/components/AlteracaoDeCardapio/CEI/AlteracaoCardapio.jsx
  src/components/AlteracaoDeCardapio/index.jsx
  src/components/InclusaoDeAlimentacao/index.jsx
  src/components/InversaoDeDiaDeCardapio/index.jsx
  src/components/SolicitacaoDeKitLanche/Container/base.jsx
  src/components/SolicitacaoUnificada/index.jsx
Labels: bug

#1492 Fix/66483-DE-problema-no-campo-pesquisar-no-dashboard-das-dietas-especiais
  src/components/Shareable/CardBody.jsx
  src/components/Shareable/style.scss
  src/components/screens/DashBoardDietaEspecial/index.jsx
Labels: bug

#1493 Hom - Atualizado até 14/06/22 as 20:20
  src/components/Shareable/CardBody.jsx
  src/components/Shareable/style.scss
  src/components/screens/DashBoardDietaEspecial/index.jsx
Labels: bug

#1496 Fix: apenas terc_total e contadores
  src/components/SolicitacaoUnificada/Container.jsx
  src/components/SolicitacaoUnificada/index.jsx
Labels: bug

#1500 Hom - Atualizado até 20/06/22 as 14:15
  src/components/screens/DietaEspecial/Escola/componentes/SolicitacaoVigente/index.jsx
Labels: bug

#1501 Feature/59034-DE-incluir-foto-na-tela-consulta-dieta-especial
  src/components/screens/DietaEspecial/AtivasInativasPorAluno/components/TabelaResultados/index.jsx
  src/components/screens/DietaEspecial/AtivasInativasPorAluno/components/TabelaResultados/styles.scss
  src/components/screens/DietaEspecial/AtivasInativasPorAluno/index.jsx
Labels: feature

#1504 Hom - Atualizado até 23/06/22 as 15:15
  src/components/screens/DietaEspecial/AtivasInativasPorAluno/components/TabelaResultados/index.jsx
  src/components/screens/DietaEspecial/AtivasInativasPorAluno/components/TabelaResultados/styles.scss
  src/components/screens/DietaEspecial/AtivasInativasPorAluno/index.jsx
Labels: feature

#1505 Feature/59034-DE-incluir-foto-na-tela-consulta-dieta-especial
  src/components/screens/DietaEspecial/AtivasInativasPorAluno/components/FormFiltros/index.jsx
  src/components/screens/DietaEspecial/AtivasInativasPorAluno/components/FormFiltros/styles.scss
  src/components/screens/DietaEspecial/AtivasInativasPorAluno/components/TabelaResultados/index.jsx
Labels: feature

#1513 Fix/66488-DE-exibir-todos-campos-das-dietas-quando-navegado-a-partir-do-menu-lateral-consulta
  src/components/screens/DietaEspecial/Relatorio/componentes/CorpoRelatorio/index.jsx
Labels: bug

#1515 Feature/59030-DE-incluir-foto-na-tela-dieta-especial-autorizada
  src/components/screens/DietaEspecial/Relatorio/componentes/CorpoRelatorio/InformacoesAluno.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/CorpoRelatorio/styles.scss
Labels: feature

#1516 Hom - Atualizado até 29/06/22 as 12:45
  src/components/screens/DietaEspecial/Relatorio/componentes/CorpoRelatorio/InformacoesAluno.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/CorpoRelatorio/styles.scss
Labels: feature

#1517 Feature/59030-DE-ajustar-loader-da-imagem
  src/components/screens/DietaEspecial/Relatorio/componentes/CorpoRelatorio/InformacoesAluno.jsx
Labels: feature

#1518 Hom - Atualizado até 29/06/22 as 14:00
  src/components/screens/DietaEspecial/Relatorio/componentes/CorpoRelatorio/InformacoesAluno.jsx
Labels: feature

#1523 Hom - Atualizado até 30/06/22 as 09:10
  src/helpers/corrigeDadosDoDashboard.js
Labels: bug

#1528 Hom - Atualizado até 30/06/22 as 17:10
  src/components/screens/DietaEspecial/AtivasInativasPorAluno/components/TabelaResultados/index.jsx
Labels: feature
