Repository prefeiturasp/SME-Terceirizadas-Frontend, pull requests merged in 2022-12, with the labels that each got.

#2118 Feature/78920 resultado da grid solicitacoes ga
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/Filtros/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/TabelaResultado/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/constants.js
  src/components/screens/Relatorios/SolicitacoesAlimentacao/index.jsx
  src/pages/Relatorios/RelatorioSolicitacoesAlimentacaoPage.jsx
  src/services/relatorios.service.js
Labels: feature

#2119 Hom atualizado 01/12 as 16:45h
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/Filtros/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/TabelaResultado/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/constants.js
  src/components/screens/Relatorios/SolicitacoesAlimentacao/index.jsx
  src/pages/Relatorios/RelatorioSolicitacoesAlimentacaoPage.jsx
  src/services/relatorios.service.js
Labels: feature

#2123 Fix: filtro terceirizada
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/Filtros/index.jsx
Labels: bug

#2124 Hom atualizado 01/12 as 18h20
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/Filtros/index.jsx
Labels: bug

#2125 Feature/70415-MI-tela-lançamento-de-dietas
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalObservacaoDiaria/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/styles.scss
  src/helpers/fieldValidators.js
  src/services/medicaoInicial/periodoLancamentoMedicao.service.js
Labels: enhancement, feature

#2126 Hom - Atualizado até 01/12/22 as 21:15
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalObservacaoDiaria/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/styles.scss
  src/helpers/fieldValidators.js
  src/services/medicaoInicial/periodoLancamentoMedicao.service.js
Labels: enhancement, feature

#2137 Hom - Atualizado até 06/12/22 as 16:10
  src/components/InclusaoDeAlimentacaoCEMEI/Relatorio/componentes/CorpoRelatorio/index.jsx
  src/services/relatorios.js
Labels: enhancement, feature

#2143 Feature/79708-GA-kit-lanche-e-alteração-alimentação-cemei-ajustes-faixas-etárias
  src/components/AlteracaoDeCardapioCEMEI/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/AlteracaoDeCardapioCEMEI/componentes/TabelaFaixasCEMEI.jsx
  src/components/AlteracaoDeCardapioCEMEI/helpers.js
  src/components/AlteracaoDeCardapioCEMEI/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/components/CorpoRelatorio/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/componentes/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/index.jsx
Labels: enhancement, feature

#2148 Hom - Atualizado até 08/12/22 as 12:50
  src/components/AlteracaoDeCardapioCEMEI/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/AlteracaoDeCardapioCEMEI/componentes/TabelaFaixasCEMEI.jsx
  src/components/AlteracaoDeCardapioCEMEI/helpers.js
  src/components/AlteracaoDeCardapioCEMEI/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/components/CorpoRelatorio/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/componentes/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/index.jsx
Labels: enhancement, feature

#2144 Feature/79713-GA-alterar-nomenclatura-solicitação-de-alteração-cei-no-dashboard
  src/components/screens/helper.js
  src/helpers/corrigeDadosDoDashboard.js
Labels: enhancement, feature

#2152 Hom - Atualizado até 09/12/22 as 09:55
  src/components/screens/helper.js
  src/helpers/corrigeDadosDoDashboard.js
Labels: enhancement, feature

#2151 Feature/79037 expansor para relatorios inclusao
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/Filtros/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoCEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoCEMEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoContinuaBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/TabelaResultado/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/constants.js
  src/components/screens/Relatorios/SolicitacoesAlimentacao/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/style.scss
  src/services/relatorios.service.js
Labels: feature

#2160 Hom - atualizado até 12/12 as 08:40
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/Filtros/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoCEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoCEMEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoContinuaBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/TabelaResultado/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/constants.js
  src/components/screens/Relatorios/SolicitacoesAlimentacao/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/style.scss
  src/services/relatorios.service.js
Labels: feature

#2159 Feature/80347 expansor para relatorios alteracao
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/AlteracaoBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/AlteracaoCEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/AlteracaoCEMEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/TabelaResultado/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/style.scss
Labels: feature

#2161 Hom - atualizado até 12/12 as 08:50
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/AlteracaoBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/AlteracaoCEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/AlteracaoCEMEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/TabelaResultado/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/style.scss
Labels: feature

#2162 Bugfix/solicitacoes alimentacao resultado com numero de alunos
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoCEIBody/index.jsx
Labels: bug

#2163 Hom - atualizado até 12/12 as 11:20
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoCEIBody/index.jsx
Labels: bug

#2170 Bugfix/ga exibicao alimentos substituidos relatorios
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/AlteracaoCEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/AlteracaoCEMEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoCEMEIBody/index.jsx
Labels: bug

#2171 Hom - Atualizado até 13/12/22 as 11:50
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/AlteracaoCEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/AlteracaoCEMEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoCEMEIBody/index.jsx
Labels: bug

#2172 Feature/72154-DE-alterar-texto-modal-cancelamento-dieta-especial
  src/components/screens/DietaEspecial/CancelamentoDieta/components/FormFiltros/index.jsx
  src/components/screens/DietaEspecial/CancelamentoDieta/components/FormFiltros/styles.scss
  src/components/screens/DietaEspecial/CancelamentoDieta/components/ModalCancelamento/index.jsx
Labels: enhancement

#2173 Hom - Atualizado até 13/12/22 as 13:05
  src/components/Shareable/Toast/dialogs.js
  src/components/screens/DietaEspecial/CancelamentoDieta/components/FormFiltros/index.jsx
  src/components/screens/DietaEspecial/CancelamentoDieta/components/FormFiltros/styles.scss
  src/components/screens/DietaEspecial/CancelamentoDieta/components/ModalCancelamento/index.jsx
Labels: enhancement

#2174 Bugfix/ga tabela inclusao cemei e status recebidas
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/AlteracaoBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/AlteracaoCEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/AlteracaoCEMEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoCEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoCEMEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoContinuaBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/TabelaResultado/index.jsx
Labels: bug

#2175 Hom - Atualizado até 13/12/22 as 14:15
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/AlteracaoBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/AlteracaoCEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/AlteracaoCEMEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoCEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoCEMEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoContinuaBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/TabelaResultado/index.jsx
Labels: bug

#2181 Feature/80349 relatorio solicitacao kit lanche
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/KitLancheAvulsaBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/KitLancheAvulsaCEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/KitLancheAvulsaCEMEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/KitLancheUnificadoBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/TabelaResultado/index.jsx
Labels: feature

#2182 Hom atualizado 14/12 as 16h50
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/KitLancheAvulsaBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/KitLancheAvulsaCEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/KitLancheAvulsaCEMEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/KitLancheUnificadoBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/TabelaResultado/index.jsx
Labels: feature

#2185 Fix/76465-MI-corrigir-atrasos-nas-validações-das-regras-nos-inputs
  src/components/Shareable/Input/InputValueMedicao/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/styles.scss
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalObservacaoDiaria/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
  src/helpers/fieldValidators.js
Labels: bug, enhancement

#2186 Hom - Atualizado até 15/12/22 as 12:10
  src/components/Shareable/Input/InputValueMedicao/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/styles.scss
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalObservacaoDiaria/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
  src/helpers/fieldValidators.js
Labels: bug, enhancement

#2187 Feature/80351 ga relatorio detalhado suspensao e inversao
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InversaoCardapioBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/KitLancheUnificadoBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/SuspensaoAlimentacaoBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/SuspensaoAlimentacaoCEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/TabelaResultado/index.jsx
Labels: feature

#2188 Fix: validar valores antes de processar dados
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/KitLancheAvulsaCEMEIBody/index.jsx
Labels: bug

#2189 Hom - Atualizado até 15/12/22 as 13:40
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InversaoCardapioBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/KitLancheAvulsaCEMEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/KitLancheUnificadoBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/SuspensaoAlimentacaoBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/SuspensaoAlimentacaoCEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/TabelaResultado/index.jsx
Labels: feature

#2190 Fix: solicitação kit lanche cemei
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/KitLancheAvulsaCEMEIBody/index.jsx
Labels: bug

#2193 Fix: mudar campos de data inversão
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InversaoCardapioBody/index.jsx
Labels: bug

#2191 Hom - Atualizado até 15/12/22 as 14:20
  src/components/AlteracaoDeCardapio/CEI/index.jsx
  src/components/AlteracaoDeCardapio/index.jsx
  src/components/AlteracaoDeCardapioCEMEI/index.jsx
  src/components/InclusaoDeAlimentacao/Escola/Formulario/componentes/InclusaoContinua/index.jsx
  src/components/InclusaoDeAlimentacao/Escola/Formulario/componentes/InclusaoNormal/index.jsx
  src/components/InclusaoDeAlimentacaoDaCei/index.jsx
  src/components/InversaoDeDiaDeCardapio/index.jsx
  src/components/SolicitacaoDeKitLanche/Container/base.jsx
  src/components/SolicitacaoKitLancheCEMEI/index.jsx
  src/components/SolicitacaoUnificada/index.jsx
  src/components/SuspensaoAlimentacaoDeCEI/Index.jsx
  src/components/SuspensaoDeAlimentacao/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InversaoCardapioBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/KitLancheAvulsaCEMEIBody/index.jsx
  src/constants/shared.js
  src/helpers/utilities.js
Labels: bug

#2197 Feature/81635-GA-alterações-sol.-lanche-emerg.cemei-ceu-cemei
  src/components/AlteracaoDeCardapioCEMEI/componentes/ModalLancheEmergencial.jsx
  src/components/AlteracaoDeCardapioCEMEI/index.jsx
Labels: enhancement, feature

#2198 Hom - Atualizado até 15/12/22 as 17:40
  src/components/AlteracaoDeCardapioCEMEI/componentes/ModalLancheEmergencial.jsx
  src/components/AlteracaoDeCardapioCEMEI/index.jsx
  src/components/Shareable/FinalForm/MultiSelect/index.jsx
  src/components/Shareable/Sidebar/SidebarContent.jsx
  src/components/Shareable/Sidebar/menus/MenuPreRecebimento.jsx
  src/components/screens/PreRecebimento/CronogramaEntrega/components/Filtros/index.jsx
  src/components/screens/PreRecebimento/CronogramaEntrega/components/Filtros/style.scss
  src/components/screens/PreRecebimento/CronogramaEntrega/components/ListagemCronogramas/index.js
  src/components/screens/PreRecebimento/CronogramaEntrega/index.jsx
  src/configs/RoutesConfig.js
  src/constants/shared.js
  src/helpers/utilities.js
Labels: enhancement, feature

#2199 Feature: incluir quebra de linha
  src/components/AlteracaoDeCardapioCEMEI/componentes/ModalLancheEmergencial.jsx
Labels: enhancement

#2200 Hom - Atualizado até 15/12/22 as 18:10
  src/components/AlteracaoDeCardapioCEMEI/componentes/ModalLancheEmergencial.jsx
Labels: enhancement

#2203 Feature/77969-DE-alterar-endpoint-escolas-para-usuário-dre-tela-consulta-dieta-aluno
  src/helpers/dietaEspecial.js
Labels: enhancement

#2204 Hom - Atualizado até 16/12/22 as 11:35
  src/helpers/dietaEspecial.js
Labels: enhancement

#2229 Feature/78928 pdf relatorio solicitacoes ga inclusoes
  src/components/screens/Relatorios/SolicitacoesAlimentacao/index.jsx
  src/pages/Relatorios/RelatorioSolicitacoesAlimentacaoPage.jsx
  src/services/relatorios.service.js
Labels: feature

#2239 Hom atualizado 27/12 as 08h50
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
  src/components/screens/Relatorios/SolicitacoesAlimentacao/index.jsx
  src/pages/Relatorios/RelatorioSolicitacoesAlimentacaoPage.jsx
  src/services/relatorios.service.js
Labels: feature

#2238 Feature/76113-DE-usuários-com-solicitações-dietas-recebidas-abertas-tempo-real
  src/components/Shareable/CardStatusDeSolicitacao/CardStatusDeSolicitacao.jsx
  src/components/Shareable/CardStatusDeSolicitacao/style.scss
  src/components/screens/DietaEspecial/Relatorio/index.jsx
  src/components/screens/DietaEspecial/Relatorio/style.scss
  src/services/dietaEspecial.service.js
  src/services/websocket.js
Labels: feature

#2241 Hom - Atualizado até 28/12/22 as 10:20
  src/components/Shareable/CardStatusDeSolicitacao/CardStatusDeSolicitacao.jsx
  src/components/Shareable/CardStatusDeSolicitacao/style.scss
  src/components/screens/DietaEspecial/Relatorio/index.jsx
  src/components/screens/DietaEspecial/Relatorio/style.scss
  src/components/screens/Logistica/ConferenciaDeGuiaComOcorrencia/index.jsx
  src/components/screens/Logistica/ConferenciaDeGuiaResumoFinal/index.jsx
  src/components/screens/Logistica/ReposicaoDeGuia/index.jsx
  src/services/dietaEspecial.service.js
  src/services/websocket.js
Labels: feature

#2250 Feature/76113-DE-usuários-com-solicitações-dietas-recebidas-abertas-tempo-real
  src/components/Shareable/CardStatusDeSolicitacao/CardStatusDeSolicitacao.jsx
  src/components/screens/DietaEspecial/Relatorio/index.jsx
Labels: enhancement

#2253 Fix/GA-correções-relatórios-solicitações-alimentações
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/AlteracaoBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/SuspensaoAlimentacaoBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/SuspensaoAlimentacaoCEIBody/index.jsx
Labels: bug

#2254 Hom atualizado 30/12 as 17h30
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/AlteracaoBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/SuspensaoAlimentacaoBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/SuspensaoAlimentacaoCEIBody/index.jsx
Labels: bug

#2256 Fix/GA-correções-relatórios-solicitações-alimentações
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/SuspensaoAlimentacaoBody/index.jsx
Labels: bug
