Repository prefeiturasp/SME-Terceirizadas-Frontend, pull requests merged in 2022-08, with the labels that each got.

#1632 Feature/69346-PeD-seleção-de-editais
  src/components/Shareable/Select/index.jsx
  src/components/screens/Produto/Homologacao/components/ModelVincularEditais/index.jsx
  src/components/screens/Produto/Homologacao/index.jsx
  src/services/produto.service.js
Labels: feature

#1633 Hom - Atualizado até 01/08/22 as 09:00
  src/components/Shareable/Select/index.jsx
  src/components/screens/Produto/Homologacao/components/ModelVincularEditais/index.jsx
  src/components/screens/Produto/Homologacao/index.jsx
  src/services/produto.service.js
Labels: feature

#1635 Hom - Atualizado até 01/08/22 as 11:10
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/Tabela/index.jsx
Labels: bug

#1636 Feature/69346-PeD-seleção-de-editais
  src/components/screens/Produto/Homologacao/components/ModelVincularEditais/index.jsx
Labels: feature

#1638 Feature/69543 modal vincular editais
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/Filtros/index.jsx
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/ModalVincularProdutosEditais/helper.js
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/ModalVincularProdutosEditais/index.jsx
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/ModalVincularProdutosEditais/style.scss
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/Tabela/index.jsx
  src/components/screens/Cadastros/VincularProdutosEditais/index.jsx
  src/services/produto.service.js
Labels: feature

#1639 Hom - Atualizado até 04/08 as 14:25
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/Filtros/index.jsx
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/ModalVincularProdutosEditais/helper.js
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/ModalVincularProdutosEditais/index.jsx
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/ModalVincularProdutosEditais/style.scss
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/Tabela/index.jsx
  src/components/screens/Cadastros/VincularProdutosEditais/index.jsx
  src/services/produto.service.js
Labels: feature

#1640 Fix: problemas de seleção dos valores no componente
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/ModalVincularProdutosEditais/index.jsx
Labels: bug

#1641 Hom - Atualizado até 04/08 as 17:30
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/ModalVincularProdutosEditais/index.jsx
Labels: bug

#1642 Fix: fechar modal, titulo do botao e onChange
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/Filtros/index.jsx
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/ModalVincularProdutosEditais/index.jsx
Labels: bug

#1643 Hom - Atualizado até 04/08 as 18:30
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/Filtros/index.jsx
  src/components/screens/Cadastros/VincularProdutosEditais/componentes/ModalVincularProdutosEditais/index.jsx
Labels: bug

#1652 Feature: formulário deve enviar lista de vinculos para atualizar tipos alimentacao
  src/components/screens/Cadastros/CadastroTipoAlimentacao/index.jsx
  src/components/screens/Cadastros/CadastroTipoAlimentacao/style.scss
  src/services/cadastroTipoAlimentacao.service.js
Labels: feature

#1658 Feature: seta para os dois lados
  src/components/InversaoDeDiaDeCardapio/index.jsx
Labels: feature

#1659 HOM - Atualizado até 11/08
  src/components/InversaoDeDiaDeCardapio/index.jsx
  src/components/screens/Cadastros/CadastroSobremesaDoce/componentes/ModalEditar/style.scss
Labels: feature

#1667 Feature: CCI, CEU CEI, CEI, devem listar alimentos de acordo com o motivo selecionado
  src/components/AlteracaoDeCardapio/CEI/AlteracaoCardapio.jsx
  src/components/AlteracaoDeCardapio/index.jsx
Labels: feature

#1661 Feature/55022 melhoria seletor motivo parte 1
  src/components/AlteracaoDeCardapio/CEI/AlteracaoCardapio.jsx
  src/components/AlteracaoDeCardapio/index.jsx
  src/components/InclusaoDeAlimentacao/Escola/Formulario/componentes/Container.jsx
  src/components/InclusaoDeAlimentacao/helper.js
Labels: feature

#1666 Feature/46673-MI-lançamento-medição-inicial-página-inicial-escola
  src/components/Shareable/Botao/constants.js
  src/components/Shareable/FluxoDeStatus/helper.js
  src/components/Shareable/FluxoDeStatus/index.jsx
  src/components/Shareable/Input/InputFile/index.jsx
  src/components/Shareable/Sidebar/menus/MenuLancamentoInicial.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/FluxoDeStatusMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/InformacoesEscola/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/InformacoesMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/TabelaLancamento/DietaConvencionalFrequencia.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/styles.scss
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/helpers.js
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/ModalFinalizarMedicao/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/styles.scss
  src/configs/RoutesConfig.js
  src/helpers/utilities.js
  src/pages/LancamentoInicial/LancamentoMedicaoInicialPage.jsx
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: enhancement, feature

#1668 Hom - Atualizado até 15/08/22 as 10:55
  src/components/AlteracaoDeCardapio/CEI/AlteracaoCardapio.jsx
  src/components/AlteracaoDeCardapio/index.jsx
  src/components/InclusaoDeAlimentacao/Escola/Formulario/componentes/Container.jsx
  src/components/InclusaoDeAlimentacao/helper.js
  src/components/Shareable/Botao/constants.js
  src/components/Shareable/FluxoDeStatus/helper.js
  src/components/Shareable/FluxoDeStatus/index.jsx
  src/components/Shareable/Input/InputFile/index.jsx
  src/components/Shareable/Sidebar/menus/MenuLancamentoInicial.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/FluxoDeStatusMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/InformacoesEscola/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/InformacoesMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/TabelaLancamento/DietaConvencionalFrequencia.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/styles.scss
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/helpers.js
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/ModalFinalizarMedicao/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/styles.scss
  src/configs/RoutesConfig.js
  src/helpers/utilities.js
  src/pages/LancamentoInicial/LancamentoMedicaoInicialPage.jsx
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: enhancement, feature

#1671 Feature/70178-MI-atalho-para-tela-inicial
  src/components/Shareable/Icones/IconeMedicaoInicial.jsx
  src/components/screens/PainelInicial/index.jsx
Labels: feature

#1672 Hom - Atualizado até 15/08/22 as 12:55
  src/components/Shareable/Icones/IconeMedicaoInicial.jsx
  src/components/screens/PainelInicial/index.jsx
Labels: feature

#1674 Fix/70183-PeD-ajuste-motivo-solicitação-de-correção-do-produto
  src/components/Shareable/MotivoDaCorrecaoDeHomologacao/index.js
Labels: bug

#1675 Hom - Atualizado até 15/08/22 as 18:10
  src/components/Shareable/MotivoDaCorrecaoDeHomologacao/index.js
  src/components/Shareable/TabelaQuantidadePorFaixaEtaria/index.jsx
Labels: bug

#1677 Feature: remover utilização do campo homologacoes
  src/components/screens/Produto/BuscaAvancada/components/RelatorioProduto/helpers.jsx
  src/components/screens/Produto/BuscaAvancada/components/RelatorioProduto/index.jsx
Labels: feature

#1676 Feature/68881-PeD-validação-de-log-análise-sensorial
  src/components/screens/Produto/Homologacao/index.jsx
Labels: feature

#1678 Hom - Atualizado até 16/08/22 as 09:40
  src/components/screens/Produto/BuscaAvancada/components/RelatorioProduto/helpers.jsx
  src/components/screens/Produto/BuscaAvancada/components/RelatorioProduto/index.jsx
  src/components/screens/Produto/Homologacao/index.jsx
Labels: bug, feature

#1679 Feature/ajustes-review-59
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/InformacoesMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/styles.scss
Labels: feature

#1681 Feature/55022 lista de substitutos escola comum
  src/components/AlteracaoDeCardapio/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/AlteracaoDeCardapio/index.jsx
  src/components/AlteracaoDeCardapio/validacao.js
  src/reducers/alteracaoCardapioReducer.js
Labels: feature

#1682 Hom - Atualizado até 17/08/22 as 12:15
  src/components/AlteracaoDeCardapio/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/AlteracaoDeCardapio/index.jsx
  src/components/AlteracaoDeCardapio/validacao.js
  src/reducers/alteracaoCardapioReducer.js
Labels: feature

#1683 Feature/ajustes-review-59-pt2
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
Labels: feature

#1684 Hom - Atualizado até 17/08/22 as 14:25
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
Labels: feature

#1685 Feature: desabilitar quando periodo nao estiver checado
  src/components/AlteracaoDeCardapio/CEI/AlteracaoCardapio.jsx
  src/components/AlteracaoDeCardapio/CEI/style.scss
Labels: feature

#1686 Hom - Atualizado até 18/08/22 as 11:50
  src/components/AlteracaoDeCardapio/CEI/AlteracaoCardapio.jsx
  src/components/AlteracaoDeCardapio/CEI/style.scss
Labels: feature

#1687 Fix: corrigir seletor quando nao tiver motivos selecionados
  src/components/AlteracaoDeCardapio/index.jsx
  src/helpers/utilities.js
Labels: feature

#1688 Hom - Atualizado até 18/08/22 as 12:50
  src/components/AlteracaoDeCardapio/index.jsx
  src/helpers/utilities.js
Labels: feature

#1695 Feature/71524-PeD-permitir-terceirizada-user-modificar-nome-produto-status-correção
  src/components/screens/Produto/AtualizacaoProdutoForm/components/WizardFormPrimeiraPagina.jsx
Labels: feature

#1696 Hom - Atualizado até 19/08/22 as 12:25
  src/components/screens/Produto/AtualizacaoProdutoForm/components/WizardFormPrimeiraPagina.jsx
Labels: feature

#1699 Feature: adicionar filtros para editais e tipo produto
  src/components/Shareable/FormBuscaProduto/index.js
  src/components/Shareable/FormBuscaProduto/style.scss
  src/services/produto.service.js
Labels: feature

#1700 Hom - Atualizado até 23/08/22
  src/components/Shareable/FormBuscaProduto/index.js
  src/components/Shareable/FormBuscaProduto/style.scss
  src/services/produto.service.js
Labels: feature

#1703 salva, altera e exibe editais por protocolo padrão
  src/components/screens/DietaEspecial/CadastroProtocoloPadraoDietaEsp/index.jsx
  src/components/screens/DietaEspecial/ConsultaProtocoloPadraoDieta/componentes/Filtros/index.jsx
  src/components/screens/DietaEspecial/ConsultaProtocoloPadraoDieta/componentes/Tabela/index.jsx
  src/components/screens/DietaEspecial/ConsultaProtocoloPadraoDieta/index.jsx
  src/components/screens/DietaEspecial/ConsultaProtocoloPadraoDieta/style.scss
  src/components/screens/Produto/Reclamacao/components/ModalReclamacaoProduto/index.jsx
Labels: feature

#1707 Feature/71710 impressao relatorio
  src/components/Shareable/FormBuscaProduto/index.js
  src/components/screens/RelatorioProdutosHomologados/index.js
Labels: feature

#1708 Hom atualizado 31/08 as 10:00
  src/components/Shareable/FormBuscaProduto/index.js
  src/components/screens/RelatorioProdutosHomologados/index.js
Labels: feature
