Repository prefeiturasp/SME-Terceirizadas-Frontend, pull requests merged in 2023-07, with the labels that each got.

#3064 Feature/96684 medicao inicial funcionalidade tecla enter
  src/components/Shareable/Input/InputValueMedicao/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: feature

#3067 Feature/96924-PeD-inserir-nome-dre-tela-reclamação-de-produto
  src/components/screens/Produto/Reclamacao/components/Reclamacao/index.jsx
Labels: enhancement, feature

#3068 Hom Atualizado 04/07 as 14h05
  src/components/screens/Produto/Reclamacao/components/Reclamacao/index.jsx
Labels: enhancement, feature

#3080 Feature/96903-GA-alteração-alimentação-RPL-e-LPR-somente-em-dias-úteis
  src/components/AlteracaoDeCardapio/CEI/Container.jsx
  src/components/AlteracaoDeCardapio/CEI/index.jsx
  src/components/AlteracaoDeCardapio/Container.jsx
  src/components/AlteracaoDeCardapio/index.jsx
  src/components/AlteracaoDeCardapioCEMEI/componentes/Container.jsx
  src/components/AlteracaoDeCardapioCEMEI/index.jsx
  src/components/Shareable/DatePicker/index.jsx
  src/helpers/fieldValidators.js
  src/services/diasUteis.service.js
Labels: enhancement, feature

#3081 Hom Atualizado 06/07 as 16h30
  src/components/AlteracaoDeCardapio/CEI/Container.jsx
  src/components/AlteracaoDeCardapio/CEI/index.jsx
  src/components/AlteracaoDeCardapio/Container.jsx
  src/components/AlteracaoDeCardapio/index.jsx
  src/components/AlteracaoDeCardapioCEMEI/componentes/Container.jsx
  src/components/AlteracaoDeCardapioCEMEI/index.jsx
  src/components/Shareable/DatePicker/index.jsx
  src/helpers/fieldValidators.js
  src/services/diasUteis.service.js
Labels: enhancement, feature

#3079 Feature: Adicionar permissões nas rotas dos relatórios e permissão de exibição dos botões da SideBar
  src/components/Shareable/Sidebar/menus/MenuRelatorios.jsx
  src/configs/RoutesConfig.js
Labels: feature

#3085 HOM - Atualizado em 07/07 às 11:05h
  src/components/Shareable/Sidebar/menus/MenuRelatorios.jsx
  src/configs/RoutesConfig.js
Labels: feature

#3107 Feature/97573 justificativa codae ao autorizar
  src/components/AlteracaoDeCardapio/Relatorio/ModalAprovarSolicitacaoAlteracao.jsx
  src/components/AlteracaoDeCardapio/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/AlteracaoDeCardapio/Relatorio/index.jsx
  src/components/AlteracaoDeCardapioCEMEI/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/AlteracaoDeCardapioCEMEI/Relatorio/componentes/ModalAprovarSolicitacaoAlteracao.jsx
  src/components/AlteracaoDeCardapioCEMEI/Relatorio/index.jsx
  src/helpers/utilities.js
Labels: feature

#3109 HOM - Atualizado até 12/07 às 14:20h
  src/components/AlteracaoDeCardapio/Relatorio/ModalAprovarSolicitacaoAlteracao.jsx
  src/components/AlteracaoDeCardapio/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/AlteracaoDeCardapio/Relatorio/index.jsx
  src/components/AlteracaoDeCardapioCEMEI/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/AlteracaoDeCardapioCEMEI/Relatorio/componentes/ModalAprovarSolicitacaoAlteracao.jsx
  src/components/AlteracaoDeCardapioCEMEI/Relatorio/index.jsx
  src/helpers/utilities.js
Labels: feature

#3118 Feature/97570-GA-modal-observação-na-autorização-inclusão-alimentação-codae
  src/components/InclusaoDeAlimentacao/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/InclusaoDeAlimentacao/Relatorio/index.jsx
  src/components/InclusaoDeAlimentacaoCEMEI/Relatorio/componentes/CorpoRelatorio/index.jsx
  src/components/InclusaoDeAlimentacaoCEMEI/Relatorio/index.jsx
  src/components/Shareable/ModalCODAEAutoriza/index.jsx
  src/components/Shareable/RelatorioHistoricoQuestionamento/index.jsx
  src/pages/InclusaoDeAlimentacao/RelatorioPage.jsx
  src/pages/InclusaoDeAlimentacaoCEMEIRelatorios/index.jsx
  src/services/inclusaoDeAlimentacao/codae.service.js
Labels: enhancement, feature

#3119 Hom Atualizado 14/07 as 10h30
  src/components/InclusaoDeAlimentacao/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/InclusaoDeAlimentacao/Relatorio/index.jsx
  src/components/InclusaoDeAlimentacaoCEMEI/Relatorio/componentes/CorpoRelatorio/index.jsx
  src/components/InclusaoDeAlimentacaoCEMEI/Relatorio/index.jsx
  src/components/Shareable/ModalCODAEAutoriza/index.jsx
  src/components/Shareable/RelatorioHistoricoQuestionamento/index.jsx
  src/pages/InclusaoDeAlimentacao/RelatorioPage.jsx
  src/pages/InclusaoDeAlimentacaoCEMEIRelatorios/index.jsx
  src/services/inclusaoDeAlimentacao/codae.service.js
Labels: enhancement, feature

#3122 Feature/97570-GA-modal-observação-na-autorização-inclusão-alimentação-codae
  src/components/Shareable/ModalCODAEAutoriza/index.jsx
Labels: enhancement

#3123 Hom Atualizado 14/07 as 16h30
  src/components/Shareable/ModalCODAEAutoriza/index.jsx
Labels: enhancement

#3130 Feature/96624-MI-criar-tela-detalhamento-lançamento-medição-inicial
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/InformacoesMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/index.jsx
  src/configs/RoutesConfig.js
  src/configs/constants.js
  src/pages/LancamentoMedicaoInicial/DetalhamentoDoLancamentoPage.jsx
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: enhancement, feature

#3132 Feature/93436-MI-aprovação-medição-inicial-pela-codae
  src/components/Shareable/FluxoDeStatus/helper.js
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalEnviarParaCodaeECodaeAprovar/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/Ocorrencias/index.jsx
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: enhancement, feature

#3139 Feature/93459-MI-envio-solicitação-de-correção-pela-codae
  src/components/Shareable/FluxoDeStatus/helper.js
  src/components/Shareable/FluxoDeStatus/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/Ocorrencias/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/styles.scss
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: enhancement, feature

#3143 Hom Atualizado 21/07 as 17h15
  src/components/Shareable/FluxoDeStatus/helper.js
  src/components/Shareable/FluxoDeStatus/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/Ocorrencias/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/styles.scss
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: enhancement, feature

#3145 Feature: funcionalidade para permitir solicitar correção da medição com perfil CODAE
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalOcorrencia/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: feature

#3148 HOM - Atualizado em 24/07 às 15:40
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalOcorrencia/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: feature

#3151 Fix: validar se existe log
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
Labels: bug

#3157 Feature: permitir usuário CODAE solicitar correção de período da medição
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: feature

#3159 HOM - Atualizado em 25/07 às 17:00
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: feature

#3160 Feature/99125-MI-envio-correção-para-codae-visão-ue
  src/components/Shareable/FluxoDeStatus/helper.js
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: enhancement, feature

#3162 Hom Atualizado 25/07 as 18h15
  src/components/Shareable/FluxoDeStatus/helper.js
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: enhancement, feature

#3173 Feature: permitir usuario CODAE aprovar ocorrências da Medição Inicial
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalOcorrencia/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: feature

#3175 Feature/99127-MI-ocorrências-e-períodos-devolvidos-para-ajustes-pela-codae-visão-ue
  src/components/Shareable/ModalHistorico/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/ModalAtualizarOcorrencia/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/Ocorrencias/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalObservacaoDiaria/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: enhancement, feature

#3176 Hom Atualizado 28/07 as 19h00
  src/components/Shareable/ModalHistorico/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalOcorrencia/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/ModalAtualizarOcorrencia/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/Ocorrencias/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalObservacaoDiaria/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
  src/services/permissoes.service.js
Labels: enhancement, feature

#3183 HOM - Atualizado em 31/07/2023 às 14:00h
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
  src/services/relatorios.js
Labels: feature

#3184 Bugfix/container dos botoes e xlsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/services/relatorios.js
Labels: bug

#3185 HOM - Atualizado em 31/07/2023 às 18:00
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/services/relatorios.js
Labels: bug

#3186 Fix/ajustar-botao-atualizar-ocorrencias-visao-ue
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/Ocorrencias/index.jsx
Labels: enhancement

#3187 Hom Atualizado 31/07 as 19h00
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/Ocorrencias/index.jsx
Labels: enhancement

#3188 Fix: impresão dos documentos com perfil CODAE
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/services/relatorios.js
Labels: bug

#3189 HOM - Atualizado em 31/07/2023 às 19:20h
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/services/relatorios.js
Labels: bug
