Repository prefeiturasp/SME-Terceirizadas-Frontend, pull requests merged in 2023-06, with the labels that each got.

#2924 Feature: respeitar nova modelagem para ocorrências e responder questionamento com perfil UE
  src/components/Shareable/FluxoDeStatus/helper.js
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/style.scss
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/ModalAtualizarOcorrencia/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/Ocorrencias/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/index.jsx
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: feature

#2927 Feature: close modal
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/ModalAtualizarOcorrencia/index.jsx
Labels: feature

#2928 HOM - atualizado em 01/06 as 11:20
  src/components/Shareable/FluxoDeStatus/helper.js
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/style.scss
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/ModalAtualizarOcorrencia/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/Ocorrencias/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/index.jsx
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: feature

#2931 HOM - Atualizado em 01/06 13:15
  src/components/Shareable/FluxoDeStatus/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/FluxoDeStatusMedicaoInicial/index.jsx
Labels: bug

#2935 HOM - Atualizado em 01/06 as 15:10h
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/Ocorrencias/index.jsx
Labels: bug

#2946 Feature/93529-MI-detalhamento-períodos-devolvidos-para-ajustes-pela-dre-visão-UE
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/styles.scss
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalSalvarCorrecoes/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: enhancement, feature

#2950 Hom Atualizado 06/06 as 16h00
  package-lock.json
  package.json
  src/components/Shareable/CKEditorField/index.jsx
  src/components/Shareable/FluxoDeStatus/helper.js
  src/components/Shareable/ModalPadraoSimNao/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/Ocorrencias/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: enhancement, feature

#2951 Feature: remover desabilitar botão após salvar uma observação
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: feature

#2955 Hom Atualizado 07/06 as 11h25
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/Ocorrencias/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: bug, enhancement

#2964 Feature/94417-MI-programas-e-projetos-unificar-períodos-nos-lançamentos
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/helpers.js
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/Ocorrencias/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
  src/services/medicaoInicial/periodoLancamentoMedicao.service.js
Labels: enhancement, feature

#2965 Hom Atualizado 13/06 as 12h05
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/helpers.js
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/Ocorrencias/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
  src/services/medicaoInicial/periodoLancamentoMedicao.service.js
Labels: enhancement, feature

#2975 Feature/95389-MI-alteração-regras-tooltip-programas-e-projetos
  src/components/Shareable/Input/InputValueMedicao/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
Labels: enhancement, feature

#2976 Hom Atualizado 13/06 as 19h00
  src/components/Shareable/Input/InputValueMedicao/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
Labels: enhancement, feature

#3000 Feature/96847-GA-relatório-solicitações-alimentação-dias-com-cancelamento-inclusão-cei-cemei
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoCEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoCEMEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/style.scss
Labels: enhancement, feature

#3001 Hom Atualizado 20/06 as 14h10
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoCEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoCEMEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/style.scss
Labels: enhancement, feature

#3008 Feature/96840-GA-relatório-solicitações-alimentação-dias-com-cancelamento-inclusão-normal-contínua
  src/components/InclusaoDeAlimentacao/Relatorio/index.jsx
  src/components/Shareable/Weekly/style.scss
  src/components/Shareable/style.scss
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoContinuaBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/TabelaResultado/index.jsx
Labels: enhancement, feature

#3009 Hom Atualizado 21/06 as 16h55
  src/components/InclusaoDeAlimentacao/Relatorio/index.jsx
  src/components/Shareable/Weekly/style.scss
  src/components/Shareable/style.scss
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoContinuaBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/TabelaResultado/index.jsx
Labels: enhancement, feature

#3017 Feature/96656-MI-ajuste-dietas-especiais-salvamento-e-botão-voltar-tela-lançamento-ue
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalVoltarPeriodoLancamento/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/styles.scss
  src/pages/LancamentoMedicaoInicial/PeriodoLancamentoMedicaoInicialPage.jsx
Labels: enhancement, feature

#3018 Hom Atualizado 23/06 as 13h25
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalVoltarPeriodoLancamento/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/styles.scss
  src/pages/LancamentoMedicaoInicial/PeriodoLancamentoMedicaoInicialPage.jsx
Labels: enhancement, feature

#3025 Feature/96655-MI-ajustes-lançamento-medição-regras-tabelas-e-legenda
  src/components/Shareable/Input/InputValueMedicao/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/styles.scss
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
Labels: enhancement, feature

#3026 Hom Atualizado 26/06 as 17h00
  src/components/Shareable/Input/InputValueMedicao/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/styles.scss
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
Labels: enhancement, feature

#3031 Feature: adicionar historico de alteracao dos editais
  src/components/Shareable/ModalHistoricoProtocoloPadrao/index.jsx
Labels: feature

#3032 Feature: outras informações no histórico
  src/components/Shareable/ModalHistoricoProtocoloPadrao/index.jsx
Labels: feature

#3016 Feature/96112 vincular protocolos editais
  src/components/Shareable/FinalForm/MultiSelect/index.jsx
  src/components/Shareable/ModalHistoricoProtocoloPadrao/index.jsx
  src/components/screens/DietaEspecial/ConsultaProtocoloPadraoDieta/componentes/DetalhesProtocolo/index.jsx
  src/components/screens/DietaEspecial/ConsultaProtocoloPadraoDieta/componentes/Filtros/index.jsx
  src/components/screens/DietaEspecial/ConsultaProtocoloPadraoDieta/componentes/ModalVincularProtolocos/index.jsx
  src/components/screens/DietaEspecial/ConsultaProtocoloPadraoDieta/index.jsx
  src/services/dietaEspecial.service.js
Labels: feature

#3035 Hom - atualizado em 28/06 - 15:30
  src/components/Shareable/FinalForm/MultiSelect/index.jsx
  src/components/Shareable/ModalHistoricoProtocoloPadrao/index.jsx
  src/components/screens/DietaEspecial/ConsultaProtocoloPadraoDieta/componentes/DetalhesProtocolo/index.jsx
  src/components/screens/DietaEspecial/ConsultaProtocoloPadraoDieta/componentes/Filtros/index.jsx
  src/components/screens/DietaEspecial/ConsultaProtocoloPadraoDieta/componentes/ModalVincularProtolocos/index.jsx
  src/components/screens/DietaEspecial/ConsultaProtocoloPadraoDieta/index.jsx
  src/services/dietaEspecial.service.js
Labels: feature

#3042 Fix: correção dos styles do modal de vincular e histórico
  src/components/Shareable/ModalHistoricoProtocoloPadrao/index.jsx
  src/components/Shareable/ModalHistoricoProtocoloPadrao/styles.scss
Labels: bug

#3047 Feature/96066-GA-inclusão-de-alimentação-motivo-específico
  src/components/InclusaoDeAlimentacao/Escola/Formulario/componentes/Container.jsx
  src/components/InclusaoDeAlimentacao/Escola/Formulario/componentes/InclusaoContinua/index.jsx
  src/components/InclusaoDeAlimentacao/Escola/Formulario/componentes/InclusaoNormal/index.jsx
  src/components/InclusaoDeAlimentacao/Escola/Formulario/index.jsx
  src/components/InclusaoDeAlimentacao/validacao.js
  src/services/cadastroTipoAlimentacao.service.js
Labels: enhancement, feature

#3057 Fix: style dos botões do modal
  src/components/Shareable/ModalHistoricoProtocoloPadrao/styles.scss
Labels: bug

#3059 Fix: sobrescrever class padrão do componente do ant para modificar o style do botão
  src/components/Shareable/ModalHistoricoProtocoloPadrao/styles.scss
Labels: bug

#3060 Hom Atualizado 30/06 as 12h35
  src/components/Shareable/ModalHistoricoProtocoloPadrao/styles.scss
Labels: bug

#3061 Feature/95990 ga botao voltar
  src/components/AlteracaoDeCardapio/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/AlteracaoDeCardapio/Relatorio/index.jsx
  src/components/InversaoDeDiaDeCardapio/Relatorio/index.jsx
  src/components/SolicitacaoDeKitLanche/Relatorio/index.jsx
  src/components/screens/DashboardDRE/index.jsx
  src/pages/AlteracaoDeCardapio/RelatorioPage.jsx
  src/pages/DRE/SolicitacaoUnificadaPage.jsx
  src/pages/Escola/AlteracaoDeCardapioPage.jsx
  src/pages/Escola/InclusaoDeAlimentacaoPage.jsx
  src/pages/InversaoDeDiaDeCardapio/RelatorioPage.jsx
  src/pages/SolicitacaoDeKitLanche/RelatorioPage.jsx
Labels: feature

#3062 HOM - Atualiza até 30/06 15:00
  src/components/AlteracaoDeCardapio/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/AlteracaoDeCardapio/Relatorio/index.jsx
  src/components/InversaoDeDiaDeCardapio/Relatorio/index.jsx
  src/components/SolicitacaoDeKitLanche/Relatorio/index.jsx
  src/components/screens/DashboardDRE/index.jsx
  src/pages/AlteracaoDeCardapio/RelatorioPage.jsx
  src/pages/DRE/SolicitacaoUnificadaPage.jsx
  src/pages/Escola/AlteracaoDeCardapioPage.jsx
  src/pages/Escola/InclusaoDeAlimentacaoPage.jsx
  src/pages/InversaoDeDiaDeCardapio/RelatorioPage.jsx
  src/pages/SolicitacaoDeKitLanche/RelatorioPage.jsx
Labels: feature
