Repository prefeiturasp/SME-Terceirizadas-Frontend, pull requests merged in 2023-05, with the labels that each got.

#2829 Hom Atualizado 02/05 as 15h45
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: enhancement

#2831 Hom Atualizado 03/05 as 09h10
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/styles.scss
Labels: enhancement

#2842 Feature/85831-MI-relatorio-medição-inicial-ue-observações-diárias-lançamento
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalObservacaoDiaria/index.jsx
  src/helpers/fieldValidators.js
Labels: enhancement, feature

#2843 Hom Atualizado 08/05 as 18h25
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalObservacaoDiaria/index.jsx
  src/helpers/fieldValidators.js
Labels: enhancement, feature

#2844 Feature/92069-MI-teste-usabilidade-medição-inicial-liberar-modulo-amb-treinamento
  src/helpers/utilities.js
Labels: enhancement

#2847 Feature/91721 salvar correcao ocorrencia
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalSolicitarCorrecaoOcorrencia/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/constants.js
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/style.scss
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: feature

#2851 HOM - Atualizado até 15/05 15:50
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalSolicitarCorrecaoOcorrencia/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/constants.js
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/style.scss
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: feature

#2852 Feature/91725-MI-aprimoramento-tela-acompanhamento-e-status-das-medições-dre-codae
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/components/CardMedicaoPorStatus/index.jsx
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/constants.js
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/index.jsx
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/style.scss
  src/components/screens/helper.js
Labels: enhancement, feature

#2853 Hom Atualizado 15/05 as 19h35
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/components/CardMedicaoPorStatus/index.jsx
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/constants.js
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/index.jsx
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/style.scss
  src/components/screens/helper.js
Labels: enhancement, feature

#2854 Fix: typo
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalSolicitarCorrecaoOcorrencia/index.jsx
Labels: bug

#2855 HOM - Atualizada até 16/05 às 11:30
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalSolicitarCorrecaoOcorrencia/index.jsx
Labels: bug

#2864 Feature/92083-MI-aprimoramento-tela-acompanhamento-e-status-das-medições-escola
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/constants.js
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/index.jsx
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/style.scss
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/constants.js
  src/configs/RoutesConfig.js
Labels: enhancement, feature

#2865 Hom Atualizado 16/05 as 20h50
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/constants.js
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/index.jsx
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/style.scss
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/constants.js
  src/configs/RoutesConfig.js
Labels: enhancement, feature

#2869 Feature/91846 aprovacao formulario ocorrencias
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalOcorrencia/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: feature

#2871 Fix: validar quando não houver log ainda
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
Labels: bug

#2870 HOM - Atualizado até 19/05 14h20
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalOcorrencia/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: feature

#2868 Feature/93523-MI-exportar-pdf-medição-inicial-pela-central-de-downloads
  src/components/Shareable/CardStatusDeSolicitacao/CardStatusDeSolicitacao.jsx
  src/components/screens/DashBoardDietaEspecial/index.js
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/index.jsx
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/style.scss
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/services/relatorios.js
Labels: enhancement, feature

#2872 Hom Atualizado 19/05 as 16h15
  src/components/Shareable/CardStatusDeSolicitacao/CardStatusDeSolicitacao.jsx
  src/components/screens/DashBoardDietaEspecial/index.js
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/index.jsx
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/style.scss
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/services/relatorios.js
Labels: enhancement, feature

#2873 Hotfix/93726-DE-nutrisupervisão-não-consegue-gerar-relatório-de-dieta-aluno
  src/components/screens/DietaEspecial/AtivasInativasPorAluno/index.jsx
  src/helpers/fieldValidators.js
Labels: bug

#2874 Prod atualizado 22/05 as 11h30
  src/components/screens/DietaEspecial/AtivasInativasPorAluno/index.jsx
  src/helpers/fieldValidators.js
Labels: bug

#2881 Hom atualizado 22/05 as 19h00
  src/components/screens/DietaEspecial/AtivasInativasPorAluno/index.jsx
  src/helpers/fieldValidators.js
Labels: bug

#2882 Dev atualizado 22/05 as 19h05
  src/components/screens/DietaEspecial/AtivasInativasPorAluno/index.jsx
  src/helpers/fieldValidators.js
Labels: bug

#2884 Fix: desabilitar botão aprovar formulário
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
Labels: bug

#2885 Hom atualizado 23/05 as 11h30
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
Labels: bug

#2887 Hotfix/numero alunos cei kit lanche
  src/components/SolicitacaoDeKitLanche/Container/base.jsx
  src/services/alteracaoDeCardapio/escola.service.js
Labels: bug

#2888 Hotfix/numero alunos cei kit lanche
  src/components/SolicitacaoDeKitLanche/Container/base.jsx
  src/services/alteracaoDeCardapio/escola.service.js
Labels: bug

#2889 Merge pull request #2888 from prefeiturasp/hotfix/numero-alunos-cei-kit-lanche
  src/components/SolicitacaoDeKitLanche/Container/base.jsx
  src/services/alteracaoDeCardapio/escola.service.js
Labels: bug

#2890 Merge pull request #2888 from prefeiturasp/hotfix/numero-alunos-cei-kit-lanche
  src/components/SolicitacaoDeKitLanche/Container/base.jsx
  src/services/alteracaoDeCardapio/escola.service.js
Labels: bug

#2891 Feature/92113-MI-retirar-lanche-emergencial-de-períodos-grupos-que-n-sejam-solicitações-de-alimentação
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: enhancement, feature

#2892 Hom Atualizado 23/05 as 18h20
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: enhancement, feature

#2895 Feature/91845-MI-envio-da-aprovação-medição-inicial-pela-dre
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalEnviarParaCodae/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/style.scss
  src/pages/LancamentoMedicaoInicial/LancamentoMedicaoInicialPage.jsx
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: enhancement, feature

#2900 Hom Atualizado 25/05 as 15h40
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalEnviarParaCodae/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/style.scss
  src/components/screens/PreRecebimento/CadastroCronograma/index.jsx
  src/components/screens/PreRecebimento/CronogramaEntrega/components/AcoesDetalhar/index.jsx
  src/components/screens/PreRecebimento/CronogramaEntrega/components/AcoesDetalharCronograma/index.jsx
  src/components/screens/PreRecebimento/CronogramaEntrega/components/AcoesDetalharDilogDiretoria/index.jsx
  src/components/screens/PreRecebimento/CronogramaEntrega/components/AcoesDetalharDinutreDiretoria/index.jsx
  src/components/screens/helper.js
  src/pages/LancamentoMedicaoInicial/LancamentoMedicaoInicialPage.jsx
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: enhancement, feature

#2902 Feature: desabilitar e habilitar os botões de correção e aprovação
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
Labels: feature

#2906 Feature/92884-MI-página-inicial-aprovado-pela-dre
  src/components/Shareable/FluxoDeStatus/helper.js
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/style.scss
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/FluxoDeStatusMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/styles.scss
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/Ocorrencias/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/index.jsx
Labels: enhancement, feature

#2907 Hom Atualizado 26/05 as 21h00
  src/components/Shareable/FluxoDeStatus/helper.js
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/style.scss
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/FluxoDeStatusMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/styles.scss
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/Ocorrencias/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/index.jsx
Labels: enhancement, feature

#2908 Feature/91842 solicitar correcao medicao inicial
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalSolicitarCorrecaoUE/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: feature

#2915 Feature/91845-MI-envio-da-aprovação-medição-inicial-pela-dre
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
Labels: enhancement

#2916 Hom Atualizado 30/05 as 18h30
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
Labels: enhancement

#2919 Feature/91845-MI-envio-da-aprovação-medição-inicial-pela-dre
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
Labels: enhancement

#2920 Hom Atualizado 30/05 as 19h45
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
Labels: enhancement
