Repository prefeiturasp/SME-Terceirizadas-Frontend, pull requests merged in 2023-10, with the labels that each got.

#3561 HOM - Atualizado 03/10 às 10:30h
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
Labels: bug

#3564 Feature/103449-MI-visualização-tela-lançamento-período-DRE-escolas-cei
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
  src/components/screens/Produto/AtualizacaoProdutoForm/styles.scss
  src/pages/style.scss
Labels: enhancement, feature

#3565 Hom - Atualizado em 04/10 as 12h55
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
  src/components/screens/Produto/AtualizacaoProdutoForm/styles.scss
  src/pages/style.scss
Labels: enhancement, feature

#3568 Feature: adicionar historico de correções para CODAE
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalHistoricoCorrecoesPeriodo/index.jsx
Labels: feature

#3569 Hom - Atualizado em 05/23 às 15:40
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalHistoricoCorrecoesPeriodo/index.jsx
Labels: feature

#3594 Feature/104604-CADASTROS-tela-nova-permissão-lançamentos-especiais-na-medição-inicial
  package-lock.json
  package.json
  src/components/SolicitacaoUnificada/Container.jsx
  src/components/screens/Cadastros/CadastroTipoAlimentacao/index.jsx
  src/components/screens/Cadastros/NovaPermissaoLancamentoEspecial/index.tsx
  src/components/screens/Cadastros/NovaPermissaoLancamentoEspecial/style.scss
  src/components/screens/Cadastros/PermissaoLancamentosEspeciais/index.tsx
  src/components/screens/Cadastros/PermissaoLancamentosEspeciais/style.scss
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/index.jsx
  src/components/screens/Produto/Reclamacao/components/ModalReclamacaoProduto/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/Filtros/index.jsx
  src/components/screens/Relatorios/components/BuscaPorPeriodo/index.jsx
  src/configs/RoutesConfig.js
  src/configs/constants.js
  src/helpers/dietaEspecial.js
  src/pages/Cadastros/CadastroTipoAlimentacaoPage.jsx
  src/pages/Cadastros/NovaPermissaoLancamentoEspecialPage.tsx
  src/pages/Cadastros/PermissaoLancamentosEspeciaisPage.tsx
  src/services/escola.service.js
  src/services/medicaoInicial/periodoLancamentoMedicao.service.js
Labels: enhancement, feature

#3595 Hom - Atualizado em 10/10 as 16h55
  package-lock.json
  package.json
  src/components/SolicitacaoUnificada/Container.jsx
  src/components/screens/Cadastros/CadastroTipoAlimentacao/index.jsx
  src/components/screens/Cadastros/NovaPermissaoLancamentoEspecial/index.tsx
  src/components/screens/Cadastros/NovaPermissaoLancamentoEspecial/style.scss
  src/components/screens/Cadastros/PermissaoLancamentosEspeciais/index.tsx
  src/components/screens/Cadastros/PermissaoLancamentosEspeciais/style.scss
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/index.jsx
  src/components/screens/Produto/Reclamacao/components/ModalReclamacaoProduto/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/Filtros/index.jsx
  src/components/screens/Relatorios/components/BuscaPorPeriodo/index.jsx
  src/configs/RoutesConfig.js
  src/configs/constants.js
  src/helpers/dietaEspecial.js
  src/pages/Cadastros/CadastroTipoAlimentacaoPage.jsx
  src/pages/Cadastros/NovaPermissaoLancamentoEspecialPage.tsx
  src/pages/Cadastros/PermissaoLancamentosEspeciaisPage.tsx
  src/services/escola.service.js
  src/services/medicaoInicial/periodoLancamentoMedicao.service.js
Labels: enhancement, feature

#3598 Feature/104861 evento especifico solicitacoes cemei
  src/components/InclusaoDeAlimentacaoCEMEI/Relatorio/componentes/CorpoRelatorio/index.jsx
  src/components/InclusaoDeAlimentacaoCEMEI/Relatorio/index.jsx
  src/components/InclusaoDeAlimentacaoCEMEI/componentes/Container.jsx
  src/components/InclusaoDeAlimentacaoCEMEI/componentes/InclusaoNormal/index.jsx
  src/components/InclusaoDeAlimentacaoCEMEI/helpers.js
  src/components/InclusaoDeAlimentacaoCEMEI/index.jsx
Labels: feature

#3600 Hom - Atualizado em 11/10 às 12:45h
  src/components/InclusaoDeAlimentacaoCEMEI/Relatorio/componentes/CorpoRelatorio/index.jsx
  src/components/InclusaoDeAlimentacaoCEMEI/Relatorio/index.jsx
  src/components/InclusaoDeAlimentacaoCEMEI/componentes/Container.jsx
  src/components/InclusaoDeAlimentacaoCEMEI/componentes/InclusaoNormal/index.jsx
  src/components/InclusaoDeAlimentacaoCEMEI/helpers.js
  src/components/InclusaoDeAlimentacaoCEMEI/index.jsx
Labels: feature

#3616 Feature/104870 descricao evento especifico
  src/components/InclusaoDeAlimentacaoCEMEI/Relatorio/componentes/CorpoRelatorio/index.jsx
  src/components/InclusaoDeAlimentacaoCEMEI/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoCEMEIBody/index.jsx
Labels: feature

#3617 Fix: Exibir tooltip em dias não letivos
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
Labels: bug

#3621 HOM - Atualizado 16/10 09:45h
  src/components/InclusaoDeAlimentacaoCEMEI/Relatorio/componentes/CorpoRelatorio/index.jsx
  src/components/InclusaoDeAlimentacaoCEMEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoCEMEIBody/index.jsx
Labels: feature

#3623 Hom - Atualizado em 16/10 as 11h35
  src/components/screens/Cadastros/PermissaoLancamentosEspeciais/index.tsx
  src/components/screens/Cadastros/PermissaoLancamentosEspeciais/style.scss
  src/interfaces/medicao_inicial.interface.ts
  src/interfaces/responses.interface.ts
  src/services/medicaoInicial/permissaoLancamentosEspeciais.service.ts
Labels: enhancement, feature

#3622 Fix: deve exibir descrição apenas quando motivo for evento específico
  src/components/InclusaoDeAlimentacaoCEMEI/index.jsx
Labels: bug

#3624 Hom - Atualizado 16/10 às 11:30h
  src/components/InclusaoDeAlimentacaoCEMEI/index.jsx
Labels: bug

#3626 Hom - Atualizado em 16/10 às 12::30h
  src/components/InclusaoDeAlimentacaoCEMEI/index.jsx
Labels: bug

#3632 Feature/104724-MI-ajustes-acompanhamento-lançamentos-usuário-medição-codae
  src/components/screens/Cadastros/PermissaoLancamentosEspeciais/style.scss
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/constants.js
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/index.jsx
Labels: enhancement, feature

#3634 Hom - Atualizado em 16/10 as 17h35
  src/components/screens/Cadastros/PermissaoLancamentosEspeciais/style.scss
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/constants.js
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/index.jsx
Labels: enhancement, feature

#3648 Feature/104716-MI-tooltip-sobremesa-doce-usuários-dre-e-medição-conferência-lançamentos
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
Labels: enhancement, feature

#3651 Hom - Atualizado em 19/10 as 10h10
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
Labels: enhancement, feature

#3662 Feature/105272-MI-tooltips-inclusão-alteração-suspensão-alimentação-dre-e-medição-conferência-lançamentos
  src/components/Shareable/Input/InputValueMedicao/index.jsx
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
  src/configs/RoutesConfig.js
Labels: enhancement, feature

#3663 Hom - Atualizado em 24/10 as 10h50
  .eslintrc.json
  package.json
  src/components/Shareable/Input/InputFile/helper.js
  src/components/Shareable/Input/InputValueMedicao/index.jsx
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
  src/configs/RoutesConfig.js
Labels: enhancement, feature

#3666 Feature/104626 editar permissões lancamento especial
  src/components/screens/Cadastros/NovaPermissaoLancamentoEspecial/index.tsx
  src/components/screens/Cadastros/PermissaoLancamentosEspeciais/index.tsx
  src/configs/RoutesConfig.js
  src/configs/constants.js
  src/interfaces/escola.interface.ts
  src/interfaces/medicao_inicial.interface.ts
  src/pages/Cadastros/NovaPermissaoLancamentoEspecialPage.tsx
  src/services/medicaoInicial/periodoLancamentoMedicao.service.js
Labels: feature

#3668 HOM - Atualizado em 24/10 às 16:20h
  src/components/screens/Cadastros/NovaPermissaoLancamentoEspecial/index.tsx
  src/components/screens/Cadastros/PermissaoLancamentosEspeciais/index.tsx
  src/configs/RoutesConfig.js
  src/configs/constants.js
  src/interfaces/escola.interface.ts
  src/interfaces/medicao_inicial.interface.ts
  src/pages/Cadastros/NovaPermissaoLancamentoEspecialPage.tsx
  src/services/medicaoInicial/periodoLancamentoMedicao.service.js
Labels: feature

#3674 Feature/101694-MI-dre-salvamento-solicitação-correção-período-tela-conferência-lançamentos
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
Labels: enhancement, feature

#3676 Hom - Atualizado em 25/10 as 15h35
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
Labels: enhancement, feature

#3682 HOM - Atualizado em 26/10 às 15:45h
  src/components/screens/Cadastros/NovaPermissaoLancamentoEspecial/index.tsx
  src/components/screens/Cadastros/NovaPermissaoLancamentoEspecial/style.scss
Labels: bug

#3684 Feature/71080-MI-desmock-dados-tela-inicial-medição-escolas-cei
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/helpers.js
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/CardLancamentoCEI/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/index.jsx
Labels: enhancement, feature

#3690 Hom - Atualizado em 27/10 as 10h45
  src/components/screens/Cadastros/CadastroEmpresa/CadastroEmpresa.jsx
  src/components/screens/Cadastros/CadastroEmpresa/components/Form/ContratosFormSet.jsx
  src/components/screens/Cadastros/CadastroEmpresa/helper.js
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/helpers.js
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/CardLancamentoCEI/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/index.jsx
  src/services/terceirizada.service.js
Labels: enhancement, feature

#3695 Feature/101001-MI-tela-detalhamento-períodos-devolvidos-para-ajustes-dre-escolas-cei
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/CardLancamentoCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalSalvarCorrecoes/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/components/ModalSalvarCorrecoes/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
Labels: enhancement, feature

#3696 Hom - Atualizado em 30/10 as 10h55
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/CardLancamentoCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalSalvarCorrecoes/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/components/ModalSalvarCorrecoes/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
Labels: enhancement, feature

#3698 Feature/106461-MI-envio-correção-para-dre-escolas-cei
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/helpers.js
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/CardLancamentoCEI/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/index.jsx
Labels: enhancement, feature

#3701 Hom - Atualizado em 30/10 as 15h20
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/helpers.js
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/CardLancamentoCEI/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/index.jsx
Labels: enhancement, feature

#3712 Feature/105807-GA-inversão-dia-cardápio-alterar-regra-de-referência-e-aplicar-em
  src/components/InversaoDeDiaDeCardapio/index.jsx
  src/components/Shareable/DatePicker/index.jsx
Labels: enhancement, feature

#3713 Hom - Atualizado em 31/10 as 12h25
  src/components/InversaoDeDiaDeCardapio/index.jsx
  src/components/Shareable/DatePicker/index.jsx
Labels: enhancement, feature

#3711 Feature: tratar erros para Card grupos periodo
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
Labels: feature
