Repository prefeiturasp/SME-Terceirizadas-Frontend, pull requests merged in 2023-04, with the labels that each got.

#2684 Feature/86236-MI-tela-laçamento-ETEC
  src/components/InclusaoDeAlimentacao/Escola/Formulario/componentes/Container.jsx
  src/components/Shareable/Input/InputValueMedicao/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
  src/components/screens/PainelInicial/index.jsx
  src/configs/RoutesConfig.js
  src/helpers/utilities.js
  src/services/medicaoInicial/periodoLancamentoMedicao.service.js
Labels: enhancement, feature

#2698 Hom Atualizado 10/04 as 19h05
  src/components/InclusaoDeAlimentacao/Escola/Formulario/componentes/Container.jsx
  src/components/Shareable/Input/InputValueMedicao/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
  src/components/screens/PainelInicial/index.jsx
  src/configs/RoutesConfig.js
  src/helpers/utilities.js
  src/services/medicaoInicial/periodoLancamentoMedicao.service.js
Labels: enhancement, feature

#2707 Feature/90028 relatorio alunos matriculados pdf
  src/components/screens/Relatorios/AlunosMatriculados/index.jsx
  src/services/relatorios.service.js
Labels: feature

#2721 Hom Atualizado 13/04 as 13h20
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: enhancement, feature

#2726 Feature/81324 relatorio medicao pagina 1
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/index.jsx
  src/services/relatorios.js
Labels: feature

#2730 Hom Atualizado 14/04 as 10h30
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/index.jsx
  src/services/relatorios.js
Labels: feature

#2774 Feature/88612-MI-aprimoramento-regras-campos-de-programas-e-projetos
  src/components/Shareable/Input/InputValueMedicao/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
Labels: enhancement, feature

#2775 Hom Atualizado 24/04 as 11h05
  src/components/Shareable/Input/InputValueMedicao/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
Labels: enhancement, feature

#2803 Feature: botão e método no service para gerar xlsx
  src/components/screens/Relatorios/AlunosMatriculados/index.jsx
  src/services/relatorios.service.js
Labels: feature

#2809 HOM - Atualizado até 27/04 14:30
  src/components/screens/Relatorios/AlunosMatriculados/index.jsx
  src/services/relatorios.service.js
Labels: feature

#2811 Fix: typo
  src/components/screens/Relatorios/AlunosMatriculados/index.jsx
Labels: bug

#2813 HOM - Atualizado até 27/04 16:00
  src/components/screens/Relatorios/AlunosMatriculados/index.jsx
Labels: bug

#2825 Feature: passar parâmetros para exibir alunos com solicitações de alteração UE
  src/components/SolicitacaoDeKitLanche/Container/base.jsx
  src/components/SolicitacaoKitLancheCEMEI/componentes/Container.jsx
Labels: feature

#2827 HOM - Atualizado até 28/04 às 19h10
  src/components/Shareable/InputSearchPendencias/index.jsx
  src/components/SolicitacaoDeKitLanche/Container/base.jsx
  src/components/SolicitacaoKitLancheCEMEI/componentes/Container.jsx
  src/components/screens/DashBoardDietaEspecial/StatusSolicitacoes.jsx
  src/components/screens/DietaEspecial/Relatorio/index.jsx
  src/helpers/terceirizadas.js
Labels: feature
