Repository prefeiturasp/SME-Terceirizadas-Frontend, pull requests merged in 2023-11, with the labels that each got.

#3724 Feature: tratar array de erros para ETEC
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
Labels: feature

#3725 HOM - Atualizado em 04/11 às 17:00h
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
Labels: feature

#3726 Feature: alterar componente para método de contagem
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/InformacoesMedicaoInicial/index.jsx
Labels: feature

#3727 HOM - Atualizado em 06/11 às 09:00h
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/InformacoesMedicaoInicial/index.jsx
Labels: feature

#3759 HOM - Atualizado em 16/11 às 08:50
  src/components/screens/Produto/BuscaProdutoSuspensos/components/TabelaResultado/index.jsx
  src/services/produto.service.js
Labels: feature

#3768 Feature: Exibir tooltip quando somatório de lanches ultrapassar frequentes na dieta especial
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
Labels: feature

#3769 HOM - Atualizado em 17/11 às 10:25h
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
Labels: feature

#3770 Feature: exibir evento em solicitações similares
  src/components/Shareable/SolicitacoesSimilaresKitLanche/index.jsx
Labels: feature

#3771 HOM - Atualizado em 17/11 às 16:30h
  src/components/Shareable/SolicitacoesSimilaresKitLanche/index.jsx
Labels: feature

#3772 Feature/107018-MI-tela-lançamento-infantil-integral-manhã-tarde-escola-cemei
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/FluxoDeStatusMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/InformacoesMedicaoInicialCEI/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/CardLancamentoCEI/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/helpers.js
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/validacoes.js
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: enhancement, feature

#3774 Hom - Atualizado em 20/11 as 16h25
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/FluxoDeStatusMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/InformacoesMedicaoInicialCEI/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/CardLancamentoCEI/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/helpers.js
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/validacoes.js
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: enhancement, feature

#3776 Feature: adicionar media query para meidicao (todas escolas)
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/styles.scss
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/CardLancamentoCEI/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/CardLancamentoCEI/styles.scss
Labels: feature

#3777 HOM - Atualizado em 21/11 às 09:15h
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/styles.scss
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/CardLancamentoCEI/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/CardLancamentoCEI/styles.scss
Labels: feature

#3812 Hom - Atualizado em 29/11 as 17h30
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/CardLancamentoCEI/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/validacoes.js
Labels: enhancement, feature

#3823 Feature/107034-MI-integração-inclusão-alimentação-escolas-cemei-período-integral
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/validacoes.js
Labels: enhancement

#3824 Hom - Atualizado em 30/11 as 19h30
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/validacoes.js
Labels: enhancement
