Repository prefeiturasp/SME-Terceirizadas-Frontend, pull requests merged in 2023-03, with the labels that each got.

#2533 Fix: reset form
  src/components/InclusaoDeAlimentacaoDaCei/Rascunhos.jsx
  src/components/InclusaoDeAlimentacaoDaCei/index.jsx
Labels: bug

#2535 Hom Atualizado 01/03 às 10:10
  src/components/InclusaoDeAlimentacaoDaCei/Rascunhos.jsx
  src/components/InclusaoDeAlimentacaoDaCei/index.jsx
Labels: bug

#2539 Feature/86398-GA-relatorio-sol-alimentacao-ajustar-periodos-escola-cei-infantil
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoCEIBody/index.jsx
Labels: enhancement, feature

#2540 Hom Atualizado 01/03 às 13:40
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoCEIBody/index.jsx
Labels: enhancement, feature

#2541 Fix: periodos internos apenas para INTEGRAL
  src/components/InclusaoDeAlimentacao/Relatorio/componentes/InclusoesCEI.jsx
Labels: bug

#2542 Hom Atualizado 01/03 às 15:00
  src/components/AlteracaoDeCardapio/CEI/helper.js
  src/components/AlteracaoDeCardapio/CEI/index.jsx
  src/components/InclusaoDeAlimentacao/Relatorio/componentes/InclusoesCEI.jsx
Labels: bug

#2548 Feature/86230-GA-inserir-ID-solicitação-no-resultado-relatório-de-solicitações-alimentação
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/AlteracaoBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/AlteracaoCEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/AlteracaoCEMEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoCEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoCEMEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoContinuaBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InversaoCardapioBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/KitLancheAvulsaBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/KitLancheAvulsaCEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/KitLancheAvulsaCEMEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/KitLancheUnificadoBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/SuspensaoAlimentacaoBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/SuspensaoAlimentacaoCEIBody/index.jsx
Labels: enhancement, feature

#2561 Feature/87382-PeD-incluir-no-histórico-do-produto-datas-de-vínculos-dos-editais
  src/components/Shareable/FluxoDeStatus/helper.js
  src/components/Shareable/ModalHistorico/index.jsx
Labels: enhancement, feature

#2562 Hom Atualizado 03/03 as 19h05
  src/components/Shareable/FluxoDeStatus/helper.js
  src/components/Shareable/ModalHistorico/index.jsx
Labels: enhancement, feature

#2568 HOM - Atualizada até 07/03 às 15:40
  src/components/Shareable/Sidebar/menus/MenuGestaoDeAlimentacao.jsx
  src/components/screens/Relatorios/AlunosMatriculados/componentes/Filtros/index.jsx
  src/components/screens/Relatorios/AlunosMatriculados/helpers.js
  src/components/screens/Relatorios/AlunosMatriculados/index.jsx
  src/configs/RoutesConfig.js
  src/configs/constants.js
  src/pages/Relatorios/RelatorioAlunosMatriculadosPage.jsx
  src/services/alunosMatriculados.service.js
Labels: feature

#2572 Feature/85622-MI-visualização-de-medição-DRE
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/constants.js
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/style.scss
  src/configs/RoutesConfig.js
  src/configs/constants.js
  src/pages/LancamentoMedicaoInicial/ConferenciaDosLancamentosPage.jsx
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: enhancement, feature

#2574 Hom Atualizado 08/03 as 14h40
  src/components/Shareable/Sidebar/menus/MenuPreRecebimento.jsx
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/constants.js
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/style.scss
  src/components/screens/PreRecebimento/SolicitacaoAlteracaoCronograma/components/Filtros/index.jsx
  src/components/screens/PreRecebimento/SolicitacaoAlteracaoCronograma/components/Filtros/style.scss
  src/components/screens/PreRecebimento/SolicitacaoAlteracaoCronograma/components/ListagemAlteracoesCronogramas/index.jsx
  src/components/screens/PreRecebimento/SolicitacaoAlteracaoCronograma/components/ListagemAlteracoesCronogramas/styles.scss
  src/components/screens/PreRecebimento/SolicitacaoAlteracaoCronograma/helper.js
  src/components/screens/PreRecebimento/SolicitacaoAlteracaoCronograma/index.jsx
  src/configs/RoutesConfig.js
  src/configs/constants.js
  src/pages/LancamentoMedicaoInicial/ConferenciaDosLancamentosPage.jsx
  src/pages/PreRecebimento/SolicitacaoAlteracaoCronogramaPage.jsx
  src/services/cronograma.service.js
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: enhancement, feature

#2575 Hom Atualizado 08/03 as 14h55
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoCEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoCEMEIBody/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/SuspensaoAlimentacaoBody/index.jsx
Labels: enhancement

#2582 Feature/85625-MI-visualização-lançamentos-de-período-DRE
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/constants.js
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/style.scss
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: enhancement, feature

#2583 Hom Atualizado 13/03 as 10h30
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/constants.js
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/style.scss
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: enhancement, feature

#2585 Hom Atualizado 13/03 as 13h30
  src/components/screens/Relatorios/AlunosMatriculados/componentes/DetalhesCEIouCEMEI/index.jsx
  src/components/screens/Relatorios/AlunosMatriculados/componentes/Filtros/index.jsx
  src/components/screens/Relatorios/AlunosMatriculados/componentes/TabelaResultado/index.jsx
  src/components/screens/Relatorios/AlunosMatriculados/helpers.js
  src/components/screens/Relatorios/AlunosMatriculados/index.jsx
  src/components/screens/Relatorios/AlunosMatriculados/style.scss
  src/services/alunosMatriculados.service.js
Labels: feature

#2587 Fix: modificar input para textfield e sobrescrever min-height padrao do componente
  src/components/screens/Produto/Homologacao/components/EditaisVinculados.jsx
  src/components/screens/Produto/Homologacao/components/style.scss
Labels: bug

#2588 Hom Atualizado 14/03 as 11h20
  src/components/screens/Produto/Homologacao/components/EditaisVinculados.jsx
  src/components/screens/Produto/Homologacao/components/style.scss
Labels: bug

#2589 Feature/85623 aprovacao periodo medicao perfil dre
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalAprovarPeriodo/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/helper.js
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: feature

#2590 Hom Atualizado 14/03 as 15h20
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalAprovarPeriodo/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/helper.js
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: feature

#2591 Feature/85636-MI-solicitação-correção-período-de-lançamento-dre
  src/components/Shareable/CKEditorField/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalCancelarCorrecao/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalSalvarCorrecao/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/constants.js
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/style.scss
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: enhancement, feature

#2592 Hom Atualizado 15/03 as 09h00
  src/components/Shareable/CKEditorField/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalCancelarCorrecao/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalSalvarCorrecao/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/constants.js
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/style.scss
  src/services/medicaoInicial/solicitacaoMedicaoInicial.service.js
Labels: enhancement, feature

#2593 Fix: atualizar dados ao aprovar pela DRE
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/constants.js
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
Labels: bug

#2596 Fix: style dos logs de correções
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/style.scss
Labels: bug

#2598 Fix: bloco de log de aprovação
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/style.scss
Labels: bug

#2600 Hom Atualizado 15/03 as 16h10
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/style.scss
Labels: bug

#2602 Fix: typo
  src/components/screens/Relatorios/AlunosMatriculados/componentes/TabelaResultado/index.jsx
Labels: bug

#2603 Hom Atualizado 16/03 as 11h45
  src/components/screens/Relatorios/AlunosMatriculados/componentes/TabelaResultado/index.jsx
Labels: bug

#2620 Fix: remover checkobox e apresentar distinto por período
  src/components/screens/Relatorios/AlunosMatriculados/componentes/DetalhesCEIouCEMEI/index.jsx
  src/components/screens/Relatorios/AlunosMatriculados/componentes/TabelaResultado/index.jsx
Labels: bug

#2623 Hom-r2 atualizado 24/03 as 09h10
  src/components/screens/Relatorios/AlunosMatriculados/componentes/DetalhesCEIouCEMEI/index.jsx
  src/components/screens/Relatorios/AlunosMatriculados/componentes/TabelaResultado/index.jsx
Labels: bug

#2624 Hom atualizado 24/03 as 09h10
  src/components/screens/Relatorios/AlunosMatriculados/componentes/DetalhesCEIouCEMEI/index.jsx
  src/components/screens/Relatorios/AlunosMatriculados/componentes/TabelaResultado/index.jsx
Labels: bug

#2622 Feature/88750-PeD-incluir-dados-terceirizada-no-histórico
  src/components/Shareable/ModalHistorico/index.jsx
  src/components/screens/Produto/BuscaAvancada/components/RelatorioProduto/components/styles.scss
Labels: enhancement

#2601 Feature/85802-GA-relatório-alunos-matriculados-dre
  src/components/Shareable/Sidebar/menus/MenuGestaoDeAlimentacao.jsx
  src/components/screens/Relatorios/AlunosMatriculados/componentes/Filtros/index.jsx
  src/configs/RoutesConfig.js
Labels: enhancement, feature

#2628 Hom Atualizado 24/03 as 17h30
  src/components/Shareable/Sidebar/menus/MenuGestaoDeAlimentacao.jsx
  src/components/screens/Relatorios/AlunosMatriculados/componentes/Filtros/index.jsx
  src/configs/RoutesConfig.js
Labels: feature

#2629 Feature/85803-GA-relatorio-alunos-matriculados-para-nutrimanifestação-nutrisupervisão-codae-medicão
  src/components/Shareable/Sidebar/menus/MenuGestaoDeAlimentacao.jsx
  src/configs/RoutesConfig.js
Labels: enhancement

#2631 Hom Atualizado 27/03 as 11h30
  src/components/Shareable/Sidebar/menus/MenuGestaoDeAlimentacao.jsx
  src/configs/RoutesConfig.js
Labels: enhancement

#2639 Feature/88746 liberar relatorio solicitacoes ga para terceirizadas
  src/components/Shareable/Sidebar/menus/MenuGestaoDeAlimentacao.jsx
  src/components/SolicitacaoUnificada/Container.jsx
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/Filtros/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/index.jsx
  src/components/screens/Relatorios/components/BuscaPorPeriodo/index.jsx
  src/configs/RoutesConfig.js
  src/helpers/dietaEspecial.js
  src/pages/Relatorios/RelatorioSolicitacoesAlimentacaoPage.jsx
  src/services/escola.service.js
  src/services/relatorios.service.js
Labels: feature

#2644 Hom Atualizado 29/03 as 02h10
  src/components/Shareable/Sidebar/menus/MenuGestaoDeAlimentacao.jsx
  src/components/SolicitacaoUnificada/Container.jsx
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/Filtros/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/index.jsx
  src/components/screens/Relatorios/components/BuscaPorPeriodo/index.jsx
  src/configs/RoutesConfig.js
  src/helpers/dietaEspecial.js
  src/pages/Relatorios/RelatorioSolicitacoesAlimentacaoPage.jsx
  src/services/escola.service.js
  src/services/relatorios.service.js
Labels: feature

#2646 Feature/85802-GA-relatório-alunos-matriculados-dre
  src/components/screens/Relatorios/AlunosMatriculados/componentes/TabelaResultado/index.jsx
  src/components/screens/Relatorios/AlunosMatriculados/index.jsx
  src/components/screens/Relatorios/AlunosMatriculados/style.scss
Labels: enhancement

#2648 Hom Atualizado 29/03 as 14h05
  src/components/screens/Relatorios/AlunosMatriculados/componentes/TabelaResultado/index.jsx
  src/components/screens/Relatorios/AlunosMatriculados/index.jsx
  src/components/screens/Relatorios/AlunosMatriculados/style.scss
Labels: enhancement

#2649 Hotfix/89352 corrigir coluna da grid
  src/components/screens/Relatorios/AlunosMatriculados/componentes/DetalhesCEIouCEMEI/index.jsx
Labels: bug

#2650 MASTER Atualizado 29/03 as 16h00
  src/components/screens/Relatorios/AlunosMatriculados/componentes/DetalhesCEIouCEMEI/index.jsx
Labels: bug

#2651 Hom Atualizado 29/03 as 16h05
  src/components/screens/Relatorios/AlunosMatriculados/componentes/DetalhesCEIouCEMEI/index.jsx
Labels: bug

#2653 Fix/90458-GA-ajustar-filtros-dinâmicos-de-lote-ue-tela-relatório-alunos-matriculados
  src/components/screens/Relatorios/AlunosMatriculados/componentes/Filtros/index.jsx
Labels: bug

#2654 Hom Atualizado 29/03 as 19h10
  src/components/screens/Relatorios/AlunosMatriculados/componentes/Filtros/index.jsx
Labels: bug
