Repository prefeiturasp/SME-Terceirizadas-Frontend, pull requests merged in 2023-09, with the labels that each got.

#3396 Feature/101984-MI-alteração-regras-de-integração-com-lanche-emergencial
  src/components/Shareable/Input/InputValueMedicao/index.jsx
  src/components/Shareable/Sidebar/menus/MenuLancamentoInicial.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalObservacaoDiaria/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/components/ModalObservacaoDiaria/index.jsx
  src/configs/RoutesConfig.js
Labels: enhancement, feature

#3397 Hom - Atualizado em 08/09 as 15h55
  src/components/Shareable/Input/InputValueMedicao/index.jsx
  src/components/Shareable/Sidebar/menus/MenuLancamentoInicial.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalObservacaoDiaria/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/components/ModalObservacaoDiaria/index.jsx
  src/configs/RoutesConfig.js
Labels: enhancement, feature

#3403 Feature/101965-MI-alteração-regras-de-apontamento-repetição-sobremesa-doce
  src/components/Shareable/Input/InputValueMedicao/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
Labels: enhancement, feature

#3404 Hom - Atualizado em 11/09 as 18h25
  src/components/Shareable/Input/InputValueMedicao/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
Labels: enhancement, feature

#3411 Feature/100066-MI-tela-lançamento-manhã-e-tarde-alimentação-escolas-cei
  src/components/Shareable/Botao/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
Labels: enhancement, feature

#3415 Hom - Atualizado em 13/09 as 10h20
  src/components/Shareable/Botao/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
Labels: enhancement, feature

#3412 Feature/76255 inclusoes para medicao cei integral
  src/components/Shareable/Input/InputValueMedicao/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/validacoes.js
Labels: feature

#3419 HOM - Atualizado em 13/09 às 15:20h
  src/components/Shareable/Input/InputValueMedicao/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/validacoes.js
Labels: feature

#3427 Feature/100486-MI-tela-lançamento-manhã-e-tarde-dieta-especial-escolas-cei
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
Labels: enhancement

#3428 Hom - Atualizado em 13/09 as 19h10
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
Labels: enhancement

#3429 Feature: melhorias no código
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/validacoes.js
Labels: feature

#3431 Hom - Atualizado em 14/09 às 11:30h
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/validacoes.js
Labels: feature

#3440 Fix/104062-habilitar-kit-lanche-e-lanche-emergencial-para-medição-dias-não-letivos
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: bug, enhancement

#3441 Prod atualizado 14/09 as 17h50
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: bug, enhancement

#3442 Hom atualizado 14/09 as 17h50
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: bug, enhancement

#3443 Dev atualizado 14/09 as 18h
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: bug, enhancement

#3467 Feature/103188 medicao inclusoes evento especifico
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
  src/services/medicaoInicial/periodoLancamentoMedicao.service.js
Labels: feature

#3461 Feature/102647-MI-integração-gestão-alimentação-escolas-cei-manhã-e-tarde-não-letivo
  src/components/Shareable/Input/InputValueMedicao/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/validacoes.js
Labels: enhancement

#3473 Hom - Atualizado em 19/09 as 17h35
  src/components/Shareable/Input/InputValueMedicao/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/validacoes.js
Labels: enhancement

#3474 Feature/99995-MI-integração-gestão-alimentação-suspensão-alimentação-escolas-cei
  src/components/Shareable/Input/InputValueMedicao/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/validacoes.js
Labels: enhancement, feature

#3478 Hom - Atualizado em 20/09 as 13h05
  src/components/Shareable/Input/InputValueMedicao/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/validacoes.js
Labels: enhancement, feature

#3484 Feature: validar se o ultimo dia letivo do mês é menor que o dia atual
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/index.jsx
  src/services/medicaoInicial/periodoLancamentoMedicao.service.js
Labels: feature

#3490 Fix/104633-PeD_GA_DE-filtro-pesquisar-e-ver-mais
  src/components/Shareable/CardBody.jsx
  src/reducers/filtersAlimentacaoReducer.js
  src/reducers/filtersDietaReducer.js
Labels: bug

#3491 Hom - Atualizado em 22/09 as 12h30
  src/components/Shareable/CardBody.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/index.jsx
  src/reducers/filtersAlimentacaoReducer.js
  src/reducers/filtersDietaReducer.js
  src/services/medicaoInicial/periodoLancamentoMedicao.service.js
Labels: bug

#3500 HOM - Atualizado em 25/09 às 11:00h
  package.json
  src/components/Shareable/Input/InputFile/index.jsx
  src/components/Shareable/Sidebar/menus/MenuPreRecebimento.jsx
  src/components/screens/PreRecebimento/CadastroLayoutEmbalagem/components/ModalCancelar/index.jsx
  src/components/screens/PreRecebimento/CadastroLayoutEmbalagem/components/ModalConfirmar/index.jsx
  src/components/screens/PreRecebimento/CadastroLayoutEmbalagem/index.jsx
  src/components/screens/PreRecebimento/CadastroLayoutEmbalagem/styles.scss
  src/components/screens/PreRecebimento/LayoutEmbalagem/index.jsx
  src/components/screens/PreRecebimento/LayoutEmbalagem/styles.scss
  src/configs/RoutesConfig.js
  src/configs/constants.js
  src/pages/PreRecebimento/CadastroLayoutEmbalagemPage.jsx
  src/pages/PreRecebimento/LayoutEmbalagemPage.jsx
  src/services/cronograma.service.js
  src/services/layoutEmbalagem.service.js
Labels: feature

#3504 Fix: tratar state ao trocar de periodo medicão no seletor de datas
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/index.jsx
Labels: bug

#3505 HOM - Atualizado em 25/09 às 12:30h
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/index.jsx
Labels: bug

#3541 Feature: validar com backend periodos com valores incompletos e sinalizar para usuário
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/styles.scss
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/ModalFinalizarMedicao/index.jsx
Labels: feature

#3542 Hom - Aualizado 28/09 às 15:00h
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/styles.scss
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/ModalFinalizarMedicao/index.jsx
Labels: feature

#3547 Fix: passar set state para modal shareable
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/index.jsx
Labels: bug

#3548 HOM - Atualizado em 29/09 às 10:00h
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/index.jsx
Labels: bug
