Repository prefeiturasp/SME-Terceirizadas-Frontend, pull requests merged in 2023-12, with the labels that each got.

#3825 Feature/107027-MI-suspensão-alteração-CEMEI-pt3
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
Labels: bug, enhancement

#3826 Hom - Atualizado em 01/12 as 15h35
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
Labels: bug, enhancement

#3827 Feature/107027-MI-suspensão-alteração-CEMEI-pt4
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/validacoes.js
Labels: bug, enhancement

#3829 Hom - Atualizado em 01/12 as 17h25
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/validacoes.js
Labels: bug, enhancement

#3837 Feature/109280 regras lancamentos especiais
  src/components/screens/Cadastros/NovaPermissaoLancamentoEspecial/index.tsx
  src/components/screens/Cadastros/NovaPermissaoLancamentoEspecial/interfaces.ts
  src/components/screens/Cadastros/PermissaoLancamentosEspeciais/index.tsx
  src/helpers/utilities.js
Labels: feature

#3861 Hom - Atualizado em 11/12 as 11h05
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/styles.scss
  src/components/screens/PreRecebimento/FichaTecnica/components/Cadastrar/index.tsx
  src/components/screens/PreRecebimento/FichaTecnica/components/Filtros/index.tsx
  src/components/screens/PreRecebimento/FichaTecnica/components/Listagem/index.tsx
  src/components/screens/PreRecebimento/FichaTecnica/index.tsx
  src/services/fichaTecnica.service.ts
  src/services/medicaoInicial/permissaoLancamentosEspeciais.service.ts
Labels: enhancement, feature

#3862 Feature/109278-MI-integração-permissão-lançamentos-especiais-tela-lançamento-escolas-emef
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
Labels: enhancement

#3863 Hom - Atualizado em 11/12 as 14h40
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
Labels: enhancement

#3880 Feature/109838-MI-integração-permissão-lançamentos-especiais-tela-conferência-dre-medição-codae
  src/components/Shareable/Sidebar/menus/MenuLancamentoInicial.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
  src/services/diasUteis.service.js
Labels: enhancement, feature

#3883 Hom - Atualizado em 13/12 as 10h35
  src/components/Shareable/Sidebar/menus/MenuLancamentoInicial.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
  src/services/diasUteis.service.js
Labels: enhancement, feature

#3904 Hom - Atualizado em 15/12 as 10h40
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/CardLancamentoCEI/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/helpers.js
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/index.jsx
Labels: enhancement, feature

#3913 Feature/109985-MI-cálculo-alimentações-permissões-lançamentos-especiais-períodos-escolas-emef-emei
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/services/medicaoInicial/permissaoLancamentosEspeciais.service.ts
Labels: enhancement, feature

#3915 Hom - Atualizado em 20/12 as 10h35
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/services/medicaoInicial/permissaoLancamentosEspeciais.service.ts
Labels: enhancement, feature

#3940 Feature/110880-MI-tela-lançamento-solicitações-alimentação-escolas-cemei
  src/components/AlteracaoDeCardapio/helper.js
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/CardLancamentoCEI/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
Labels: enhancement, feature

#3941 Hom - Atualizado em 28/12 as 15h45
  src/components/AlteracaoDeCardapio/helper.js
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/CardLancamentoCEI/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
Labels: enhancement, feature

#3947 Feature/107036-MI-integração-lanche-emergencial-kit-lanche-escolas-cemei
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/helpers.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
Labels: enhancement, feature

#3950 Hom - Atualizado em 29/12 as 13h15
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/helpers.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
Labels: enhancement, feature
