Repository prefeiturasp/SME-Terceirizadas-Frontend, pull requests merged in 2023-01, with the labels that each got.

#2257 Bugfix/correcao calculo total kit lanche
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/KitLancheAvulsaCEMEIBody/index.jsx
Labels: bug

#2261 Feature/80959 retirar obrigatoriedade modal inversa cardapio
  src/components/InversaoDeDiaDeCardapio/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/Shareable/ModalCODAEAutoriza/index.jsx
Labels: feature

#2266 Hotfix/83155-GA-kit-lanche-passeio-ceu-gestao-não-validar-quantidade-de-matriculados
  src/components/SolicitacaoUnificada/Container.jsx
  src/components/SolicitacaoUnificada/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/SolicitacaoUnificada/Relatorio/index.jsx
  src/components/SolicitacaoUnificada/index.jsx
  src/components/screens/Cadastros/CadastroLote/components/ModalCadastroLote.jsx
  src/components/screens/Cadastros/CadastroLote/index.jsx
Labels: enhancement

#2267 Hotfix/83155-GA-kit-lanche-passeio-ceu-gestao-não-validar-quantidade-de-matriculados
  src/components/SolicitacaoUnificada/Container.jsx
  src/components/SolicitacaoUnificada/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/SolicitacaoUnificada/Relatorio/index.jsx
  src/components/SolicitacaoUnificada/index.jsx
  src/components/screens/Cadastros/CadastroLote/components/ModalCadastroLote.jsx
  src/components/screens/Cadastros/CadastroLote/index.jsx
Labels: enhancement

#2268 Hom Atualizado 03/01 as 19h10
  src/components/SolicitacaoUnificada/Container.jsx
  src/components/SolicitacaoUnificada/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/SolicitacaoUnificada/Relatorio/index.jsx
  src/components/SolicitacaoUnificada/index.jsx
  src/components/screens/Cadastros/CadastroLote/components/ModalCadastroLote.jsx
  src/components/screens/Cadastros/CadastroLote/index.jsx
Labels: enhancement

#2269 Dev Atualizado 03/01 as 20h30
  src/components/SolicitacaoUnificada/Container.jsx
  src/components/SolicitacaoUnificada/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/SolicitacaoUnificada/Relatorio/index.jsx
  src/components/SolicitacaoUnificada/index.jsx
  src/components/screens/Cadastros/CadastroLote/components/ModalCadastroLote.jsx
  src/components/screens/Cadastros/CadastroLote/index.jsx
Labels: enhancement

#2275 Feature/74279-MI-alterações-área-inf-básicas-medição-inicial
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/InformacoesMedicaoInicial/index.jsx
Labels: enhancement, feature

#2277 Feature/76113-DI-melhoria-para-deletar-objetos-SolicitacaoAberta-caso-necessário
  src/components/screens/DietaEspecial/Relatorio/index.jsx
  src/services/dietaEspecial.service.js
Labels: enhancement, feature

#2279 Hom Atualizado 09/01 as 13h30
  src/components/screens/DietaEspecial/Relatorio/index.jsx
  src/services/dietaEspecial.service.js
Labels: enhancement, feature

#2280 Feature/82438 filtros lotes dres para codae
  src/components/AlteracaoDeCardapio/CODAE/PainelPedidos/Container.jsx
  src/components/AlteracaoDeCardapio/CODAE/PainelPedidos/index.jsx
  src/components/InclusaoDeAlimentacao/CODAE/PainelPedidos/Container.jsx
  src/components/InclusaoDeAlimentacao/CODAE/PainelPedidos/index.jsx
  src/components/InversaoDeDiaDeCardapio/CODAE/PainelPedidos/Container.jsx
  src/components/InversaoDeDiaDeCardapio/CODAE/PainelPedidos/index.jsx
  src/components/Shareable/CardBodySemRedux.jsx
  src/components/SolicitacaoDeKitLanche/CODAE/PainelPedidos/Container.jsx
  src/components/SolicitacaoDeKitLanche/CODAE/PainelPedidos/index.jsx
  src/components/SolicitacaoUnificada/CODAE/PainelPedidos/Container.jsx
  src/components/SolicitacaoUnificada/CODAE/PainelPedidos/index.jsx
  src/components/screens/DashboardCODAE/Container.jsx
  src/components/screens/DashboardCODAE/index.jsx
  src/helpers/utilities.js
  src/pages/CODAE/AlteracaoDeCardapio/PainelPedidosPage.jsx
  src/pages/CODAE/InclusaoDeAlimentacao/PainelPedidosPage.jsx
  src/pages/CODAE/InversaoDiaCardapio/PainelPedidosPage.jsx
  src/pages/CODAE/SolicitacaoUnificada/PainelPedidosPage.jsx
  src/pages/SolicitacaoDeKitLanche/ContainerPage.jsx
  src/services/alteracaoDeCardapio/codae.service.js
  src/services/inclusaoDeAlimentacao/codae.service.js
  src/services/inversaoDeDiaDeCardapio.service.js
  src/services/kitLanche/codae.service.js
  src/services/painelCODAE.service.js
  src/services/solicitacaoUnificada.service.js
Labels: feature

#2293 Hom - Atualizado até 11/01 as 15:15
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/InclusaoCEIBody/index.jsx
Labels: feature

#2302 Feature: alterar label do Lanche 5h
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/ListagemLancamentos/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/TabelaLancamento/DietaConvencionalFrequencia.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/TabelaLancamento/DietaEspecial.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/helpers.js
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/ProgramasAutorizados/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
Labels: feature

#2306 HOM - Atualizada até 13/01 às 11:00
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/ListagemLancamentos/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/TabelaLancamento/DietaConvencionalFrequencia.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/TabelaLancamento/DietaEspecial.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/helpers.js
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/ProgramasAutorizados/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
Labels: feature

#2314 Hom Atualizado 16/01 as 10h40
  src/components/Shareable/Input/InputValueMedicao/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/styles.scss
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
  src/services/medicaoInicial/periodoLancamentoMedicao.service.js
Labels: enhancement, feature

#2315 Feature/bump dependabot
  package-lock.json
  package.json
Labels: dependencies

#2316 Fix: trocar multiselect para seletor único
  src/components/AlteracaoDeCardapio/CODAE/PainelPedidos/index.jsx
  src/components/InclusaoDeAlimentacao/CODAE/PainelPedidos/index.jsx
  src/components/InversaoDeDiaDeCardapio/CODAE/PainelPedidos/index.jsx
  src/components/SolicitacaoDeKitLanche/CODAE/PainelPedidos/index.jsx
  src/components/SolicitacaoUnificada/CODAE/PainelPedidos/index.jsx
  src/components/screens/DashboardCODAE/index.jsx
Labels: bug

#2318 Hom atualizado 17/01 as 11h00
  package-lock.json
  package.json
  src/components/AlteracaoDeCardapio/CODAE/PainelPedidos/index.jsx
  src/components/AlteracaoDeCardapio/index.jsx
  src/components/InclusaoDeAlimentacao/CODAE/PainelPedidos/index.jsx
  src/components/InversaoDeDiaDeCardapio/CODAE/PainelPedidos/index.jsx
  src/components/Shareable/FormBuscaProduto/index.js
  src/components/SolicitacaoDeKitLanche/CODAE/PainelPedidos/index.jsx
  src/components/SolicitacaoUnificada/CODAE/PainelPedidos/index.jsx
  src/components/screens/DashboardCODAE/index.jsx
Labels: bug

#2321 Forçando no front atribuir https
  src/components/screens/Configuracoes/CargasUsuarios/components/ListagemPlanilhas/index.jsx
Labels: bug

#2322 Feature/76113-DE-remover-bloqueio-websocket-ambiente-produção
  src/components/Shareable/CardStatusDeSolicitacao/CardStatusDeSolicitacao.jsx
  src/components/screens/DietaEspecial/Relatorio/index.jsx
Labels: enhancement

#2323 Hom Atualizado 17/01 as 17h
  src/components/Shareable/CardStatusDeSolicitacao/CardStatusDeSolicitacao.jsx
  src/components/screens/DietaEspecial/Relatorio/index.jsx
Labels: enhancement

#2329 Feature/77845 mensagem reset senha
  src/components/Shareable/InfoSenhaServidorMunicipal/index.jsx
  src/components/Shareable/InfoSenhaServidorMunicipal/style.scss
  src/components/screens/Perfil/components/ModalAlterarSenha/index.jsx
  src/pages/RecuperarSenhaPage.jsx
  src/services/auth.js
Labels: feature

#2337 Feature/80628 mensagem sucesso requisicao entrega
  src/components/screens/Logistica/GestaoRequisicaoEntrega/components/Confirmar/index.jsx
Labels: feature

#2341 Hom Atualizado 24/01 as 16h10
  src/components/Shareable/ModalCancelarSolicitacao_/index.jsx
  src/components/Shareable/RelatorioHistoricoJustificativaEscola/index.jsx
  src/components/SolicitacaoUnificada/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/SolicitacaoUnificada/Relatorio/index.jsx
  src/components/SolicitacaoUnificada/style.scss
  src/components/screens/helper.js
  src/configs/helper.js
  src/helpers/utilities.js
  src/pages/SolicitacaoUnificada/RelatoriosPage.jsx
  src/services/solicitacaoUnificada.service.js
Labels: enhancement, feature

#2342 Feature/82445 ga solicitacoes similares kit lanche
  src/components/Shareable/SolicitacoesSimilaresKitLanche/index.jsx
  src/components/Shareable/SolicitacoesSimilaresKitLanche/style.scss
  src/components/Shareable/style.scss
  src/components/SolicitacaoDeKitLanche/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/SolicitacaoDeKitLanche/Relatorio/index.jsx
  src/components/SolicitacaoDeKitLanche/components/CardPendenteAcao/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/components/CorpoRelatorio/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/index.jsx
  src/helpers/utilities.js
Labels: feature

#2347 HOM - Atualizado até 26/01
  src/components/Shareable/SolicitacoesSimilaresKitLanche/index.jsx
  src/components/Shareable/SolicitacoesSimilaresKitLanche/style.scss
  src/components/Shareable/style.scss
  src/components/SolicitacaoDeKitLanche/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/SolicitacaoDeKitLanche/Relatorio/index.jsx
  src/components/SolicitacaoDeKitLanche/components/CardPendenteAcao/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/components/CorpoRelatorio/index.jsx
  src/components/SolicitacaoKitLancheCEMEI/Relatorio/index.jsx
  src/components/screens/PreRecebimento/CronogramaEntrega/components/ListagemCronogramas/index.js
  src/helpers/utilities.js
Labels: feature

#2348 Fix: icone para solicitações similares, eslint em cronograma entrega
  src/components/SolicitacaoDeKitLanche/components/CardPendenteAcao/index.jsx
  src/components/screens/PreRecebimento/CronogramaEntrega/components/ListagemCronogramas/index.js
Labels: bug

#2349 HOM - Atualizado até 26/01
  src/components/SolicitacaoDeKitLanche/components/CardPendenteAcao/index.jsx
  src/components/screens/PreRecebimento/CronogramaEntrega/components/ListagemCronogramas/index.js
Labels: bug

#2359 Feature/82443 filtro lote para dashboard dre
  src/components/AlteracaoDeCardapio/DRE/PainelPedidos/Container.jsx
  src/components/AlteracaoDeCardapio/DRE/PainelPedidos/index.jsx
  src/components/InclusaoDeAlimentacao/DRE/PainelPedidos/Container.jsx
  src/components/InclusaoDeAlimentacao/DRE/PainelPedidos/index.jsx
  src/components/InversaoDeDiaDeCardapio/DRE/PainelPedidos/Container.jsx
  src/components/InversaoDeDiaDeCardapio/DRE/PainelPedidos/index.jsx
  src/components/SolicitacaoDeKitLanche/DRE/PainelPedidos/Container.jsx
  src/components/SolicitacaoDeKitLanche/DRE/PainelPedidos/index.jsx
  src/components/screens/DashboardCODAE/VisaoGeral.jsx
  src/components/screens/DashboardDRE/Container.jsx
  src/components/screens/DashboardDRE/index.jsx
  src/components/screens/PreRecebimento/AlterarCronograma/index.jsx
  src/pages/DRE/AlteracaoDeCardapio/PainelPedidosPage.jsx
  src/pages/DRE/InclusaoDeAlimentacao/PainelPedidosPage.jsx
  src/pages/DRE/InversaoDiaCardapio/PainelPedidosPage.jsx
  src/pages/SolicitacaoDeKitLanche/ContainerPage.jsx
  src/services/alteracaoDeCardapio/dre.service.js
  src/services/inclusaoDeAlimentacao/dre.service.js
  src/services/inversaoDeDiaDeCardapio.service.js
  src/services/kitLanche/dre.service.js
  src/services/painelDRE.service.js
Labels: feature

#2362 Hom - Atualizado até 27/01 as 12:00
  src/components/AlteracaoDeCardapio/DRE/PainelPedidos/Container.jsx
  src/components/AlteracaoDeCardapio/DRE/PainelPedidos/index.jsx
  src/components/InclusaoDeAlimentacao/DRE/PainelPedidos/Container.jsx
  src/components/InclusaoDeAlimentacao/DRE/PainelPedidos/index.jsx
  src/components/InversaoDeDiaDeCardapio/DRE/PainelPedidos/Container.jsx
  src/components/InversaoDeDiaDeCardapio/DRE/PainelPedidos/index.jsx
  src/components/SolicitacaoDeKitLanche/DRE/PainelPedidos/Container.jsx
  src/components/SolicitacaoDeKitLanche/DRE/PainelPedidos/index.jsx
  src/components/screens/DashboardCODAE/VisaoGeral.jsx
  src/components/screens/DashboardDRE/Container.jsx
  src/components/screens/DashboardDRE/index.jsx
  src/components/screens/PreRecebimento/AlterarCronograma/index.jsx
  src/pages/DRE/AlteracaoDeCardapio/PainelPedidosPage.jsx
  src/pages/DRE/InclusaoDeAlimentacao/PainelPedidosPage.jsx
  src/pages/DRE/InversaoDiaCardapio/PainelPedidosPage.jsx
  src/pages/SolicitacaoDeKitLanche/ContainerPage.jsx
  src/services/alteracaoDeCardapio/dre.service.js
  src/services/inclusaoDeAlimentacao/dre.service.js
  src/services/inversaoDeDiaDeCardapio.service.js
  src/services/kitLanche/dre.service.js
  src/services/painelDRE.service.js
Labels: feature

#2358 Feature/83976-GA-DRE-cancelar-solicitação-kit-lanche-unificado
  src/components/Shareable/ModalCancelarSolicitacao_/index.jsx
  src/components/Shareable/RelatorioHistoricoJustificativaEscola/index.jsx
  src/components/Shareable/RelatorioHistoricoJustificativaEscola/style.scss
  src/components/SolicitacaoUnificada/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/SolicitacaoUnificada/Relatorio/componentes/TabelaKits/index.jsx
  src/components/SolicitacaoUnificada/Relatorio/componentes/TabelaKits/style.scss
  src/components/SolicitacaoUnificada/Relatorio/index.jsx
  src/components/screens/helper.js
  src/helpers/utilities.js
  src/services/solicitacaoUnificada.service.js
Labels: enhancement, feature

#2364 Hom Atualizado 27/01 as 13h40
  src/components/Shareable/ModalCancelarSolicitacao_/index.jsx
  src/components/Shareable/RelatorioHistoricoJustificativaEscola/index.jsx
  src/components/Shareable/RelatorioHistoricoJustificativaEscola/style.scss
  src/components/SolicitacaoUnificada/Relatorio/componentes/CorpoRelatorio.jsx
  src/components/SolicitacaoUnificada/Relatorio/componentes/TabelaKits/index.jsx
  src/components/SolicitacaoUnificada/Relatorio/componentes/TabelaKits/style.scss
  src/components/SolicitacaoUnificada/Relatorio/index.jsx
  src/components/screens/DietaEspecial/CadastroProtocoloPadraoDietaEsp/componentes/SubstituicoesField/MultiSelect/Dropdown.jsx
  src/components/screens/DietaEspecial/CadastroProtocoloPadraoDietaEsp/componentes/SubstituicoesField/MultiSelect/StatefuMultiSelect.jsx
  src/components/screens/DietaEspecial/CadastroProtocoloPadraoDietaEsp/componentes/SubstituicoesField/MultiSelect/index.jsx
  src/components/screens/DietaEspecial/CadastroProtocoloPadraoDietaEsp/componentes/SubstituicoesField/MultiSelect/style.scss
  src/components/screens/DietaEspecial/CadastroProtocoloPadraoDietaEsp/componentes/SubstituicoesField/SubstituicaoFinalForm.jsx
  src/components/screens/DietaEspecial/CadastroProtocoloPadraoDietaEsp/componentes/SubstituicoesField/index.jsx
  src/components/screens/DietaEspecial/CadastroProtocoloPadraoDietaEsp/index.jsx
  src/components/screens/helper.js
  src/helpers/utilities.js
  src/services/solicitacaoUnificada.service.js
Labels: enhancement, feature

#2366 Feature/72324-MI-permissionamento-para-finalizar-medição-inicial
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
Labels: enhancement, feature

#2367 Hom Atualizado 30/01 as 12h25
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
Labels: enhancement, feature
