Repository prefeiturasp/SME-Terceirizadas-Frontend, pull requests merged in 2023-02, with the labels that each got.

#2381 Fix: exibição dos filtros
  src/components/Shareable/CardBody.jsx
Labels: bug

#2382 HOM - Atualizada até 01/02 às 15:00
  src/components/Shareable/CardBody.jsx
Labels: bug

#2389 Fix: tabela de faixas etárias CEI deve exibir apenas faixas com frequ…
  src/components/InclusaoDeAlimentacaoDaCei/TabelaFaixasCEI.jsx
  src/components/Shareable/TabelaFaixaEtaria/index.jsx
Labels: bug

#2390 Feature/73029-PeD-gestão-de-editais-suspender-produto-por-edital
  src/components/Shareable/FluxoDeStatus/helper.js
  src/components/screens/DashboardGestaoProduto/helper.js
  src/components/screens/Produto/AtivacaoSuspensao/AtivacaoSuspensaoDetalheProduto.jsx
  src/components/screens/Produto/AtivacaoSuspensao/ModalAtivacaoSuspensaoProduto/index.jsx
  src/components/screens/Produto/AtivacaoSuspensao/ModalAtivacaoSuspensaoProduto/style.scss
  src/components/screens/Produto/Homologacao/components/BotoesCabecalho.jsx
  src/components/screens/Produto/Homologacao/components/BotoesRodape.jsx
  src/components/screens/Produto/Homologacao/components/Container.jsx
  src/components/screens/Produto/Homologacao/components/EditaisVinculados.jsx
  src/components/screens/Produto/Homologacao/helper.js
  src/components/screens/Produto/Homologacao/index.jsx
  src/services/produto.service.js
Labels: enhancement, feature

#2391 Hom Atualizado 03/02 as 17h10
  src/components/InclusaoDeAlimentacaoDaCei/TabelaFaixasCEI.jsx
  src/components/Shareable/FluxoDeStatus/helper.js
  src/components/Shareable/TabelaFaixaEtaria/index.jsx
  src/components/screens/DashboardGestaoProduto/helper.js
  src/components/screens/Produto/AtivacaoSuspensao/AtivacaoSuspensaoDetalheProduto.jsx
  src/components/screens/Produto/AtivacaoSuspensao/ModalAtivacaoSuspensaoProduto/index.jsx
  src/components/screens/Produto/AtivacaoSuspensao/ModalAtivacaoSuspensaoProduto/style.scss
  src/components/screens/Produto/Homologacao/components/BotoesCabecalho.jsx
  src/components/screens/Produto/Homologacao/components/BotoesRodape.jsx
  src/components/screens/Produto/Homologacao/components/Container.jsx
  src/components/screens/Produto/Homologacao/components/EditaisVinculados.jsx
  src/components/screens/Produto/Homologacao/helper.js
  src/components/screens/Produto/Homologacao/index.jsx
  src/services/produto.service.js
Labels: enhancement, feature

#2395 Feature/84543-PeD-hover-tooltip-dashboard-cards-homologados-suspensos
  src/components/Shareable/CardStatusDeSolicitacao/CardStatusDeSolicitacao.jsx
  src/components/screens/DashboardGestaoProduto/helper.js
Labels: enhancement, feature

#2405 Hom Atualizado 07/02 as 12h10
  src/components/Shareable/Botao/constants.js
  src/components/Shareable/CardStatusDeSolicitacao/CardStatusDeSolicitacao.jsx
  src/components/Shareable/ModalAssinaturaUsuario/index.jsx
  src/components/Shareable/ModalAssinaturaUsuario/style.scss
  src/components/screens/DashboardGestaoProduto/helper.js
  src/components/screens/PreRecebimento/CronogramaEntrega/components/AcoesDetalhar/index.jsx
  src/services/cronograma.service.js
Labels: enhancement, feature

#2417 Feature/74333 exportar arquivo ocorrencias pdf
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/services/relatorios.js
Labels: feature

#2416 Feature/84946 inclusao alimentacao cci ceiceu
  src/components/InclusaoDeAlimentacao/Relatorio/componentes/CorpoRelatorio.jsx
  src/configs/helper.js
Labels: feature

#2427 Feature/76445-MI-salvamento-automático-dos-lançamentos
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/styles.scss
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: enhancement, feature

#2428 Hom Atualizado 10/02 as 12h15
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/styles.scss
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: enhancement, feature

#2431 HOM - atualizada até 10/02 às 16:40
  src/components/Shareable/Botao/index.jsx
  src/components/Shareable/Botao/style.scss
  src/components/screens/Cadastros/CadastroEmpresa/CadastroEmpresa.jsx
  src/components/screens/Cadastros/CadastroEmpresa/components/Form/LotesFormSet.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalSalvarLancamento/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/styles.scss
Labels: feature

#2441 Fix: desabilitar botão quando não houver anexos
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
Labels: bug

#2440 Fix: desabilitar quando o formulário não é válido
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: bug

#2442 HOM - atualizada até 14/02 às 11:20
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: bug

#2449 Fix: validação do disable
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
Labels: bug

#2450 HOM - atualizada até 14/02 às 18:00
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
Labels: bug

#2452 Fix: exibir tooltip
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalObservacaoDiaria/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: bug

#2453 HOM - atualizada até 14/02 às 20:00
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalObservacaoDiaria/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: bug

#2454 Feature/84834-MI-permitir-inclusão-informação-com-valor-zero
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
Labels: enhancement, feature

#2456 Fix: adicionar bypass para exception de obrigatoriedade de terminar url com /
  src/services/_base.js
Labels: bug

#2458 Fix/86552-PeD-card-produtos-suspensos-abrindo-tela-em-branco
  src/components/Shareable/DetalheDoProduto/index.jsx
  src/components/screens/Produto/AvaliarReclamacaoProduto/components/DadosProduto/index.jsx
Labels: bug

#2460 Fix: url
  src/services/relatorios.js
Labels: bug

#2467 Fix: corrigir estado do tooltip ao excluir a observação com um valor válido
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalObservacaoDiaria/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: bug

#2468 HOM - atualizado até 15/02 às 18:35
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalObservacaoDiaria/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: bug

#2461 Feature/86009 ajuste subdivisao coordenador produto e dieta
  src/components/screens/Configuracoes/GestaoAcesso/components/ModalCadastroVinculo/index.jsx
Labels: feature

#2470 Feature/85885-PeD-homologação-produtos-infos-volume-e-unid-medida
  src/components/screens/Produto/AtualizacaoProdutoForm/components/components/Especificacoes/index.jsx
  src/components/screens/Produto/Cadastro/Step3/components/Especificacoes/index.jsx
Labels: enhancement, feature

#2471 Hom Atualizado 16/02 às 12:45
  src/components/Shareable/Sidebar/menus/MenuGestaoDeAlimentacao.jsx
  src/components/screens/Produto/AtualizacaoProdutoForm/components/components/Especificacoes/index.jsx
  src/components/screens/Produto/Cadastro/Step3/components/Especificacoes/index.jsx
  src/configs/RoutesConfig.js
  src/pages/Relatorios/RelatorioSolicitacoesAlimentacaoPage.jsx
Labels: enhancement, feature

#2472 Feature/85896-GA-inclusao-alimentacao-lanche-emerg-ETECs
  src/components/InclusaoDeAlimentacao/Escola/Formulario/componentes/Container.jsx
  src/components/InclusaoDeAlimentacao/Escola/Formulario/componentes/InclusaoNormal/index.jsx
  src/components/InclusaoDeAlimentacao/Escola/Formulario/index.jsx
  src/components/Shareable/ModalDataPrioritaria/index.jsx
  src/components/screens/Produto/AtualizacaoProdutoForm/components/WizardFormTerceiraPagina.jsx
  src/components/screens/Produto/AtualizacaoProdutoForm/components/components/Especificacoes/index.jsx
  src/components/screens/Produto/Cadastro/Step3/components/Especificacoes/index.jsx
Labels: enhancement, feature

#2474 Hom Atualizado 17/02 às 10:00
  src/components/InclusaoDeAlimentacao/Escola/Formulario/componentes/Container.jsx
  src/components/InclusaoDeAlimentacao/Escola/Formulario/componentes/InclusaoNormal/index.jsx
  src/components/InclusaoDeAlimentacao/Escola/Formulario/index.jsx
  src/components/Shareable/ModalDataPrioritaria/index.jsx
  src/components/screens/Produto/AtualizacaoProdutoForm/components/WizardFormTerceiraPagina.jsx
  src/components/screens/Produto/AtualizacaoProdutoForm/components/components/Especificacoes/index.jsx
  src/components/screens/Produto/Cadastro/Step3/components/Especificacoes/index.jsx
Labels: enhancement, feature

#2491 Fix/GA-fix-campo-tipos-alimentação-solicitação-de-inclusão
  src/components/InclusaoDeAlimentacao/Escola/Formulario/componentes/InclusaoNormal/index.jsx
Labels: bug

#2492 Hom Atualizado 22/02 às 16:10
  src/components/InclusaoDeAlimentacao/Escola/Formulario/componentes/InclusaoNormal/index.jsx
Labels: bug

#2482 Feature/85719-PeD-tela-ativar-suspender--filtros-produtos-parcialmente-suspenso
  src/components/Shareable/DetalheDoProduto/index.jsx
  src/components/screens/Produto/AtivacaoSuspensao/FormBuscaProduto/index.js
  src/components/screens/Produto/AtivacaoSuspensao/FormBuscaProduto/style.scss
  src/components/screens/Produto/AtivacaoSuspensao/index.js
  src/components/screens/Produto/AtivacaoSuspensao/style.scss
Labels: enhancement, feature

#2494 Hom Atualizado 22/02 às 17:50
  src/components/Shareable/DetalheDoProduto/index.jsx
  src/components/Shareable/FormBuscaProduto/index.js
  src/components/Shareable/ModalAssinaturaUsuario/index.jsx
  src/components/screens/PreRecebimento/PainelAprovacoes/index.jsx
  src/components/screens/Produto/AtivacaoSuspensao/FormBuscaProduto/index.js
  src/components/screens/Produto/AtivacaoSuspensao/FormBuscaProduto/style.scss
  src/components/screens/Produto/AtivacaoSuspensao/index.js
  src/components/screens/Produto/AtivacaoSuspensao/style.scss
  src/components/screens/RelatorioProdutosHomologados/TabelaAgrupadaProdutosMarcas/index.js
  src/components/screens/RelatorioProdutosHomologados/TabelaAgrupadaProdutosMarcas/style.scss
  src/components/screens/RelatorioProdutosHomologados/TabelaAgrupadaProdutosTerceirizadas/index.js
  src/components/screens/RelatorioProdutosHomologados/index.js
  src/components/screens/RelatorioProdutosHomologados/style.scss
  src/services/cronograma.service.js
  src/services/produto.service.js
Labels: feature

#2500 Feature/84949 criar periodo externo inclusao cei
  src/components/InclusaoDeAlimentacaoDaCei/Container.jsx
  src/components/InclusaoDeAlimentacaoDaCei/TabelaFaixasCEI.jsx
  src/components/InclusaoDeAlimentacaoDaCei/helper.js
  src/components/InclusaoDeAlimentacaoDaCei/index.jsx
Labels: feature

#2501 Hom Atualizado 24/02 às 12:00
  src/components/InclusaoDeAlimentacaoDaCei/Container.jsx
  src/components/InclusaoDeAlimentacaoDaCei/TabelaFaixasCEI.jsx
  src/components/InclusaoDeAlimentacaoDaCei/helper.js
  src/components/InclusaoDeAlimentacaoDaCei/index.jsx
Labels: feature

#2502 Feature/72115-MI-integração-com-gestão-alimentação--suspensão-e-alteração
  src/components/Shareable/Input/InputValueMedicao/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
  src/services/medicaoInicial/periodoLancamentoMedicao.service.js
Labels: enhancement, feature

#2503 Hom Atualizado 24/02 às 14:20
  src/components/Shareable/Input/InputValueMedicao/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
  src/services/medicaoInicial/periodoLancamentoMedicao.service.js
Labels: enhancement, feature

#2520 Feature/85719-PeD-tela-ativar-suspender-produto-resultado-filtro-e-relatório
  src/components/Shareable/DetalheDoProduto/index.jsx
  src/components/screens/Produto/AtivacaoSuspensao/AtivacaoSuspensaoDetalheProduto.jsx
  src/components/screens/Produto/AtivacaoSuspensao/ModalAtivacaoSuspensaoProduto/index.jsx
  src/components/screens/Produto/AtivacaoSuspensao/index.js
Labels: enhancement, feature

#2524 Hom Atualizado 28/02 às 10:55
  src/components/Shareable/DetalheDoProduto/index.jsx
  src/components/screens/Produto/AtivacaoSuspensao/AtivacaoSuspensaoDetalheProduto.jsx
  src/components/screens/Produto/AtivacaoSuspensao/ModalAtivacaoSuspensaoProduto/index.jsx
  src/components/screens/Produto/AtivacaoSuspensao/index.js
Labels: enhancement, feature

#2521 Feature: aplicar nova modelagem para inclusão CEI (períodos externos)
  src/components/InclusaoDeAlimentacao/Relatorio/componentes/InclusoesCEI.jsx
Labels: feature
