Repository prefeiturasp/SME-Terceirizadas-Frontend, pull requests merged in 2023-08, with the labels that each got.

#3192 Fix: incluir produtos suspensos por CODAE aceitar reclamação
  src/components/screens/Produto/AtivacaoSuspensao/index.js
Labels: bug

#3193 HOM - Atualizado em 01/08/2023 às 10:40
  src/components/screens/Produto/AtivacaoSuspensao/index.js
Labels: bug

#3194 Fix: Breadcrump e log do período
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/pages/LancamentoMedicaoInicial/ConferenciaDosLancamentosPage.jsx
Labels: bug

#3250 Feature/71446-MI-tela-lançamento-integral-alimentação-escolas-cei-ceiceu-cci
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/CardLancamentoCEI/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/components/ModalErro/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/components/ModalObservacaoDiaria/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/components/ModalObservacaoDiaria/styles.scss
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/components/ModalSalvarCorrecoes/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/components/ModalVoltarPeriodoLancamento/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/styles.scss
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/validacoes.js
  src/configs/RoutesConfig.js
  src/configs/constants.js
  src/pages/LancamentoMedicaoInicial/PeriodoLancamentoMedicaoInicialCEIPage.jsx
  src/services/medicaoInicial/periodoLancamentoMedicao.service.js
Labels: enhancement, feature

#3253 Hom Atualizado 11/08 as 17h20
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/CardLancamento/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/CardLancamentoCEI/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/components/ModalErro/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/components/ModalObservacaoDiaria/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/components/ModalObservacaoDiaria/styles.scss
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/components/ModalSalvarCorrecoes/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/components/ModalVoltarPeriodoLancamento/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/styles.scss
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/validacoes.js
  src/configs/RoutesConfig.js
  src/configs/constants.js
  src/pages/LancamentoMedicaoInicial/PeriodoLancamentoMedicaoInicialCEIPage.jsx
  src/services/medicaoInicial/periodoLancamentoMedicao.service.js
Labels: enhancement, feature

#3261 Fix/101320-MI-validação-repetição-incorreta
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
Labels: bug

#3262 Prod atualizado 16/08 as 10h00
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
Labels: bug

#3264 Dev atualizado 16/08 as 11h00
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
Labels: bug

#3278 Feature/94889 criar historico correcoes periodo escolar
  src/components/Shareable/style.scss
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalHistoricoCorrecoesPeriodo/HistoricoAprovacao.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalHistoricoCorrecoesPeriodo/HistoricoCorrecaoEscola.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalHistoricoCorrecoesPeriodo/HistoricoCorrecaoSolicitada.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalHistoricoCorrecoesPeriodo/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalHistoricoCorrecoesPeriodo/style.scss
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/index.jsx
  src/helpers/utilities.js
Labels: feature

#3287 Feature: requisitar lotes e escolas apenas quando houver DRE uuid
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/index.jsx
Labels: feature

#3288 HOM - Atualizado em 21/08 às 11:20h
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/index.jsx
Labels: feature

#3294 Fix: habilitar toda coluna da tabela quando ao menos um campo for solicitado para correção
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
Labels: bug

#3295 Master - Atualizado em 22/08 às 11:30h
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
Labels: bug

#3296 MASTER > HOM - Atualizado em 22/08 às 11:40h
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
Labels: bug

#3299 Bugfix/100279 corrige problema colateral de acesso a tela de alteracao
  src/components/PreRecebimento/FormEtapa/helper.js
Labels: bug

#3314 Feature/71614-MI-tela-lançamento-integral-dieta-especial-escolas-cei
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/validacoes.js
  src/services/medicaoInicial/periodoLancamentoMedicao.service.js
Labels: enhancement, feature

#3315 Hom - Atualizado em 25/08 as 11h10
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/validacoes.js
  src/services/medicaoInicial/periodoLancamentoMedicao.service.js
Labels: enhancement, feature

#3324 Fix: adicionar tooltip, ajustar tamanho modal, ajustar font tabela
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalHistoricoCorrecoesPeriodo/HistoricoAprovacao.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalHistoricoCorrecoesPeriodo/HistoricoCorrecaoEscola.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalHistoricoCorrecoesPeriodo/HistoricoCorrecaoSolicitada.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalHistoricoCorrecoesPeriodo/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalHistoricoCorrecoesPeriodo/style.scss
Labels: bug

#3331 Feature/71444-MI-tela-lançamento-parcial-alimentação-escolas-cei
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
Labels: enhancement

#3332 Hom - Atualizado em 28/08 as 18h00
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
Labels: enhancement

#3341 Fix/102460-MI-erro-ao-preencher-zero-na-frequência-dia-não-letivo
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: bug

#3342 Fix/102411-MI-erro-ao-adicionar-observação-com-repetição-maior-que-frequência
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: bug

#3343 Hom - Atualizado em 29/08 as 14h55
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: bug

#3344 Feature: paginação ver mais dieta especial
  src/components/screens/DashBoardDietaEspecial/StatusSolicitacoes.jsx
  src/services/dashBoardDietaEspecial.service.js
Labels: feature

#3345 HOM - atualizado em 29/08 às 19:00
  src/components/Shareable/TabelaFaixaEtaria/index.jsx
  src/components/Shareable/TabelaFaixaEtaria/style.scss
  src/components/screens/DashBoardDietaEspecial/StatusSolicitacoes.jsx
  src/services/dashBoardDietaEspecial.service.js
Labels: feature

#3347 Fix: desativar item do histórico
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalHistoricoCorrecoesPeriodo/index.jsx
Labels: bug

#3348 HOM - Atualizado em 29/08 às 22:30h
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/ModalHistoricoCorrecoesPeriodo/index.jsx
Labels: bug

#3350 HOM - Atualizado em 30/08 às 12:00h
  src/components/screens/DashBoardDietaEspecial/StatusSolicitacoes.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: bug
