Repository prefeiturasp/SME-Terceirizadas-Frontend, pull requests merged in 2024-04, with the labels that each got.

#4415 Feature/117235-MI-pdf-relatório-controle-frequências-unidades-cei
  src/components/screens/Cadastros/CadastroTipoAlimentacao/index.jsx
  src/components/screens/LancamentoInicial/ControleDeFrequencia/index.tsx
  src/components/screens/LancamentoInicial/ControleDeFrequencia/styles.scss
  src/interfaces/controle_de_frequencia.ts
  src/services/medicaoInicial/controleDeFrequencia.service.ts
Labels: enhancement, feature

#4452 Feature/118769-DE-relatório-dietas-autorizadas-filtros-e-grid
  src/components/Shareable/CollapseFiltros/index.tsx
  src/components/Shareable/Sidebar/menus/MenuDietaEspecial.jsx
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/components/Filtros/index.jsx
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/components/Filtros/styles.scss
  src/components/screens/DietaEspecial/RelatorioDietaEspecial/index.jsx
  src/components/screens/DietaEspecial/RelatorioDietasAutorizadas/components/Filtros/index.jsx
  src/components/screens/DietaEspecial/RelatorioDietasAutorizadas/components/Filtros/styles.scss
  src/components/screens/DietaEspecial/RelatorioDietasAutorizadas/components/ListagemDietas/index.jsx
  src/components/screens/DietaEspecial/RelatorioDietasAutorizadas/components/ListagemDietas/styles.scss
  src/components/screens/DietaEspecial/RelatorioDietasAutorizadas/index.jsx
  src/components/screens/DietaEspecial/RelatorioDietasAutorizadas/styles.scss
  src/configs/RoutesConfig.js
  src/configs/constants.js
  src/pages/DietaEspecial/RelatorioDietasAutorizadas.jsx
  src/services/dietaEspecial.service.js
Labels: enhancement, feature

#4498 Feature/118803-DE-relatório-dietas-autorizadas-cards-quantidade
  src/components/screens/DietaEspecial/RelatorioDietasAutorizadas/components/Filtros/index.jsx
  src/components/screens/DietaEspecial/RelatorioDietasAutorizadas/index.jsx
  src/components/screens/DietaEspecial/RelatorioDietasAutorizadas/styles.scss
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/Filtros/index.jsx
  src/pages/DietaEspecial/RelatorioDietasAutorizadas.jsx
  src/services/relatorios.service.js
Labels: enhancement, feature

#4499 Hom - Atualizado em 18/04 as 10h
  src/components/screens/DietaEspecial/RelatorioDietasAutorizadas/components/Filtros/index.jsx
  src/components/screens/DietaEspecial/RelatorioDietasAutorizadas/index.jsx
  src/components/screens/DietaEspecial/RelatorioDietasAutorizadas/styles.scss
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/Filtros/index.jsx
  src/pages/DietaEspecial/RelatorioDietasAutorizadas.jsx
  src/services/relatorios.service.js
Labels: enhancement, feature

#4500 Feature/118803-DE-relatório-dietas-autorizadas-cards-quantidade
  src/components/screens/DietaEspecial/RelatorioDietasAutorizadas/index.jsx
Labels: enhancement

#4501 Hom - Atualizado em 18/04 as 11:40
  src/components/screens/DietaEspecial/RelatorioDietasAutorizadas/index.jsx
Labels: enhancement

#4519 Hotfix/120666 relatorio dieta especial vazio
  src/components/screens/DietaEspecial/RelatorioDietasAutorizadas/components/Filtros/index.jsx
Labels: bug

#4525 Feature/119254-CADASTROS-cadastro-sobremesa-doce-por-edital
  src/components/Shareable/Botao/constants.js
  src/components/Shareable/Calendario/componentes/ModalCadastrarNoCalendario/index.jsx
  src/components/Shareable/Calendario/componentes/ModalCadastrarNoCalendario/style.scss
  src/components/Shareable/Calendario/componentes/ModalEditar/index.jsx
  src/components/Shareable/Calendario/helpers.js
  src/components/Shareable/Calendario/index.jsx
Labels: enhancement, feature

#4526 Hom - Atualizado em 26/04 as 09:20
  src/components/Shareable/Botao/constants.js
  src/components/Shareable/Calendario/componentes/ModalCadastrarNoCalendario/index.jsx
  src/components/Shareable/Calendario/componentes/ModalCadastrarNoCalendario/style.scss
  src/components/Shareable/Calendario/componentes/ModalEditar/index.jsx
  src/components/Shareable/Calendario/helpers.js
  src/components/Shareable/Calendario/index.jsx
Labels: enhancement, feature

#4529 Feature/119255-CADASTROS-editais-e-contratos-add-campo-IMR
  src/components/Shareable/Calendario/componentes/ModalCadastrarNoCalendario/index.jsx
  src/components/Shareable/Calendario/componentes/ModalCadastrarNoCalendario/style.scss
  src/components/screens/Cadastros/EditaisContratosRefatorado/Cadastro/helper.tsx
  src/components/screens/Cadastros/EditaisContratosRefatorado/Cadastro/index.tsx
  src/components/screens/Cadastros/EditaisContratosRefatorado/Cadastro/style.scss
  src/components/screens/Cadastros/EditaisContratosRefatorado/ConsultaEditaisContratos/components/CamposEditalContrato.tsx
  src/components/screens/Cadastros/EditaisContratosRefatorado/ConsultaEditaisContratos/components/ListaContratoEdital.tsx
  src/components/screens/Cadastros/EditaisContratosRefatorado/ConsultaEditaisContratos/style.scss
  src/components/screens/Cadastros/EditaisContratosRefatorado/interfaces.tsx
Labels: enhancement, feature

#4530 Hom - Atualizado em 26/04 as 16:00
  src/components/Shareable/Calendario/componentes/ModalCadastrarNoCalendario/index.jsx
  src/components/Shareable/Calendario/componentes/ModalCadastrarNoCalendario/style.scss
  src/components/screens/Cadastros/EditaisContratosRefatorado/Cadastro/helper.tsx
  src/components/screens/Cadastros/EditaisContratosRefatorado/Cadastro/index.tsx
  src/components/screens/Cadastros/EditaisContratosRefatorado/Cadastro/style.scss
  src/components/screens/Cadastros/EditaisContratosRefatorado/ConsultaEditaisContratos/components/CamposEditalContrato.tsx
  src/components/screens/Cadastros/EditaisContratosRefatorado/ConsultaEditaisContratos/components/ListaContratoEdital.tsx
  src/components/screens/Cadastros/EditaisContratosRefatorado/ConsultaEditaisContratos/style.scss
  src/components/screens/Cadastros/EditaisContratosRefatorado/interfaces.tsx
Labels: enhancement, feature
