Repository prefeiturasp/SME-Terceirizadas-Frontend, pull requests merged in 2024-01, with the labels that each got.

#3957 Feature/107032-MI-integração-medição-inclusao-alimentação-período-parcial-n-letivo-escolas-cemei
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
Labels: enhancement

#3958 Hom - Atualizado em 02/01 as 17h35
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
Labels: enhancement

#3972 Feature/111738-MI-tela-inicial-programas-e-projetos-escolas-cemei
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/helpers.js
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/CardLancamentoCEI/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
Labels: enhancement, feature

#3975 Feature/109836 integracao lancamentos especiais cemei
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
Labels: feature

#3978 Hom - Atualizado em 08/01 as 11h50
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/helpers.js
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/CardLancamentoCEI/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
Labels: enhancement, feature

#3993 Feature/110892-MI-tela-lançamento-programas-e-projetos-escolas-cemei
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/CardLancamentoCEI/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/validacoes.js
Labels: enhancement, feature

#3995 Hom - Atualizado em 10/01 as 12h35
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/CardLancamentoCEI/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/validacoes.js
Labels: enhancement, feature

#3996 Feature/110892-MI-tela-lançamento-programas-e-projetos-escolas-cemei-pt2
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/index.jsx
Labels: enhancement

#3997 Hom - Atualizado em 10/01 as 13h30
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/index.jsx
Labels: enhancement

#4008 Feature/103874-MI-botão-finalizar-períodos-comuns-escolas-ceu-gestão
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
Labels: enhancement, feature

#4009 Hom - Atualizado em 12/01 as 15h45
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodo/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
Labels: enhancement, feature

#4016 Feature/111634-MI-botão-finalizar-solicitações-de-alimentação-ceu-gestão
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
Labels: enhancement

#4019 Hom - Atualizado em 15/01 as 17h
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
Labels: enhancement

#4027 Feature/111634-MI-botão-finalizar-solicitações-de-alimentação-ceu-gestão
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: enhancement

#4028 Hom - Atualizado em 16/01 as 11h45
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: enhancement

#4050 Feature/112106-DE-tela-detalhes-dieta-do-aluno-para-aluno-nao-matriculado
  src/components/screens/DietaEspecial/Aluno/index.jsx
  src/components/screens/DietaEspecial/AtivasInativasPorAluno/components/TabelaResultados/index.jsx
  src/services/dietaEspecial.service.js
  src/services/perfil.service.js
Labels: enhancement, feature

#4051 Hom - Atualizado em 18/01 as 13h40
  src/components/screens/DietaEspecial/Aluno/index.jsx
  src/components/screens/DietaEspecial/AtivasInativasPorAluno/components/TabelaResultados/index.jsx
  src/services/dietaEspecial.service.js
  src/services/perfil.service.js
Labels: enhancement, feature

#4056 PROD: atualizado em 19/01/2024 as 16:10
  src/components/AlteracaoDeCardapio/helper.js
  src/components/AlteracaoDeCardapio/index.jsx
Labels: bug

#4057 HOM: atualizado em 19/01/2024 as 16:15 (descendo)
  src/components/AlteracaoDeCardapio/helper.js
  src/components/AlteracaoDeCardapio/index.jsx
Labels: bug

#4058 DEV: atualizado em 19/01/2024 as 16:30 (descendo)
  src/components/AlteracaoDeCardapio/helper.js
  src/components/AlteracaoDeCardapio/index.jsx
Labels: bug

#4059 Fix/corrige-acompanhamento-lançamento-tela-conferência-dre-codae
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
Labels: bug

#4060 PROD: atualizado em 22/01/2024 as 12:30
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
Labels: bug

#4061 HOM: atualizado em 22/01/2024 as 13h (descendo)
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
Labels: bug

#4095 Feature/112055-MI-tela-conferência-lançamentos-dre-medição-escolas-cemei
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/LegendaDiasNaoLetivos/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/CardLancamentoCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
Labels: enhancement, feature

#4096 Hom - Atualizado em 30/01 as 18h25
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/LegendaDiasNaoLetivos/index.jsx
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/LancamentoMedicaoInicial/components/LancamentoPorPeriodoCEI/CardLancamentoCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
Labels: enhancement, feature
