Repository prefeiturasp/SME-Terceirizadas-Frontend, pull requests merged in 2024-02, with the labels that each got.

#4124 Prod atualizado 06/02 as 10h51
  src/pages/Cadastros/CadastroKitLanchePage.jsx
  src/pages/DietaEspecial/CriarCopiaProtocoloPadraoDieta.jsx
  src/pages/DietaEspecial/EditaProtocoloPadraoDieta.jsx
Labels: bug

#4133 Feature/103253-MI-tela-lançamento-manhã-tarde-escola-emebs
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalObservacaoDiaria/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/styles.scss
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/styles.scss
  src/components/screens/LancamentoInicial/constants.js
  src/components/screens/PreRecebimento/AlterarCronograma/index.jsx
  src/helpers/utilities.js
  src/services/auth.js
Labels: enhancement, feature

#4137 Hom - Atualizado em 07/02 as 18h45
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalObservacaoDiaria/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/styles.scss
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/styles.scss
  src/components/screens/LancamentoInicial/constants.js
  src/components/screens/PreRecebimento/AlterarCronograma/index.jsx
  src/helpers/utilities.js
  src/services/auth.js
Labels: enhancement, feature

#4145 Feature/113179 refatora consulta editais contratos
  src/components/screens/Cadastros/EditaisContratos/EditaisCadastrados/index.jsx
  src/components/screens/Cadastros/EditaisContratosRefatorado/Cadastro/ModalCadastroEdital.tsx
  src/components/screens/Cadastros/EditaisContratosRefatorado/Cadastro/index.tsx
  src/components/screens/Cadastros/EditaisContratosRefatorado/Cadastro/style.scss
  src/components/screens/Cadastros/EditaisContratosRefatorado/ConsultaEditaisContratos/components/CamposEditalContrato.tsx
  src/components/screens/Cadastros/EditaisContratosRefatorado/ConsultaEditaisContratos/components/Header.tsx
  src/components/screens/Cadastros/EditaisContratosRefatorado/ConsultaEditaisContratos/components/ListaContratoEdital.tsx
  src/components/screens/Cadastros/EditaisContratosRefatorado/ConsultaEditaisContratos/constants.tsx
  src/components/screens/Cadastros/EditaisContratosRefatorado/ConsultaEditaisContratos/index.tsx
  src/components/screens/Cadastros/EditaisContratosRefatorado/ConsultaEditaisContratos/style.scss
  src/components/screens/Cadastros/EditaisContratosRefatorado/interfaces.tsx
  src/interfaces/responses.interface.ts
  src/pages/Cadastros/EditaisCadastradosPage.jsx
  src/services/edital.service.js
Labels: feature

#4154 Fix/114743-SIGPAE-acesso-perfil-gabinete
  src/components/Shareable/CardStatusDeSolicitacao/CardStatusDeSolicitacao.jsx
  src/components/Shareable/FormBuscaProduto/index.js
  src/components/Shareable/Sidebar/SidebarContent.jsx
  src/components/Shareable/Sidebar/menus/MenuDietaEspecial.jsx
  src/components/Shareable/Sidebar/menus/MenuGestaoDeAlimentacao.jsx
  src/components/Shareable/Sidebar/menus/MenuLancamentoInicial.jsx
  src/components/Shareable/Sidebar/menus/MenuRelatorios.jsx
  src/components/screens/DashboardGestaoProduto/helper.js
  src/components/screens/DietaEspecial/Relatorio/index.jsx
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/index.jsx
  src/components/screens/PainelInicial/index.jsx
  src/components/screens/PreRecebimento/AlterarCronograma/index.jsx
  src/components/screens/Produto/BuscaAvancada/components/RelatorioProduto/components/corpoRelatorio/index.jsx
  src/components/screens/Produto/BuscaAvancada/components/RelatorioProduto/components/resultadoMock/index.jsx
  src/components/screens/Produto/RelatorioReclamacaoProduto/components/ModalRelatorioReclamacao/index.jsx
  src/components/screens/Produto/RelatorioReclamacaoProduto/components/ModalRelatorioReclamacao/styles.scss
  src/components/screens/Produto/ResponderReclamacao/helpers.js
  src/configs/RoutesConfig.js
  src/configs/helper.js
  src/constants/shared.js
  src/helpers/gestaoDeProdutos.js
  src/helpers/utilities.js
  src/pages/Produto/StatusSolicitacoesGestaoProduto.jsx
  src/pages/Relatorios/RelatorioSolicitacoesAlimentacaoPage.jsx
Labels: enhancement, feature

#4157 DEV: atualizado em 09/01/2024 as 14:50 (descendo)
  src/components/Shareable/CardStatusDeSolicitacao/CardStatusDeSolicitacao.jsx
  src/components/Shareable/FormBuscaProduto/index.js
  src/components/Shareable/Sidebar/SidebarContent.jsx
  src/components/Shareable/Sidebar/menus/MenuDietaEspecial.jsx
  src/components/Shareable/Sidebar/menus/MenuGestaoDeAlimentacao.jsx
  src/components/Shareable/Sidebar/menus/MenuLancamentoInicial.jsx
  src/components/Shareable/Sidebar/menus/MenuRelatorios.jsx
  src/components/screens/DashboardGestaoProduto/helper.js
  src/components/screens/DietaEspecial/Relatorio/index.jsx
  src/components/screens/LancamentoInicial/AcompanhamentoDeLancamentos/index.jsx
  src/components/screens/PainelInicial/index.jsx
  src/components/screens/Produto/BuscaAvancada/components/RelatorioProduto/components/corpoRelatorio/index.jsx
  src/components/screens/Produto/BuscaAvancada/components/RelatorioProduto/components/resultadoMock/index.jsx
  src/components/screens/Produto/RelatorioReclamacaoProduto/components/ModalRelatorioReclamacao/index.jsx
  src/components/screens/Produto/RelatorioReclamacaoProduto/components/ModalRelatorioReclamacao/styles.scss
  src/components/screens/Produto/ResponderReclamacao/helpers.js
  src/configs/RoutesConfig.js
  src/configs/helper.js
  src/constants/shared.js
  src/helpers/gestaoDeProdutos.js
  src/helpers/utilities.js
  src/pages/Produto/StatusSolicitacoesGestaoProduto.jsx
  src/pages/Relatorios/RelatorioSolicitacoesAlimentacaoPage.jsx
Labels: enhancement, feature

#4158 Fix/114743-SIGPAE-acesso-perfil-gabinete
  src/helpers/utilities.js
Labels: enhancement, feature

#4159 PROD: atualizado em 09/02/2024 as 15:45
  src/helpers/utilities.js
Labels: enhancement, feature

#4160 HOM: atualizado em 09/01/2024 as 15:50 (descendo)
  src/helpers/utilities.js
Labels: enhancement, feature

#4161 DEV: atualizado em 09/01/2024 as 16h (descendo)
  src/helpers/utilities.js
Labels: enhancement, feature

#4171 Feature/105949-MI-tela-lançamento-dieta-especial-escolas-emebs
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: enhancement, feature

#4172 Hom - Atualizado em 13/02 as 13h20
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: enhancement, feature

#4194 Feature/105951-MI-tela-lançamento-programas-e-projetos-escolas-emebs
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
Labels: enhancement, feature

#4195 Hom - Atualizado em 15/02 as 10h
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/validacoes.js
Labels: enhancement, feature

#4196 Feature/113221-MI-salvamento-automático-abas-infantil-e-fundamental-escolas-emebs
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: enhancement, feature

#4197 Hom - Atualizado em 15/02 as 12h05
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: enhancement, feature

#4199 Feature/MI-ajustes-lançamentos-medição
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalErro/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
Labels: enhancement

#4200 Hom - Atualizado em 19/02 as 11h40
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/components/ModalErro/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicialCEI/index.jsx
Labels: enhancement

#4221 Feature/113228-MI-tela-conferência-lançamentos-dre-medição-escolas-emebs
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
Labels: enhancement, feature

#4222 Hom - Atualizado em 23/02 as 09h55
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
Labels: enhancement, feature

#4223 Feature/114735 justificativa exclusao edital
  src/components/screens/Produto/Homologacao/components/ModelVincularEditais/index.jsx
  src/components/screens/Produto/Homologacao/index.jsx
  src/services/produto.service.js
Labels: feature

#4232 Feature/114982-MI-salvamento-solicitação-correção-períodos-enviados-escolas-emebs
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
Labels: enhancement, feature

#4233 Hom - Atualizado em 26/02 as 18h32
  src/components/screens/LancamentoInicial/ConferenciaDosLancamentos/components/TabelaLancamentosPeriodo/index.jsx
Labels: enhancement, feature

#4234 Bugfix/ajusta label nome escola
  src/components/Shareable/Sidebar/helpers.js
Labels: bug

#4237 Hom - Atualizado em 27/02 as 12h45
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
  src/configs/RoutesConfig.js
Labels: enhancement, feature
