Repository prefeiturasp/SME-Terceirizadas-Frontend, pull requests merged in 2024-03, with the labels that each got.

#4256 Feature/113303-MI-botão-finalizar-escolas-emebs-períodos-manhã-tarde-comuns
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: enhancement, feature

#4264 Hom - Atualizado em 01/03 as 13h45
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/index.jsx
Labels: enhancement, feature

#4271 Feature/113229-validação-programas-projetos-emebs
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
Labels: enhancement

#4274 Hom - Atualizado em 01/03 as 20h
  src/components/screens/LancamentoInicial/PeriodoLancamentoMedicaoInicial/helper.js
Labels: enhancement

#4291 Feature/115761-GA-inclusão-ali-contínua-lanche4h-refeição-e-sobremesa
  src/components/InclusaoDeAlimentacao/Escola/Formulario/componentes/InclusaoContinua/index.jsx
  src/components/Shareable/MakeField/styles.scss
Labels: enhancement, feature

#4292 Hom - Atualizado em 06/03 as 18h
  src/components/InclusaoDeAlimentacao/Escola/Formulario/componentes/InclusaoContinua/index.jsx
  src/components/Shareable/MakeField/styles.scss
Labels: enhancement, feature

#4302 Hotfix/117125-DE-dietas-negadas-retirar-dados-nutri
  src/components/Shareable/FluxoDeStatus/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/CorpoRelatorio/FluxoDeStatusDieta.jsx
Labels: enhancement, feature

#4304 PROD: atualizado em 07/03/2024 as 17:30
  src/components/Shareable/FluxoDeStatus/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/CorpoRelatorio/FluxoDeStatusDieta.jsx
Labels: enhancement, feature

#4305 HOM: atualizado em 08/03/2024 as 10h (descendo)
  src/components/Shareable/FluxoDeStatus/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/CorpoRelatorio/FluxoDeStatusDieta.jsx
Labels: enhancement, feature

#4318 Feature/115754 relatorio solicitacoes alimentacao totalizadores
  public/index.html
  src/components/screens/Relatorios/SolicitacoesAlimentacao/componentes/Filtros/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/index.jsx
  src/components/screens/Relatorios/SolicitacoesAlimentacao/style.scss
  src/services/relatorios.service.js
Labels: feature

#4326 Feature/101667-MI-relatório-adesão-dre
  src/components/Shareable/CollapseFiltros/index.tsx
  src/components/Shareable/Sidebar/menus/MenuLancamentoInicial.jsx
  src/components/screens/LancamentoInicial/Relatorios/RelatorioAdesao/components/FormFiltro/index.tsx
  src/components/screens/LancamentoInicial/Relatorios/RelatorioAdesao/components/FormFiltro/view.ts
  src/components/screens/LancamentoInicial/Relatorios/RelatorioAdesao/index.tsx
  src/components/screens/LancamentoInicial/Relatorios/RelatorioAdesao/view.ts
  src/configs/RoutesConfig.js
Labels: enhancement, feature

#4327 Hom - Atualizado em 12/03 as 10:05
  src/components/Shareable/CollapseFiltros/index.tsx
  src/components/Shareable/Sidebar/menus/MenuLancamentoInicial.jsx
  src/components/screens/LancamentoInicial/Relatorios/RelatorioAdesao/components/FormFiltro/index.tsx
  src/components/screens/LancamentoInicial/Relatorios/RelatorioAdesao/components/FormFiltro/view.ts
  src/components/screens/LancamentoInicial/Relatorios/RelatorioAdesao/index.tsx
  src/components/screens/LancamentoInicial/Relatorios/RelatorioAdesao/view.ts
  src/configs/RoutesConfig.js
Labels: enhancement, feature

#4333 Feature/101650-MI-relatório-de-adesão-ue
  src/components/Shareable/CollapseFiltros/index.tsx
  src/components/Shareable/Sidebar/menus/MenuLancamentoInicial.jsx
  src/components/screens/LancamentoInicial/Relatorios/RelatorioAdesao/components/FormFiltro/index.tsx
  src/components/screens/LancamentoInicial/Relatorios/RelatorioAdesao/components/FormFiltro/view.ts
  src/components/screens/LancamentoInicial/Relatorios/RelatorioAdesao/index.tsx
  src/components/screens/LancamentoInicial/Relatorios/RelatorioAdesao/view.ts
  src/configs/RoutesConfig.js
  src/services/auth.js
Labels: enhancement, feature

#4334 Hom - Atualizado em 13/03 as 10:50
  src/components/Shareable/CollapseFiltros/index.tsx
  src/components/Shareable/Sidebar/menus/MenuLancamentoInicial.jsx
  src/components/screens/LancamentoInicial/Relatorios/RelatorioAdesao/components/FormFiltro/index.tsx
  src/components/screens/LancamentoInicial/Relatorios/RelatorioAdesao/components/FormFiltro/view.ts
  src/components/screens/LancamentoInicial/Relatorios/RelatorioAdesao/index.tsx
  src/components/screens/LancamentoInicial/Relatorios/RelatorioAdesao/view.ts
  src/configs/RoutesConfig.js
  src/services/auth.js
Labels: enhancement, feature

#4352 Hom - Atualizado em 15/03 as 09:20
  src/components/screens/LancamentoInicial/Relatorios/RelatorioAdesao/components/FormFiltro/view.ts
  src/components/screens/LancamentoInicial/Relatorios/RelatorioAdesao/view.ts
Labels: enhancement, feature

#4371 Fix/117125-DE-dietas-negadas-retirar-dados-nutri-ajuste-dre
  src/components/Shareable/FluxoDeStatus/index.jsx
Labels: bug

#4372 Hom - Atualizado em 19/03 as 11:20
  src/components/Shareable/FluxoDeStatus/index.jsx
Labels: bug

#4383 Feature/117133-ajuste-ASelect
  src/components/Shareable/MakeField/index.jsx
  src/components/screens/Cadastros/CadastroTipoAlimentacao/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/Protocolos/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/SubstituicoesField/SubstituicaoFinalForm.jsx
Labels: enhancement

#4384 Hom - Atualizado em 21/03 as 15:25
  src/components/Shareable/MakeField/index.jsx
  src/components/screens/Cadastros/CadastroTipoAlimentacao/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/Protocolos/index.jsx
  src/components/screens/DietaEspecial/Relatorio/componentes/FormAutorizaDietaEspecial/componentes/SubstituicoesField/SubstituicaoFinalForm.jsx
Labels: enhancement
